.INCLUDE	%CMN:COMMON%
TITLE	PBSCMN,<QUEUE CONSTANTS>,0A,10-MAY-91,PRL/ACT/TJK/DBM

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	PBSCMN Edit History
;+
; EDIT	BY   DATE	REASON
;  001	PRL  13-Jul-82	Creation
;  002	PRL  04-Nov-82	Add CC.FLG%, QUE.OPEN% flag words
;  003	DRP  08-Jan-83	Added REPAINT% flag word and INDENT% constant
;  004	DRP  10-Jan-83	Added FATAL% flag and SPLONL constant
;  005	DRP  10-Jan-83	Added /QUEUE, /OWNER and /NAME cmnd line
;			position pointers
;  006	ACT  08-Feb-83	Added ID.ASN% for /[NO]SHARABLE
;  007	PRL  27-Jun-83	Update for V9.0
;  008	PRL  28-Jun-84	Add RCVxxx globals
;  009	PRL  08-Aug-84	Add PBSLOC (PBS package location) string
;  010	PRL  24-Sep-84	Add FRMCTL, DFLCHR constants
;			Remove DFLSIM constant
;  011	PRL  05-Oct-84	Add C.POS global (C.POS%)
;  012	PRL  27-Oct-84	Remove INDENT global
;  013	PRL  15-Jan-85	Add DFLBOT constant
;  014	PRL  29-Jan-85	Update PBS version no. (7.)
;  015	PRL  20-Jan-85	Update length of CD,CQ,JB,ID,MS packets
;  016	PRL  16-Feb-85	Change MODULE$ string to ERRNAM$ string
;  017  TJK  10-SEP-85  Add bits for [NO]TRAILER_PAGES
;  018	DBM  06-Feb-87	Add notify timer for receiver waits
;
;			[RSTS/E V9.6]
;  019	DBM  16-Feb-88	Add bits for /[NO]WRAP
;
;			[RSTS/E V10.0]
;  020  PRL  27-Jun-89	Change JS.ILL (illegal) to JS.FRM (forms wait)
;  021  PRL  03-Jul-89	Use channel 0 for KB.CHNL%
;			Define OUT.CHNL% (1) for new /OUTPUT display
;  022  PRL  20-Jul-89	Add JBF.NTF% (NOTIFY flag bit)
;  023  JJT  22-Dec-89	Change OUT.CHNL% to SHO.CHNL%
;-

.SBTTL	Define and order the PSECTS

	.PSECT	PBSCMN,RW,D,GBL,REL,OVR

.SBTTL	define macro to build string

	.MACRO	STRING	LENGTH=1,FILL=32.,TEXT
	$$$$$$=.
	.BLKB0	LENGTH,FILL
	.IF NB	<TEXT>
	.=$$$$$$
	.ASCII	%TEXT%
	.=$$$$$$+LENGTH
	.ENDC
	.EVEN
	.ENDM	STRING

.SBTTL	Assign values to PBSCMN common

;		value			BP2 variable	usage
;		=====			============	=====

; define job constants

	.WORD	0.			;PPN%		user PPN
	.WORD	0.			;JOB.NO%	user job no.
	.WORD	0.			;KB.NO%		user KB no.
	.WORD	0.			;KB.WIDTH%	width of user KB

; define debugger

DEBUG::	.WORD	0.			;DEBUG%		enable debugger (off)

; define display flags

DSPLAY::.WORD	-1.			;DISPLAY%	display msgs flag (on)
LITERL::.WORD	0.			;LITERAL%	display literal flg (off)
C.POS::	.WORD	0.			;C.POS%		conflicting qual pos

; define the flag to allow/disallow the DBUG command

ALWDBG::.WORD	0.			;ALWDBG%	allow DBUG (disallow)

; define the flag to disable sending command packet

NOSEND::.WORD	0.			;NOSEND%	no send cmd packet

; define command line positions for queue name, PPN and job name

	.WORD	0.			;QUE.POS%	queue name position
	.WORD	0.			;OWN.POS%	PPN position
	.WORD	0.			;NAM.POS%	job name position

; define error status word

ERRSTS::.WORD	0.			;ERRSTS%	error status code
	.WORD	0.			;ERRLIN%	error line no.

; define error (sub)program name string

	STRING	6.			;ERRNAM$	error (sub)program name

; define fatal error flag

	.WORD	0.			;FATAL%		fatal error found (off)

; define send packet ID word

	.WORD	0.			;SEND.ID%	send packet ID word

; define ACK request flag

ACKFLG::.WORD	1.			;AK.FLG%	ACK request flag

; define max retries on send 

SNDRTY::.WORD	10.			;SEND.RETRY%	max retries on send

; define max receiver wait time in seconds

RCVWAI::.WORD	90.			;RECV.WAIT%	recv wait in sec.   ;018

; define notify time for receiver wait in seconds			    ;018

NOTWAI::.WORD	15.			;NOTIFY.WAIT%	notify time in sec. ;018

; define boolean constants

	.WORD	-1.			;TRUE%		boolean true
	.WORD	0			;FALSE%		boolean false

;define integer constants

	.WORD	32767.			;MAXINT%	maximum integer

; define PBS packet version no.

PBSVER::.WORD	7.			;PBS.VER%	PBS packet version

; define program entry type

	.WORD	0.			;ENT.TY%	QUEUE entry type

; define event flags

CCFLAG::.WORD	0.			;CC.FLG%	CTRL/C-detected flag
	.WORD	0.			;RCVR.DCLR%	rcvr-declared flag

; define queue manager local object type

QMNLOT::.WORD	3.			;QMAN.LOT%	queue mgr local obj type

; define PBS package location

PBSLOC::STRING	14.,32.,<PBS$:>		;PBS.LOC$	PBS package location

; define PBS files

PBSFIL::STRING	10.,32.,<PBS.SYS>	;PBS.FIL$	PBS system file
PBSTSK::STRING	10.,32.,<PBS.TSK>	;PBS.TSK$	PBS task file
FRMFIL::STRING	10.,32.,<FORMS.SYS>	;FRM.FIL$	forms def file
SETFIL::STRING	10.,32.,<SETUP.SYS>	;SET.FIL$	set-up def file

; define channel assignments

PBSCHL::.WORD	0.			;KB.CHNL%	user's KB channel ;021
	.WORD	12.			;SHO.CHNL%	output dev channel ;023
	.WORD	2.			;PBS.CHNL%	PBS file channel
	.WORD	3.			;PKT.CHNL%	s/r packet channel
	.WORD	4.			;FRM.CHNL%	forms file channel
	.WORD	5.			;SET.CHNL%	set-up file channel

; define priv on/off sys call

PBSSYS::.BYTE	6.,-21.,0.		;PRIV.ON$	PRIV ON sys call
	.BYTE	6.,-21.,255.		;PRIV.OFF$	PRIV OFF sys call

; define useful strings

PBSSTR::.BYTE	13.,10.			;CR.LF$		<CR><LF> string
	.BYTE	6.			;CHR.6$		CHR$(6%) constant
	.BYTE	0.			;CHR.0$		CHR$(0%) constant
	.BYTE	0.,0.			;CHR.00$	CHR$(0%)x2 constant

; define minor queue types

MNRTYP::.WORD	1.			;PRT.TYP%	print queue type
	.WORD	2.			;BAT.TYP%	batch queue type

; define major queue types

MJRTYP::.WORD	1*20			;QUE.DEF%	queue type
	.WORD	2*20			;SRV.DEF%	server type
	.WORD	3*20			;SET.DEF%	set-up type
	.WORD	4*20			;ASN.DEF%	queue assignment type

; define defaults

DFLPEN::STRING	9.,32.,<PRINT>		;DFL.PEN$	print entry-name
DFLBEN::STRING	9.,32.,<BATCH>		;DFL.BEN$	batch entry-name
DFLPTY::STRING	4.,32.,<.LST>		;DFL.PTY$	print filetype
DFLBTY::STRING	4.,32.,<.COM>		;DFL.BTY$	batch filetype
DFLLTY::STRING	4.,32.,<.LOG>		;DFL.LTY$	batch log filetype

DFLJCP::.WORD	1.			;DFL.JCP%	job_count
DFLFCP::.WORD	1.			;DFL.FCP%	file copies

DFLLNG::.WORD	66.			;DFL.LNG%	form length
DFLWID::.WORD	132.			;DFL.WID%	form width
DFLBOT::.WORD	6.			;DFL.BOT%	bottom margin
DFLJHD::.WORD	1.			;DFL.JHD%	job headers
DFLJTR::.WORD	0.			;DFL.JTR%	job trailers
DFLFHD::.WORD	1.			;DFL.FHD%	file headers
DFLFTR::.WORD	0.			;DFL.FTR%	file trailers
DFLSIM::.WORD	-1.			;DFL.SIM%	simulate

DFLPGE::.WORD	1.			;DFL.PGE%	restart page number

; define packet command codes

CMDCOD::.WORD	0.			;NP.CMD%	NOP cmd
	.WORD	1.			;BP.CMD%	BREAKPOINT cmd
	.WORD	2.			;ST.CMD%	STATUS REQUEST cmd
	.WORD	3.			;SR.CMD%	STATUS RESPONSE cmd
	.WORD	4.			;SU.CMD%	STATUS UPDATE cmd
	.WORD	5.			;AK.CMD%	ACKNOWLEDGEMENT cmd
	.WORD	6.			;NK.CMD%	NEG-ACKNOWLEDGE cmd
	.WORD	7.			;PD.CMD%	PAUSE DEVICE cmd
	.WORD	8.			;CD.CMD%	CONTINUE DEVICE cmd
	.WORD	9.			;JB.CMD%	DEFINE JOB cmd
	.WORD	10.			;MD.CMD%	MODIFY JOB cmd
	.WORD	11.			;KL.CMD%	KILL JOB cmd
	.WORD	12.			;EJ.CMD%	END-OF-JOB cmd
	.WORD	13.			;FT.CMD%	DEFINE FONT cmd
	.WORD	14.			;ON.CMD%	ON-LINE cmd
	.WORD	15.			;OC.CMD%	ON-LINE CONFIRM cmd
	.WORD	16.			;OF.CMD%	OFF-LINE cmd
	.WORD	17.			;SY.CMD%	SYNC ERROR cmd
	.WORD	18.			;ID.CMD%	INITIALIZE DEVICE cmd
	.WORD	19.			;MS.CMD%	MODIFY SERVER cmd
	.WORD	20.			;DD.CMD%	DELETE DEVICE cmd
	.WORD	21.			;IQ.CMD%	INITIALIZE QUEUE cmd
	.WORD	22.			;MQ.CMD%	MODIFY QUEUE cmd
	.WORD	23.			;DQ.CMD%	DELETE QUEUE cmd
	.WORD	24.			;PQ.CMD%	PAUSE QUEUE cmd
	.WORD	25.			;CQ.CMD%	CONTINUE QUEUE cmd
	.WORD	26.			;AS.CMD%	ASSIGN QUEUE cmd
	.WORD	27.			;DS.CMD%	DEASSIGN QUEUE cmd

; define minimum packet command lengths (includes 14. byte header)

CMDLGN::.WORD	14.			;NP.LEN%	NOP length
	.WORD	14.			;BP.LEN%	BREAKPOINT length
	.WORD	14.			;ST.LEN%	STATUS REQUEST length
	.WORD	14.			;SR.LEN%	STATUS RESPONSE length
	.WORD	30.			;SU.LEN%	STATUS UPDATE length
	.WORD	40.			;AK.LEN%	ACKNOWLEDGEMENT length
	.WORD	30.			;NK.LEN%	NEG-ACKNOWLEDGE length
	.WORD	40.			;PD.LEN%	PAUSE DEVICE length
	.WORD	44.			;CD.LEN%	CONTINUE DEVICE length
	.WORD	124.			;JB.LEN%	DEFINE JOB length
	.WORD	124.			;MD.LEN%	MODIFY JOB length
	.WORD	30.			;KL.LEN%	KILL JOB length
	.WORD	34.			;EJ.LEN%	END-OF-JOB length
	.WORD	0.			;FT.LEN%	DEFINE FONT length
	.WORD	40.			;ON.LEN%	ON-LINE length
	.WORD	30.			;OC.LEN%	ON-LINE CONFIRM length
	.WORD	30.			;OF.LEN%	OFF-LINE length
	.WORD	14.			;SY.LEN%	SYNC ERROR length
	.WORD	62.			;ID.LEN%	INITIALIZE DEVICE length
	.WORD	62.			;MS.LEN%	MODIFY SERVER length
	.WORD	40.			;DD.LEN%	DELETE DEVICE length
	.WORD	70.			;IQ.LEN%	INITIALIZE QUEUE length
	.WORD	70.			;MQ.LEN%	MODIFY QUEUE length
	.WORD	40.			;DQ.LEN%	DELETE QUEUE length
	.WORD	40.			;PQ.LEN%	PAUSE QUEUE length
	.WORD	40.			;CQ.LEN%	CONTINUE QUEUE length
	.WORD	50.			;AS.LEN%	ASSIGN QUEUE length
	.WORD	50.			;DS.LEN%	DEASSIGN QUEUE length

; define file qualifiers and defaults

FFBIN::	.WORD	1			;FF.BIN%	/[NO]BINARY
DFLBIN::.WORD	0			;DFL.BIN%	  default = /NOBINARY
FFDEL::	.WORD	4			;FF.DEL%	/[NO]DELETE
DFLDEL::.WORD	0			;DFL.DEL%	  default = /NODELETE
FFFPG::	.WORD	40			;FF.FPG%	/[NO]FLAG_PAGES
DFLFPG::.WORD	40			;DFL.FPG%	  default = /FLAG_PAGES
FFCNV::	.WORD	1000			;FF.CNV%	/[NO]CONVERT
DFLCNV::.WORD	0			;DFL.CNV%	  default = /NOCONVERT
FFTRN::	.WORD	2000			;FF.TRN%	/[NO]TRUNCATE
DFLTRN::.WORD	0			;DFL.TRN%	  default = /NOTRUNCATE
FFFEE::	.WORD	10000			;FF.FEE%	/[NO]FEED
DFLFEE::.WORD	10000			;DFL.FEE%	  default = /FEED
FFRAP::	.WORD	20000			;FF.RAP%	/[NO]WRAP	;019
DFLRAP::.WORD	20000			;DFL.RAP%	  default = /WRAP ;019
FFQLG::	.WORD	100000			;FF.QLG%	/[NO]LOG_QUEUE
DFLQLG::.WORD	100000			;DFL.QLG%	  default = /LOG_QUEUE

; define INITIALIZE/SERVER flag bits

IDFASN::.WORD	1			;IDF.ASN%	/[NO]SHAREABLE
IDFTEN::.WORD	2			;IDF.TEN%	/TENTATIVE

; define INITIALIZE/SERVER characteristics bits


IDCTOF::.WORD	1			;IDC.TOF%	/[NO]SIMULATE
IDCCTL::.WORD	2			;IDC.CTL%	/[NO]CONTROLS
IDCPUC::.WORD	4			;IDC.PUC%	/CONTROLS=UP_ARROW

IDCFTP::.WORD   10			;IDC.FTP%	/[NO]TRAILER_PAGES 

; define INITIALIZE/QUEUE flag bits

IQFDFL::.WORD	1			;IQF.DFL%	default
IQFCLS::.WORD	2			;IQF.CLS%	closed
IQFSTP::.WORD	4			;IQF.STP%	stopped
IQFMDL::.WORD	10			;IQF.MDL%	marked for deletion

; define DEASSIGN/QUEUE flag bits

DSFALL::.WORD	1			;DSF.ALL%	/ALL

; define STOP/PRINTER flag bits

PAFEJO::.WORD	1			;PAF.EJO%	/JOB_END
PAFEFI::.WORD	2			;PAF.EFI%	/FILE_END
PAFEPG::.WORD	4			;PAF.EPG%	/PAGE_END

; define STOP/QUEUE/MANAGER flag bits

OFFABO::.WORD	1			;OFF.ABO%	/ABORT

; define START/SERVER flag bits

CNFNXT::.WORD	1			;CNF.NXT%	/NEXT
CNFTFI::.WORD	2			;CNF.TFI%	/TOP_OF_FILE
CNFTJO::.WORD	4			;CNF.TJO%	/RESTART
CNFPAG::.WORD	10			;CNF.PAG%	/PAGE
CNFFWD::.WORD	20			;CNF.FWD%	/FORWARDSPACE
CNFBWD::.WORD	40			;CNF.BWD%	/BACKSPACE

; define job flag bits

       ;.WORD	1			;		reserved	;022
JBFHLD::.WORD	2			;JBF.HLD%	HOLD job
JBFREL::.WORD	4			;JBF.REL%	RELEASE job
       ;.WORD	10			;		reserved	;022
JBFNTF::.WORD	20			;JBF.NTF%	NOTIFY flag	;022

; define job status values

JSFRM::	.WORD	0.			;JS.FRM%	forms wait (FORMS) ;020
JSNRD::	.WORD	1.			;JS.NRD%	not ready (HOLD)
JSAFT::	.WORD	2.			;JS.AFT%	after (AFTER)
JSRDY::	.WORD	3.			;JS.RDY%	ready (READY)
JSSTR::	.WORD	4.			;JS.STR%	started (STARTED)
JSABT::	.WORD	5.			;JS.ABT%	aborting (ABORTING)
JSSUC::	.WORD	6.			;JS.SUC%	success (ENDED)
JSFAI::	.WORD	7.			;JS.FAI%	failure (FAILED)
JSKIL::	.WORD	8.			;JS.KIL%	killed (DELETED)
JSABO::	.WORD	9.			;JS.ABO%	aborted (ABORTED)

; define RSTS error codes

	.WORD	2.			;ERR.BADNAM%	?Illegal name
	.WORD	4.			;ERR.NOROOM%	?No room for user
	.WORD	5.			;ERR.NOSUCH%	?Can't find file
	.WORD	10.			;ERR.PRVIOL%	?Protection violation
	.WORD	11.			;ERR.EOF%	?End of file
	.WORD	14.			;ERR.DEVHNG%	?Device hung
	.WORD	16.			;ERR.FIEXST%	?File exists
	.WORD	32.			;ERR.NOBUFS%	?No buffers
	.WORD	69.			;ERR.QUOTA%	?Quota exceeded
	.WORD	154.			;ERR.BKTLCK%	?RMS bucket locked
	.WORD	155.			;ERR.NOTFND%	?Record not found

; define RMS error codes

	.WORD	-1472.			;RMS.RNF%	record not found
	.WORD	-1296.			;RMS.PRV%	priv'd queue
	.WORD	-1248.			;RMS.PLG%	page limit > max limit
	.WORD	-1024.			;RMS.LBY%	server busy
	.WORD	-912.			;RMS.ISI%	cpu limit > max limit
	.WORD	-896.			;RMS.IRC%	time limit > max limit
	.WORD	-880.			;RMS.IOP%	prioity > max priority
	.WORD	-784.			;RMS.FUL%	no room
	.WORD	-736.			;RMS.FNF%	file not found
	.WORD	-672.			;RMS.FEX%	already exists
	.WORD	-512.			;RMS.DNR%	dev not ready
	.WORD	-232.			;RMS.BOF%	logfile queue closed
	.WORD	-208.			;RMS.BKZ%	no default logfile queue
	.WORD	-192.			;RMS.BKS%	logfile queue not found

; define server status bits

	.WORD	1.			;SPS.ONL%	online to QMAN
	.WORD	2.			;SPS.NRD%	not ready
	.WORD	4.			;SPS.PDV%	paused
	.WORD	8.			;SPS.OFL%	sent off-line
	.WORD	16.			;SPS.ALC%	device allocated
	.WORD	32.			;SPS.HNG%	hung
	.WORD	64.			;SPS.JOB%	started
	.WORD	128.			;SPS.SYN%	sync error detected
	.WORD	256.			;SPS.NIU%	not in use
	.WORD	512.			;SPS.MDL%	marked for deletion
	.WORD	1024.			;SPS.SPN%	waiting for spawn
	.WORD	2048.			;SPS.RES%	waiting for resource
	.WORD	4096.			;SPS.CAR%	server lost carrier
	.WORD	8192.			;SPS.TEN%	tentative
	.WORD	16384.			;SPS.DIS%	disabled

; define sender parameters for RCVPKT

RCVJOB::.BYTE	0			;RCV.JOB$	sender's job no.
	.BYTE	0			;		reserved
RCVPPN::.WORD	0			;RCV.PPN%	sender's PPN
RCVLEN::.WORD	0			;RCV.LEN%	no. bytes sent
RCVREM::.WORD	0			;RCV.REM%	no. bytes not sent

; allocate SYS call work array

	.BLKW	31.			;FIRQB%(30)	SYS call work array

.END
