;
;	PBSMGV.CMD
;
;	COPYRIGHT (c) 1982, 1984
;	DIGITAL EQUIPMENT CORP., MAYNARD, MASS.
;
;	TKB command file to build PBSMGV.TSK V9.0
;
;	Build using:
;
;		CUSP resident library CSP100
;		RMS disk (overlaid) library
;
SYSTEM:PBSMGV,LST:PBSMGV/MA/CR/-SP,SYSTEM:PBSMGV=SYSTEM:PBSMGV/MP
TASK=PBSMGR
UNITS=12
ASG=SY:5:6:7:8:9:10:11:12
RESLIB=LB:CSP100/RO
EXTTSK=1024
//
