$JOB/CCL/NOLIMIT/PRI:-16 [170,30]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$ASSIGN <40>
$SWITCH RT11
$SIZE 16
$R SY:LINK
DEFALT.XXX/Z,LSD:DEFALT/A/W,SY:DEFALT=DEFALT/X/B:#1000
$R SY:PIP
DEFALT.SAV/DE:NOWARN/NOLOG
*.SAV=DEFALT.XXX/RE/NOLOG
DEFALT.OBJ/DE/NOLOG
$SIZE 16
$R SY:LINK
ODT.XXX/Z,LSD:ODT/A/W,SY:ODT=ODT/X/B:#140000
$R SY:PIP
ODT.SAV/DE:NOWARN/NOLOG
*.SAV=ODT.XXX/RE/NOLOG
$R SY:SILUS
ODT.SYS,_TT:=ODT
$EOD
$R SY:PIP
ODT.SAV/DE:NOWARN/NOLOG
$EOJ
