$JOB/CCL/NOLIMIT/PRIORITY:-16 [170,45]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: DK
$ASSIGN D: SY
$ASSIGN <40>
$SWITCH RT11
$SIZE 28
$R SY:LINK
SYSGEN.SV/Z,SYSGEN/A/W,SYSGEN=SYSGEN/X/C
SGNSRT/O:1/C
SGNTTY/O:1/C
SGNDSK/O:1/C
SGNPRF/O:1/C
SGNOPT/O:1/C
SGNBAT/O:1/C
SGNANS/O:2/C
SGNDIR/O:2
$R SY:SILUS
SYSGEN.SAV/S,SYSGEN=SYSGEN.SV/N
SYSGEN
$EOD
$R SY:PIP
SYSGEN.SV,SYSGEN.STB/DE/NOLOG
$EOJ
