TITLE	ACTKEY,<ACTMGR CUI KEYWORDS>,0A,10-MAY-91,WJS/JJT

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	ACTKEY Edit History
;+
;
;-


.sbttl	Set up MACRO parameters

;	.enabl	lc
	.list	bex
	.list	me
	.list	meb



.sbttl	Define and order the CSECT's


	DEFORG	DUMMY,psect	reloc=ABS
	DEFORG	ACTKEY,psect	space=D

.sbttl	Include CUI macros

	.mcall	$CUI
	$CUI	table			; Define CUI tables


;  Note:  the following macros assume they are being invoked in
;           the ACTKEY psect, and leave the current psect
;           set to ACTKEY upon exit

.sbttl	Define "keydef" macro

; Assign even values to command/qualifier keys

.macro	keydef	Key,Keynam
	.nlist
	defkey	Key,<Keynam>
	.psect	ACTKEY
	.word	Key
	.list
.endm	keydef


.sbttl	Define "tagdef" macro

; Assign odd values to parameter tags

.macro	tagdef	Tag
	.nlist
	.psect	DUMMY
			.iif ndf Tagorg	Tagorg:
			.iif eq .-Tagorg	.blkb	1
Tag::	.blkb	2
	.psect	ACTKEY
	.word	Tag
	.list
.endm	tagdef




;.GO	Starting point for KEYKEY.TEC
;		(which prepares ACTKEY.B2S from ACTKEY.MAC)

.sbttl	Commands

	 keydef	 CR.A.k	 <"CR-EATE/AC-COUNT">

	keydef	SEA.k	<"SE-T AC-COUNT">
	keydef	SEP.k	<"SE-T PA-SSWORD">

	keydef	SHA.k	<"SH-OW AC-COUNTS">

	 keydef	 DE.A.k	 <"DE-LETE/AC-COUNT">

.sbttl	Command qualifiers

	keydef	ACC.q	"AC-COUNTING_DATA"
	keydef	ALL.q	"AL-L"
	keydef	BRI.q	"BR-IEF"
	keydef	CLU.q	"CL-USTER_SIZE"
	keydef	DEB.q	"DEB-UG"
	keydef	DIA.q	"";"DIA-LOGUE"
	keydef	EXP.q	"EX-PIRED"
	keydef	FIR.q	"FI-RST"
	keydef	FUL.q	"FU-LL"
	keydef	INQ.q	"IN_Q-UOTA"
	keydef	LAS.q	"LA-ST"
	keydef	FOR.q	"FO-RM"
	keydef	LIN.q	"INT-ERACTIVE"
	keydef	LOG.q	"LOG"
	keydef	LOO.q	"LOO-KUP"
	keydef	NAM.q	"NA-ME"
	keydef	NET.q	"NE-TWORK"
	keydef	NOE.q	"NOEX-PIRE"
	keydef	PPT.q	"PA-SSWORD_PROMPT"
	keydef	OUQ.q	"OU-T_QUOTA"
	keydef	OUT.q	"OU-TPUT"
	keydef	POS.q	"PO-SITION"
	keydef	PRV.q	"PR-IVILEGES"
	keydef	PUR.q	"PU-RGE"
	KEYDEF	NPR.Q	"NOPU-RGE"
	keydef	REM.q	"DI-ALUP"
	keydef	RSV.q	"";"RESER-VE_QUOTA"
	keydef	QER.q	"QU-ERY"
	keydef	SIZ.q	"SI-ZE"
	keydef	SYS.q	"SY-STEM"
	keydef	TEM.q	"TE-MPLATE"
	KEYDEF	CAP.Q	"CA-PTIVE"
	KEYDEF	DET.Q	"DET-ACHED_JOB_QUOTA"
	KEYDEF	JOB.Q	"JO-B_QUOTA"
	KEYDEF	MES.Q	"ME-SSAGE_QUOTA"
	KEYDEF	RIB.Q	"RI-B_QUOTA"
	KEYDEF	NOU.Q	"NOU-SER"
	KEYDEF	USE.Q	"US-ER"
	KEYDEF	RES.Q	"RE-SET"
	KEYDEF	NRS.Q	"NORE-SET"

.sbttl	Command qualifier keywords

	keydef	INDE.k	"IN-DEX"
	keydef	MIDD.k	"MID-DLE"
	keydef	NONE.k	"NONE"
	keydef	UNLI.k	"UN-LIMITED"
	KEYDEF	QER.K	"QU-ERY"

.sbttl	Parameter tags

	tagdef	CLU.t		; Clustersize
	tagdef	DVP.t		; Device PPN specification
	tagdef	EXP.t		; Expiration date
	tagdef	FIR.t		; Beginning PPN for wildcards
	tagdef	INQ.t		; Logged-in quota
	tagdef	LAS.t		; Ending PPN for wildcards
	tagdef	NAM.t		; Account name
	tagdef	OUT.t		; Output file specification
	tagdef	OUQ.t		; Logged-out quota
	tagdef	POS.t		; UFD requested position
	tagdef	PRV.t		; Privileges
	tagdef	SIZ.t		; UFD requested extent
	tagdef	TEM.t		; Template device/PPN specification

.sbttl	Classes

	TAGDEF	ACC.C		; Class of account qualifiers

	.end
