.INCLUDE	/CMN:COMMON.MAC/
.LIBRARY	/CUI:CUIMAC.MLB/
.LIBRARY	/DCL:DCLMAC.MLB/
.NLIST
.INCLUDE	/DCL:DCLPFX.MAC/
.LIST
TITLE	DCLDSP,<DCL Program Dispatch>,0A,10-MAY-91,GMB/BGN/BTB

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	EDIT HISTORY FOR DCLDSP
;+
;  001	GMB  28-May-85	Created this file from thin air.
;  002  BGN  25-Aug-87  Add SHOW QUOTA command
;  003  BGN  22-Sep-87  Dispatch BASIC command to DCLAUX
;  004  BGN  24-SEP-88  Add support for LAT
;
;			[RSTS V10.0]
;  005  BTB  05-Nov-89	Move MOUNT, DISMOUNT, and INITIALIZE to DCLAUX
;  006	BTB  10-Nov-89	Add OMS support
;  007	BTB  31-May-90	Combine AUX commands into one AUX.CMD entry point
;			Moved BASIC back to DCL, Added CC.CMD
;  008	JFM  18-Jun-90	Fix BASIC/BPLUS - add $DEFCMD, $THR.  Move $ENDCMD up
;-

	.PSECT	DCLDSP,RO,REL,CON
	DEFORG	DCLDSP

	$CUI	TABLE			;Include macros for CUI tables

	.MCALL	PUTCCL,PUTSTR						;007

.SBTTL	Define macro $DOCCL

	.MACRO	$DOCCL	PROG
	 .WORD	$DOCCL,PROG
	 .GLOBL	PROG
	.ENDM

.ENABL	LSB

.SBTTL	$DOCCL	- Set up CCL entry to command handler

$DOCCL::CALLX	PUTCCL			; Set up command handler as a CCL
	CALLX	PUTLINE			; Put command line into TRNBUF
	CLR	R0			; Set CUI error code to success
	CALLRX	U$ENDTHR		; End the CUI dialogue and return
					; ... to HEART

.DSABL	LSB

.SBTTL	Dispatch to command handlers

ACT.CMD::				; Account management commands
	$DOCCL	...ACT			; These commands are done by ACTMGR

AUX.CMD::				; AUX commands			;007
	$DOCCL	...AUX			; These commands are done by DCLAUX

BAS.CMD::				; BASIC/BP2 command		;007
	$DOCCL	...BP2			;  Go to BASIC+2		;007

BPL.CMD::$THR
	$DEFCMD				; BASIC/BPLUS command		;008
	$ENDCMD				; No parameters			;008
	PUTCCL	...UTL			; Tell UTLMGR to		;007
	PUTSTR	"SET"<SPACE>"JOB/KEYB=BASIC" ; switch to BASIC-PLUS	;007
	$ENDTHR				;				;007

BCK.CMD::				; BACKUP and RESTORE commands
	$DOCCL	...BCK			; These commands are done by BACKUP

CC.CMD::				; CC command			;007
	$DOCCL	...CC			; Done by the PDP-11 C compiler	;007

LAT.CMD::                               ; LAT utility commands		;004
       	$DOCCL	...LAT			; These commands are done by LATMGR;004

OMS.CMD::				; Operator Management Services	;006
	$DOCCL	...OMS			; These commands are done by OMS ;006

QUO.CMD::				; SHOW QUOTAS COMMAND		;002
	$DOCCL	...QUO			; These commands are done by QUOLST;002

SPL.CMD::				; PRINT and SUBMIT commands
	$DOCCL	...QUE			; These commands are done by SPLMGR

TER.CMD::				; SHOW/SET TERMINAL commands
	$DOCCL	...TER			; These commands are done by TERMGR

UTL.CMD::				; Utility commands
	$DOCCL	...UTL			; These commands are done by UTLMGR

	.END
