.INCLUDE	/CMN:COMMON.MAC/
.LIBRARY	/CUI:CUIMAC.MLB/
.LIBRARY	/DCL:DCLMAC.MLB/
.NLIST
.INCLUDE	/DCL:DCLPFX.MAC/
.LIST
TITLE	DCLFIL,<Filespecs for DCL Utilities>,0A,10-MAY-91,CEK/JFM/GMB/BGN/BTK/BTB/DLS

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	EDIT HISTORY FOR DCLFIL
;+
;
;  001	CEK  16-APR-82	Added edit history
;  002	CEK  16-APR-82	Removed file name from descriptor for DCL's friend
;  003	CEK  30-APR-82	Changed ORG statements
;  004	JFM  25-SEP-82	Added ..DISO and ..MNTO, the ONLCLN program
;  005	JFM  05-OCT-82	Removed ...F4P, Fortran-IV Plus. 
;  006	JFM  05-Feb-83	Made TTYSET point to 30500 not 30000.
;  007	JFM  21-Feb-83	...HEL will point to DCLA.HLP if you install DCLA
;			on your system.  But the RTS will still be called DCL. 
;  008	JFM  29-Mar-83	Removed ...DIS and ...MNT, UMOUNT facility codes.
;  009	JFM  29-Mar-83	Changed "..DISO" and "..MNTO" to "...DIS" and "...MNT"
;  010	JFM  29-Mar-83	Added conditional code to TITLE statement for RSTSA
;  011	JFM  14-Apr-83	Changed DEFCCL MACRO to support logical names, modified
;			all DEFCCLs and File Descriptor Block for this change.
;  012	JFM  18-Apr-83	Added ..SRMG, for SORT and MERGE commands
;  013	JFM  11-Aug-83	Changed ..SRMG into ...SRT and ...MGE
;  014	JFM  23-Sep-83	Removed ...DCL, changed ...HEL
;  015	JFM  23-Nov-83	Changed ...SET (TTYSET) to ...TER (TERMGR)
;  016	JFM  10-Jan-84	Changed ...DIS and ...MNT from .SAV's to .TSK's
;  017	JFM  10-Feb-84	Changed ...DIS and ...MNT from .TSK's to *'s
;  018	JFM  10-Mar-84	Added UTLMGR and BARF and ACTMGR tasks
;  019	JFM  08-May-84	Removed RSTSA references
;  020	JFM  11-Jul-84	Changed ...DIS and ...MNT to ...ONC (ONLCLN)
;  021	JFM  30-Jul-84	Removed SETPAS
;  022	JFM  07-Aug-84	Gave ACTMGR privs
;  023	JFM  09-Aug-84	Changed FLLOG to 10 bytes and colons now required on
;			logical names
;  024	JFM  28-Aug-84	Took PRIVs away from BACKUP, PBSMGR has 127 linelength
;  025  GMB  05-Nov-84	Made PIP entry point = 30500, PIP line length = 511
;  026	JFM  30-Jan-85	Got rid of reference to SWITCH program
;  027  GMB  23-May-85	Changed some of the DEFFILs to point to DCLAUX
;  028  GMB  28-May-85	Added ...AUX for all commands which are done in DCLAUX
;  029  GMB  02-Sep-86	Set 'watch'able bit for DCLAUX
;  030  GMB  23-Jan-87	Changed line length of PBSMGR from 127 to 255
;  031  BGN  25-Aug-87  Add QUOLST as ...QUO
;  032  BGN  24-Feb-88	Add LATMGR as ...LAT
;  033	REG  16-Sep-88	Change QUOLST line number to 30500
;  034	BTK  20-Dec-88	Removed ...RTS
;
;			[RSTS V10.0]
;  035  BTB  05-Nov-89	Removed DCLDVS-oriented files
;  036	BTB  10-Nov-89	Add OMS as ...OMSMGR
;  037	BTB  31-May-90	Add C compiler as ...CC, added BASIC as ...BP2
;  038  DLS  10-Aug-90	Gave Privs back to BACKUP
;-

	.MCALL	.ASCIC
	.PSECT	DCLFIL,RO,REL,CON
	DEFORG	DCLFIL

.SBTTL	DEFFIL Macro

; First, verify assumptions about the layout of file descriptor block.
; This layout is also defined in DCLPFX so if it is different here you will
; get phase errors. //Should use .assume//

	.DSECT
FLLOG:	.BLKB	10.		;Logical device: 10 ascii bytes (9 for logical
				;  and name, one for ":")
FLNAM1:	.BLKW	2		;Filename: 2 words of RAD50.
FLEXT:	.BLKW			;Extension of CUSP, or -1 for default
				;handling of extensions.
FLNENT:	.BLKW			;Entry parameter.  Sign bit set if 
				;privilege is to be retained.
FLCLEN:	.BLKW			;Maximum length of command line accepted by
				;CUSP.  Size of core common (127) in most 
				;cases, but 80 for some CUSPs.
FLCKEY:				;Command keyword accepted by CUSP, as ASCIZ 
				;string.
	UNORG

.MACRO	DEFCCL	LOG=$:,FILE,EXT,LINENO=0,PRIVIL,LINELEN=127
	.NCHR	$$$NUM, <LOG>
	.ASSUME	$$$NUM LE 9.
	.ASSUME	$$$NUM GT 0
	.ASCII	/LOG/
	.REPT	10.-$$$NUM
	.BYTE	0
	.ENDR
	.NCHR	$$$NUM, <FILE>
	.ASSUME	$$$NUM GT 0
	.IF	LE $$$NUM-3.
	 .RAD50	/FILE/
	 .WORD	0
	.IFF
	.ASSUME	$$$NUM LE 6.
	 .RAD50	/FILE/
	.ENDC
	.IF	IDN <EXT>,<*>
	 .WORD	-1.
	.IFF
	.NCHR	$$$NUM, <EXT>
	.IIF	GT $$$NUM-3	.ERROR	;Illegal extension.
	.IIF	EQ $$$NUM-0	.ERROR	;Illegal extension.
	 .RAD50	/EXT/
	.ENDC
	.IF	IDN	<PRIVIL>,<PRIV>
	 .WORD	^O100000 ! LINENO'.
	.IFF
	 .WORD	LINENO'.
	.ENDC
	 .WORD	LINELEN'.
	.ENDM

...ACT::DEFCCL	,ACTMGR,TSK		30500	PRIV	LINELEN=255
	.ASCIZ	""
	.EVEN
...ATT::DEFCCL	,LOGIN,*		30000	PRIV	
	.ASCIZ	"ATTACH"
	.EVEN
...AUX::DEFCCL	,DCLAUX,TSK		30501	PRIV	LINELEN=255
	.ASCIZ	""
	.EVEN
...BCK::DEFCCL	<[0,1]>,BACKUP,TSK	30500	PRIV	LINELEN=255	;038
	.ASCIZ	""
	.EVEN
...BP2::DEFCCL	,BP2IC2,TSK		30000	PRIV	LINELEN=127	;037
	.ASCIZ	""							;037
	.EVEN								;037
...BYE::DEFCCL	,LOGOUT,*		0	PRIV
	.ASCIZ	"BYE"
	.EVEN
...CC::	DEFCCL	CC$:,PDP11C,TSK		30000	NOPRIV	LINELEN=255	;037
	.ASCIZ	"CC"							;037
	.EVEN								;037
...EDT::DEFCCL	EDT$:,EDT,TSK	     	30000	NOPRIV
	.ASCIZ	"EDT"
	.EVEN
...FIL::DEFCCL	,FILCOM,*	     	30000	NOPRIV
	.ASCIZ	"FILCOM"
	.EVEN
...HEL::DEFCCL HELP$:,HELP,*		31500	PRIV 
	.ASCIZ	"HELP"
	.EVEN
...LAT::DEFCCL	,LATMGR,TSK		30500	PRIV	LINELEN=255	;032
	.ASCIZ	""                                                      ;032
	.EVEN                                                           ;032
...NET::DEFCCL	DECNET$:,NET,TSK	30000	PRIV 
	.ASCIZ	"NET"
	.EVEN
...NFT::DEFCCL	DECNET$:,NFT,TSK	30000	PRIV 
	.ASCIZ	"NFT"
	.EVEN
...NCP::DEFCCL	DECNET$:,NCP,TSK	30000	PRIV 
	.ASCIZ	"NCP"
	.EVEN
...OMS::DEFCCL	OMS$:,OMSMGR,TSK	30500	PRIV	LINELEN=255
	.ASCIZ	""
	.EVEN
...PIP::DEFCCL	,PIP,SAV		8192	PRIV	LINELEN=127
	.ASCIZ	"PIP"
	.EVEN
...QUE::DEFCCL	PBS$:,PBSMGR,TSK	30500	PRIV	LINELEN=255
	.ASCIZ	""
	.EVEN
...QUO::DEFCCL	AUXLIB$:,QUOLST,*	30500	PRIV			;033
	.ASCIZ	""							;031
	.EVEN								;031
...SYS::DEFCCL	,SYSTAT,*		30000	PRIV 
	.ASCIZ	"SYSTAT"
	.EVEN
...TEC::DEFCCL	TECO$:,TECO,TEC		0	NOPRIV
	.ASCIZ	<'D+40><'C+40><'L+40><SPACE><SPACE><'T+40><'E+40><'C+40><'O+40>
	.EVEN				;EDIT/TECO passes the string
					;"dcl  teco etc" in core common.
...TER::DEFCCL	,TERMGR,*		30500	PRIV	LINELEN=255 
	.ASCIZ	""
	.EVEN
...UTL::DEFCCL	,UTLMGR,TSK		30500	PRIV	LINELEN=255
	.ASCIZ	""
	.EVEN

.END
