.INCLUDE	/CMN:COMMON.MAC/
.LIBRARY	/CUI:CUIMAC.MLB/
.LIBRARY	/DCL:DCLMAC.MLB/
.NLIST
.INCLUDE	/DCL:DCLPFX.MAC/
.LIST
TITLE	DCLVEC,<DCL Pseudo-Vector>,0A,10-MAY-91,CEK/JFM/GMB

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	EDIT HISTORY FOR DCLVEC
;+
;
;  001	CEK  16-APR-82	Added edit history
;  002	CEK  30-APR-82	Changed ORG statements
;  003	JFM  23-SEP-83  Added note for JOB.SIZ equate. Should not be hard coded
;  004  JFM  29-NOV-83  Removed P..CRAS and P..STRT entry points 
;  005	JFM  08-MAY-84	Made default runable extension .COM
;  006  GMB  05-Jan-86  Changed JOB.SIZ to 3K
;			Added MAX.SIZ
;
;-

;+
; DCLVEC.MAC - DCL Pseudo-vector
;
; This OBJ file must be the last one in the link sequence,
; so that DCLVEC ends up at the end, and so that the symbol IMPEND
; really gets put at the end of the IMPURE PSECT.
;-


	.PSECT	DCLVEC,RO,REL,CON
	DEFORG	DCLVEC

.SBTTL	Constants

.EQUATE	JOB.SIZ,4	;Size of user job, in K words.
			;??  NOTE: Should change this to figure out the size of
			;IMPURE, rounded up to the next 4000 word boundary,
			;then divide by 4 to figure JOB.SIZ.  How's that sound?
.EQUATE MAX.SIZ,8.	;Maximum size of user job in K words.

; Global constants for RTSODT.

O.ISIZ	==	JOB.SIZ		;Initial job size. (Historical.)
O.MSIZ	==	JOB.SIZ		;Minimum job size.
O.SIZE	==	MAX.SIZ		;Maximim job size.
O.DEXT	==	^RCOM.		;Runnable extension is .COM.
O.FLAG	==	PF.KBM
;+
; The default bit values for P.FLAG are:
;	PF.CSZ	=	0	Monitor preallocates space for job based 
;				on PF.MSIZ when we get a .RUN.
;	PF.REM	=	0	Monitor doesn't remove RTS from memory
;				until someone else needs the space.
;	PF.NER	=	0	Monitor logs errors occurring within the
;				RTS.
;	PF.RW	=	0	The RTS is read-only.
;	PF.1US	=	0	The RTS is multi-user.
;	PF.KBM	=	1	The RTS is a KBM.
;-



	.WORD	O.FLAG		;P.FLAG--RTS flag word.
	.WORD	O.DEXT		;P.DEXT--No default extension for .RUN
	.WORD	O.ISIZ		;P.ISIZ--Initial job size (historical)
	.WORD	O.MSIZ		;P.MSIZ--Minimum job size 
	.WORD	P..FIS		;P.FIS--Trap address for FIS hardware floating
				;point option.
	.WORD			;P.CRAS--Crash entry point.  (Shouldn't be
				;used.)
	.WORD			;P.STRT--Start entry point.  (Shouldn't be
				;used.)
	.WORD	P..NEW		;P.NEW--Entry point for new user.
	.WORD	P..RUN		;P.RUN--Entry point for .RUN.
	.WORD	P..BAD		;P.BAD--Trap address for various bad errors.
	.WORD	P..BPT		;P.BPT--Trap address for BPT instruction and 
				;T bit. (Shouldn't be used.)
	.WORD	P..IOT		;P.IOT--Trap address for IOT instruction.
				;(Shouldn't be used.)
	.WORD	P..EMT		;P.EMT--Trap address for non-monitor EMTs.
				;(Shouldn't be used.)
	.WORD	P..TRAP		;P.TRAP--Trap address for TRAPs.
				;(Shouldn't be used.)
	.WORD	P..FPP		;P.FPP--Trap address for FPP or FPU floating 
				;point errors. (Shouldn't be used.)
	.WORD	P..CC		;P.CC--Trap address for one CTRL/C.
	.WORD	P..2CC		;P.2CC--Trap address for two CTRL/Cs.
	.WORD	O.SIZE		;P.SIZE--Maximum job size 

GLOBAL	<P..NEW,P..RUN,P..FIS,P..BAD>
GLOBAL	<P..BPT,P..IOT,P..EMT,P..TRAP,P..FPP,P..CC,P..2CC>
.END
