$JOB/CCL/NOLIMIT/PRIORITY:-16 [170,44]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$ASSIGN <40>
$SWITCH RT11
$R SY:PIP
*.BAK/DE:NOWARN/NOLOG
$SIZE 28
$R SY:MACRO
OVRLRG,LSD:OVRLRG/C=OVRLRG
$R SY:MACRO
OV2,LSD:OV2/C=OV2
$SIZE 28
$R SY:MACRO
EXTLRG,LSD:EXTLRG/C=#COMMON,#KERNEL,#FLDEF,EXTLRG
$SIZE 28
$R SY:MACRO
OPNLRG,LSD:OPNLRG/C=OPNLRG
$SIZE 28
$R SY:MACRO
ASS,LSD:ASS/C=ASS
$SIZE 28
$R SY:MACRO
SND,LSD:SND/C=#COMMON,#KERNEL,#FLDEF,#EMLDEF,#NETDEF.SML/M,SND
$SIZE 28
$R SY:MACRO
DIR,LSD:DIR/C=#COMMON,#KERNEL,#FLDEF,DIR
$SIZE 28
$R SY:MACRO
RAD,LSD:RAD/C=#COMMON,#KERNEL,#FLDEF,RAD
$SIZE 28
$R SY:MACRO
ZER,LSD:ZER/C=#COMMON,#KERNEL,#FLDEF,ZER
$SIZE 28
$R SY:MACRO
PAS,LSD:PAS/C=#COMMON,#KERNEL,#FLDEF,PAS
$SIZE 28
$R SY:MACRO
MNT,LSD:MNT/C=#COMMON,#KERNEL,#FLDEF,MNT
$SIZE 28
$R SY:MACRO
UUO,LSD:UUO/C=UUO
$SIZE 28
$R SY:MACRO
SPL,LSD:SPL/C=#COMMON,#KERNEL,#FLDEF,#NETDEF.SML/M,SPL
$SIZE 28
$R SY:MACRO
LIN,LSD:LIN/C=#COMMON,#KERNEL,#FLDEF,LIN
$SIZE 28
$R SY:MACRO
RTS,LSD:RTS/C=#COMMON,#KERNEL,#FLDEF,RTS
$SIZE 28
$R SY:MACRO
TRM,LSD:TRM/C=TRM
$SIZE 28
$R SY:MACRO
TRU,LSD:TRU/C=TRU
$SIZE 28
$R SY:MACRO
DLN,LSD:DLN/C=#COMMON,#KERNEL,#FLDEF,DLN
$SIZE 28
$R SY:MACRO
DTU,LSD:DTU/C=#COMMON,#KERNEL,#FLDEF,#DTDEF,DTU
$SIZE 28
$R SY:MACRO
MTU,LSD:MTU/C=#COMMON,#KERNEL,#FLDEF,#MTDEF,MTU
$SIZE 28
$R SY:MACRO
MTA,LSD:MTA/C=#COMMON,#KERNEL,#FLDEF,#MTDEF,MTA
$SIZE 28
$R SY:MACRO
SLN,LSD:SLN/C=#COMMON,#KERNEL,#FLDEF,SLN
$SIZE 28
$R SY:MACRO
FIL,LSD:FIL/C=#COMMON,#KERNEL,#FLDEF,FIL
$SIZE 28
$R SY:MACRO
CHE,LSD:CHE/C=#COMMON,#KERNEL,#FLDEF,CHE
$SIZE 28
$R SY:MACRO
SNP,LSD:SNP/C=#COMMON,#KERNEL,#FLDEF,SNP
$SIZE 28
$R SY:MACRO
KMC,LSD:KMC/C=KMC
$SIZE 28
$R SY:MACRO
PAT,LSD:PAT/C=#COMMON,#KERNEL,#FLDEF,PAT
$SIZE 28
$R SY:MACRO
LOD,LSD:LOD/C=#COMMON,#KERNEL,#FLDEF,LOD
$SIZE 28
$R SY:MACRO
FUT,LSD:FUT/C=#COMMON,#KERNEL,#FLDEF,FUT
$SIZE 28
$R SY:MACRO
LOG,LSD:LOG/C=LOG
$SIZE 28
$R SY:MACRO
UTL,LSD:UTL/C=UTL
$SIZE 28
$R SY:MACRO
SLI,LSD:SLI/C=SLI
$SIZE 28
$R SY:MACRO
HSH,LSD:HSH/C=#COMMON,#KERNEL,#FLDEF,HSH
$SIZE 28
$R SY:MACRO
PRV,LSD:PRV/C=#COMMON,#KERNEL,#FLDEF,PRV
$SIZE 28
$R SY:MACRO
PFB,LSD:PFB/C=PFB
$SIZE 28
$R SY:MACRO
OPN,LSD:OPN/C=#COMMON,#KERNEL,#FLDEF,OPN
$SIZE 28
$R SY:MACRO
CFG,LSD:CFG/C=CFG
$SIZE 28
$R SY:MACRO
CF1,LSD:CF1/C=CF1
$SIZE 28
$R SY:MACRO
LTU,LSD:LTU/C=LTU
$SIZE 28
$EOJ
