; LBRASM.CMD
;
; MAC COMMAND FILE TO ASSEMBLE LIBRARIAN (LBR.TSK) MODULES
;
SYSTEM:LBR   ,LST:LBR   /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBR
SYSTEM:LBRCD ,LST:LBRCD /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRCD
SYSTEM:LBRCM ,LST:LBRCM /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRCM
SYSTEM:LBRCR ,LST:LBRCR /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRCR
SYSTEM:LBRCRD,LST:LBRCRD/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRCRD
;SYSTEM:LBRCRF,LST:LBRCRF/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRCRF
SYSTEM:LBRDF ,LST:LBRDF /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRDF
SYSTEM:LBRDL ,LST:LBRDL /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRDL
SYSTEM:LBRDLM,LST:LBRDLM/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRDLM
SYSTEM:LBRER ,LST:LBRER /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRER
SYSTEM:LBRERF,LST:LBRERF/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRERF
SYSTEM:LBRERO,LST:LBRERO/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRERO
SYSTEM:LBREX ,LST:LBREX /CR/-SP=RSX:COMMON,LBR:RSTPRE,LBRPRF,LBREX
SYSTEM:LBRFI ,LST:LBRFI /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRFI
SYSTEM:LBRFLA,LST:LBRFLA/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRFLA
SYSTEM:LBRIN ,LST:LBRIN /CR/-SP=RSX:COMMON,LBR:RSTPRE,LBRPRF,LBRIN
SYSTEM:LBRINI,LST:LBRINI/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRINI
SYSTEM:LBRLCD,LST:LBRLCD/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRLCD
SYSTEM:LBRLI ,LST:LBRLI /CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRLI
SYSTEM:LBRMMH,LST:LBRMMH/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRMMH
SYSTEM:LBRNXT,LST:LBRNXT/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRNXT
SYSTEM:LBROUT,LST:LBROUT/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBROUT
SYSTEM:LBRPUT,LST:LBRPUT/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRPUT
SYSTEM:LBRRHD,LST:LBRRHD/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRRHD
SYSTEM:LBRRLH,LST:LBRRLH/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRRLH
SYSTEM:LBRRMH,LST:LBRRMH/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRRMH
SYSTEM:LBRTBL,LST:LBRTBL/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRTBL
SYSTEM:LBRWHD,LST:LBRWHD/CR/-SP=RSX:COMMON,LBR:LBRPRF,LBRWHD
;
