;
; TKB BUILD FILE FOR LBR
; FOR RSTS/E V9.0
; USING SYSLIB
; CREATED BY SGNBLDBLD.CMD VERSION 1.62
;
SYSTEM:LBR/-FP/CP/MM,SYSTEM:LBR/MA/CR/-SP,SYSTEM:LBR=LBR:LBRBLD/MP
TASK=...LBR
STACK=128
UNITS=8
ASG=TI:1:2,OV:7
ASG=TI:8		;LUN FOR ERROR MESSAGES
EXTTSK=7600		;Extra dynamic memory
GBLDEF=N$MPAG:24	;FAST-PAGE SEARCH PARAMETER
GBLDEF=W$KLUN:7		;WORK FILE LUN
GBLDEF=W$KEXT:-24	;WORK FILE EXTENSION PARAMETER
GBLDEF=$CDDMG:1		;NO DOUBLE PRECISION DECIMAL CONVERSION
GBLDEF=..RWLG:1		;NO READ/WRITE VIRTUAL LONG
@LBR:LBRGBL.CMD
//
