;	THIS FILE IS CALLED BY LBR:LBRBLD.CMD
;	FOR REFERENCES FOR RSTS
;
;
;
EXTSCT=.99998:1000	; ALLOCATE PATCH SPACE IN ROOT
;
; GLOBAL REFERENCES TO ROOT AND OVERLAY SEGMENTS
;
;	GLOBAL REFERENCES FROM LBR.OLB
;
GBLREF=$VRSN,$LBR,$RSTRT,$QUIT,$CLEAR,$OPEN	; Module:LBR
GBLREF=$NWLNK,$CMIPT,$FRHD			;
GBLREF=L$BUF,L$TYP,L$ID,L$VER,L$DAT,L$ES,L$ET	; Module:LBRDF
GBLREF=L$EI,L$EA,L$MS,L$MT,L$MI,L$MA,L$LD,L$LA	;
GBLREF=L$NX,$LBEND,$MHBUF,$PARTD,$EPTHL,$MNTHL	;
GBLREF=$HDLST,$OPNFL,$ATTFG,$SWTCH,$MNBLK,$EPBLK;
GBLREF=$DMN,$LNDES,$LNBUF,$CMFLG,TY$ES,TY$MS	;
GBLREF=DF$TYP,SR0,LBRTAB,$OUTBF,$CSIBK		;
GBLREF=$MGLST,$ERMSG				; Module:LBRER
GBLREF=$FINDA,$FINDC,$FINDN			; Module:LBRFI
GBLREF=$DECD					; Module:LBRCD
GBLREF=$DEL					; Module:LBRDL
GBLREF=$INIT					; Module:LBRINI
GBLREF=$CRE					; Module:LBRCR
GBLREF=$CMP					; Module:LBRCM
GBLREF=LASTEP,$INS				; Module:LBRIN
GBLREF=$LIS					; Module:LBRLI
GBLREF=$LISCD					; Module:LBRLCD
GBLREF=$EXT					; Module:LBREX
;GBLREF=$RDHD					; Module:LBRRHD
GBLREF=$LIPTR,$OUT,$OUT1			; Module:LBROUT
GBLREF=$RDLHD					; Module:LBRRLH
GBLREF=$RDEP,$RDMN				; Module:LBRTBL
GBLREF=$WTHD					; Module:LBRWHD
GBLREF=$FIXLA					; Module:LBRFLA
GBLREF=$DELM					; Module:LBRDLM
GBLREF=$RDMH 					; Module:LBRRMH
GBLREF=$NEXT					; Module:LBRNXT
GBLREF=PUT,EPTERR				; Module:LBRPUT
GBLREF=$FMTER					; Module:LBRERF
GBLREF=$EROUT,$QIOMG,$QIO,$TTYAT,$TTYDT		; Module:LBRERO
;
;	GLOBAL REFERENCES FROM SYSLIB.OLB
;
GBLREF=$EXST					; Module:EXST
GBLREF=$SAVVR					; Module:SAVVR
GBLREF=.SAVR1					; Module:SAVR1
GBLREF=.GCML1,.GCML2,.GCML3			; Module:.GCML
GBLREF=.CSI1					; Module:.CSI1
GBLREF=.CSI2					; Module:.CSI2
GBLREF=.ODCVT,.DCCVT				; Module:.ODCVT
GBLREF=$EDMSG					; Module:EDTMG
GBLREF=$DAT,$TIM				; Module:EDDAT
GBLREF=$CBDAT,$CBDMG,$CBDSG,$CBOMG,$CBOSG,$CBTA ; Module:CBTA
GBLREF=$CBTMG					;
GBLREF=$C5TA					; Module:C5TA
GBLREF=$CAT5					; Module:CAT5
GBLREF=.PARSE,..PARS,..STFN			; Module:PARSE
GBLREF=.XQIO					; Module:XQIOU
GBLREF=.GETSQ					; Module:GETSQ
GBLREF=.PUT					; Module:PUT
GBLREF=.POINT,.MARK				; Module:PNTMRK
;GBLREF=..RWAC,..RWAT				; Module:RDWAIT
;GBLREF=..WTWA,..WTWD,..WTW1			; Module:WTWAIT
GBLREF=.OPFNB					; Module:OPFNB
GBLREF=.FINIT,..FINI				; Module:FINIT
GBLREF=.MRKDL					; Module:MRKDL
GBLREF=.CLOSE					; Module:CLOSE
GBLREF=.READ					; Module:READ
GBLREF=.WRITE					; Module:WRITE
;
;	GLOBAL REFERENCES FROM TKB.OLB
;
GBLREF=$ALVRT					; Module:ALVRT
GBLREF=$ALBLK					; Module:ALBLK
GBLREF=$RQVCB					; Module:RQVCB
GBLREF=$RDPAG,$WRPAG				; Module:RDPAG
GBLREF=$CVRL					; Module:CVRL
GBLREF=$FNDPG					; Module:FNDPG
GBLREF=$GTCOR					; Module:GTCOR
GBLREF=$LCKPG,$UNLPG,$WRMPG			; Module:MRKPG
GBLREF=$HGVAD,$PAGLS,$PAGHD,$TIME,$WRKPT	; Module:VMDAT
GBLREF=$GTCML					; Module:GTCML
GBLREF=$INIVM					; Module:INIVM
GBLREF=$SCANI,$SCANO,$SYNTX			; Module:SCAN
