TITLE	.NELEM,<Get Number of Elements in List>,0A,10-MAY-91,CEK

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	EDIT HISTORY FOR NELEM
;+
;
;  001	CEK  16-APR-82	Added edit history
;
;-

;+
; .NELEM	symbol,<list>
;
; The .NELEM macro is used to determine the number of elements in a list.
;
; symbol represents any legal symbol.  This symbol is equated to the number
;	 of elements in the specified list.  If the list is null, symbol
;	 is equated to zero.
;
; list	 represents a list of elements, which must be separated by any legal 
; 	 separator (comma, space, and/or tab).  The list must be enclosed
;	 in angle brackets.
;-

.MACRO	.NELEM	SYMBOL,LIST
SYMBOL	=	0
	.IRP	I,<LIST>
SYMBOL	=	SYMBOL + 1
	.ENDR
	.ENDM
