

$ CMS SET LIBRARY DISK$USER3:[MACRO11.][MACRO.CMSLIB]
$ SET NOON
$ SET DEFAULT USER3$:[MACRO11.RSTS]
$! IF F$SEARCH("DESCRIP.MMS") .EQS "" THEN CMS FETCH DESCRIP.MMS ""
$ MMS/CMS/MACRO=("RSTS=1","CMSFLAGS=/GEN=1+") ALL
$ EXIT
