;  DEC/CMS REPLACEMENT HISTORY, Element ENBDS.MAC
;  *3    18-AUG-1986 11:19:15 WORRALL "Complete HEX listing support for version 5.5 fieldtest"
;  *2    14-APR-1986 23:19:02 SYSTEM "Update 5.4 of MACRO-11"
;  *1    28-MAR-1986 02:35:18 SYSTEM "Load MACRO-11 sources from V5.3"
;  DEC/CMS REPLACEMENT HISTORY, Element ENBDS.MAC
	.NLIST							;Edit Level 00
	.ENABL	LC,GBL
	.LIST
	.TITLE	ENBDS - .ENABL/.DSABL DIRECTIVES
	.SBTTL	ENBDS - .ENABL/.DSABL DIRECTIVES
	.SBTTL
	.SBTTL		.IDENT	/V05.05/
	.SBTTL
	.IDENT	/V05.05/
;****************************************************************************
;*									    *
;*                   COPYRIGHT (c)  1983, 1986                              *
;*          BY DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.                *
;*                   ALL RIGHTS RESERVED.                                   *
;* 									    *
;*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED  *
;*  ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE  *
;*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER  *
;*  COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY  *
;*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY  *
;*  TRANSFERRED.							    *
;* 									    *
;*  THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE  *
;*  AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT  *
;*  CORPORATION.							    *
;* 									    *
;*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS  *
;*  SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.		    *
;*									    *
;****************************************************************************


;++
;  Facility:	MACRO-11  The PDP-11 macro assembler for RT/RSX/VMS and RSTS/E
;
;    Author:	Too many people to list here
;
;   Created:	From the dust and dirt
;
;  Abstract:	ENBDS - .ENABL/.DSABL DIRECTIVES
;
;     Externals	 Description
;     ---------	 -----------
;
;      Edit	Who	Date		Description of modification
;      ----	---	----		---------------------------
;--


	PURE	PUREI,I

;+
; **-ENABL-ENABLE/DISABLE FUNCTION
;-

.ENABL	LSB

ENABL::				;R3=0 IMPLIES ".ENABL"
				;R3=-1 IMPLIES ".DSABL"
	CALL	GSARG		;Get symbolic argument
	BEQ	10$		;Just return if null
$EDABL::SCANW	EDTROL		;Search the table
	BEQ	7$		;Branch if not there, error
	CLR	R2		;Compute bit position
	SEC
2$:	ROL	R2
	SOB	R0,2$
	TST	EXMFLG		;Called from command string?
	BEQ	3$		;Branch if not
	BIS	R2,EDMCSI	;Else, set disable bits
	BR	4$		;  and bypass test

3$:	BIT	R2,EDMCSI	;Over-ridden from CSI?
	BNE	ENABL		;Branch if so, IGNORE!
4$:	BIC	R2,EDMASK	;Else, Clear selected bit
	TST	R3		;.ENABL?
	BEQ	5$		;Branch if so, leave it clear
	BIS	R2,EDMASK	;Else, set the bit for .DSABL
5$:	MOV	R3,-(SP)	;Preserve R3 and set flags		;JR
	CALL	@SYMBOL+2	;Call action routine (if any)		;JR
	MOV	(SP)+,R3	;Restore .ENABL/DSABL flags register	;JR
	BR	ENABL		;Loop to process any further parameters	;JR

7$:	ERROR	A
10$:	RETURN
.DSABL LSB


	.END
