;  DEC/CMS REPLACEMENT HISTORY, Element FLGDF.MAC
;  *3    18-AUG-1986 11:20:34 WORRALL "Complete HEX listing support for version 5.5 fieldtest"
;  *2    14-APR-1986 23:21:17 SYSTEM "Update 5.4 of MACRO-11"
;  *1    28-MAR-1986 02:36:27 SYSTEM "Load MACRO-11 sources from V5.3"
;  DEC/CMS REPLACEMENT HISTORY, Element FLGDF.MAC
	.NLIST
	.ENABL	LC,GBL
	.SBTTL
	.SBTTL
	.SBTTL	FLGDF	- MACRO-11 static variable definitions	;Edit level 01
	.SBTTL
	.SBTTL		.IDENT	/V05.05/
	.SBTTL
;****************************************************************************
;*									    *
;*                   COPYRIGHT (c)  1983, 1986                              *
;*          BY DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.                *
;*                   ALL RIGHTS RESERVED.                                   *
;* 									    *
;*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED  *
;*  ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE  *
;*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER  *
;*  COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY  *
;*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY  *
;*  TRANSFERRED.							    *
;* 									    *
;*  THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE  *
;*  AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT  *
;*  CORPORATION.							    *
;* 									    *
;*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS  *
;*  SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.		    *
;*									    *
;****************************************************************************


;++
;  Facility:	MACRO-11  The PDP-11 macro assembler for RT/RSX/VMS and RSTS/E
;
;    Author:	Too many people to list here
;
;   Created:	From the dust and dirt
;
;  Abstract:	FLGDF	- MACRO-11 static variable definitions
;
; This prefix file contains symbolic definitions for character codes,
; object module record types and symbol table mode bits.
;
;     Externals	 Description
;     ---------	 -----------
;
;      Edit	Who	Date		Description of modification
;      ----	---	----		---------------------------
;	001	Jrw	07-Jun-83	Correct psect flags. Get rid
;					of bit 3.
;--


.DSABL	CRF

;+
; Symbolic character defines.
;-

CH.IOR=	'!
CH.QTM=	'"
CH.HSH=	'#
CH.DOL=	'$
CH.PCT=	'%
CH.AND=	'&
CH.XCL=	''
CH.LP=	'(
CH.RP=	')
CH.MUL=	'*
CH.ADD=	'+
CH.COM=	',
CH.SUB=	'-
CH.DOT=	'.
CH.DIV=	'/
CH.COL=	':
CH.SMC=	';
CH.LAB=	'<
CH.EQU=	'=
CH.RAB=	'>
CH.QM=	'?
CH.IND=	'@
CH.BSL=	'\
CH.UAR=	'^

LET.A=	'A
LET.B=	'B
LET.C=	'C
LET.D=	'D
LET.E=	'E
LET.F=	'F
LET.G=	'G
LET.O=	'O
LET.Z=	'Z

DIG.0=	'0
DIG.9=	'9

TAB=	11
LF=	12
VT=	13
FF=	14
CR=	15
SPACE=	40

LST.KB=	1
LST.LP=	2

;Object module definitions
;Relocation record (RLD) type defines

RLDT00=	00	;Absolute data
RLDT01=	01	;Internal relocation		TST	#c
RLDT02=	02	;Global relocation		TST	#G
RLDT03=	03	;Internal displaced relocation	TST	ABS
RLDT04=	04	;Global displaced relocation	TST	X
RLDT05=	05	;Global additive relocation	TST	#X+6
RLDT06=	06	;Global additive displaced	TST	#X+6
RLDT07=	07	;New csect			.=X
RLDT10=	10	;Sequence break			.=.+X
RLDT11=	11	;Program limits			.LIMIT
RLDT15=	15	;Sector additive relocation	TST	#O
RLDT16=	16	;Sector additive displaced	TST	#O+6
RLDT17=	17	;Complex relocation		TST	G1+G2*R1!R2...

;Global symbol dictionary entry types

GSDT00=	00*400	;Object module name
GSDT01=	01*400	;Program section name
GSDT02=	02*400	;Internal symbol table
GSDT03=	03*400	;Transfer address
GSDT04=	04*400	;Symbol declaration
GSDT05= 05*400	;Program section name
GSDT06=	06*400	;Version identification

;Object module record types

BLKT01=	01	;GSD
BLKT02=	02	;GSD End
BLKT03=	03	;Text block
BLKT04=	04	;RLD Block
BLKT05=	05	;ISD
BLKT06=	06	;Module end

;Flags used in symbol table mode

DEFFLG=	010		;Defined
DFGFLG= 020		;Defaulted global reference
RELFLG=	040		;Relocatable
GLBFLG=	100		;Global
CPXFLG= 200		;Complex relocation expression
NCRFLG= CPXFLG		;.NOCRF flag

REGFLG=	1		;Register
LBLFLG=	2		;Label
MDFFLG=	4		;Multilpy defined

; Flags used in complex relocation expressions

CPXOPC=	DEFFLG			;Complex opcode
CPXADD=	1			;Add
CPXSUB=	2			;Subtract
CPXMUL=	3			;Multiply
CPXDIV=	4			;Divide
CPXAND=	5			;And
CPXIOR=	6			;Inclusive or
CPXNEG=	10			;Negate
CPXCOM=	11			;Complement
CPXSTO=	12			;Store result
CPXSDS=	13			;Store result with displaced relocation
CPXGLB=	16			;Stack value of global symbol
CPXREL=	17			;Stack relocatable value
CPXCON=	20			;Stack constant

; Program section attribute flag bit definitions

CSTSAV= 001			;Save attribute (1=SAV, 0=Normal)
CSTALO=	004			;Allocation (1=OVR, 0=CON)
CSTACC=	020			;Access (1=RO, 0=RW)
CSTREL=	040			;Relocation (1=REL, 0=ABS)
CSTGBL=	100			;Scope (1=GLOBAL, 0=LOCAL)
CSTTYP=	200			;Type (1=DATA, 0=INSTRUCTION)

; Default section flags

ASTFLG=	CSTALO!CSTGBL           ;!DEFFLG	;ABS Section
CSTFLG=	CSTREL                  ;!DEFFLG		;CSECT Section
PSTFLG=	CSTFLG			;PSECT Section

; Address mode flags

AM.DEF=	10			;Deferred mode
AM.INC=	20			;Auto-increment mode
AM.DEC=	40			;Auto-decrement mode
AM.NDX=	60			;Index mode
AM.PC=	07			;PC Mode addressing
AM.IMM=	AM.INC+AM.PC		;Immediate mode
AM.REL=	AM.NDX+AM.PC		;Relative mode


.ENABL CRF
.LIST
