;  DEC/CMS REPLACEMENT HISTORY, Element MPUSH.MAC
;  *3    18-AUG-1986 11:24:47 WORRALL "Complete HEX listing support for version 5.5 fieldtest"
;  *2    14-APR-1986 23:35:49 SYSTEM "Update 5.4 of MACRO-11"
;  *1    28-MAR-1986 02:41:34 SYSTEM "Load MACRO-11 sources from V5.3"
;  DEC/CMS REPLACEMENT HISTORY, Element MPUSH.MAC
	.NLIST							;Edit Level 00
	.ENABL	LC,GBL
	.LIST
	.TITLE	MPUSH - Push current macro expansion context
	.SBTTL	MPUSH - Push current macro expansion context
	.SBTTL
	.SBTTL		.IDENT	/V05.05/
	.SBTTL
	.IDENT	/V05.05/
;****************************************************************************
;*									    *
;*                   COPYRIGHT (c)  1983, 1986                              *
;*          BY DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.                *
;*                   ALL RIGHTS RESERVED.                                   *
;* 									    *
;*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED  *
;*  ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE  *
;*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER  *
;*  COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY  *
;*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY  *
;*  TRANSFERRED.							    *
;* 									    *
;*  THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE  *
;*  AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT  *
;*  CORPORATION.							    *
;* 									    *
;*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS  *
;*  SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.		    *
;*									    *
;****************************************************************************


;++
;  Facility:	MACRO-11  The PDP-11 macro assembler for RT/RSX/VMS and RSTS/E
;
;    Author:	Too many people to list here
;
;   Created:	From the dust and dirt
;
;  Abstract:	MPUSH - Push current macro expansion context
;
;     Externals	 Description
;     ---------	 -----------
;
;      Edit	Who	Date		Description of modification
;      ----	---	----		---------------------------
;--


	PURE	PUREI,I
;+
;
; **-MPUSH-SAVE CURRENT MACRO CONTEXT
;
;-

MPUSH::	CALL	GETBLK		;++017 GET A STORAGE BLOCK
	TST	-(R2)		;POINT TO START
	MOV	#MSBBLK,R4	;++021 GET ADDR OF MACRO CONTEXT AREA
100$:	MOV	(R4),(R2)+	;++021 COPY CURRENT CONTEXT INTO SAVE BLK
	CLR	(R4)+		;++021 WHILE CLEARING MACRO CONTEXT AREA
	CMP	#MSBEND,R4	;++021 REPEAT FOR ENTIRE CONTEXT
	BNE	100$		;++021
	MOV	#MSBBLK,R2	;++021 GET ADDR OF MACRO CONTEXT AREA
	MOV	R5,(R2)+	;STORE CURRENT MACRO TYPE INDICATOR
	MOV	R1,(R2)+	;++021 SAVE VIRT LOCN OF CONTEXT SAVE BLK
	UNLPG			;++021 UNLOCK ITS PAGE
	INC	MACLVL		;BUMP LEVEL COUNT
	RETURN			;RETURN WITH R2 POINTING AT MSBTXT


	.END
