;  DEC/CMS REPLACEMENT HISTORY, Element SPACE.MAC
;  *3    18-AUG-1986 11:27:46 WORRALL "Complete HEX listing support for version 5.5 fieldtest"
;  *2    14-APR-1986 23:56:55 SYSTEM "Update 5.4 of MACRO-11"
;  *1    28-MAR-1986 02:46:19 SYSTEM "Load MACRO-11 sources from V5.3"
;  DEC/CMS REPLACEMENT HISTORY, Element SPACE.MAC
	.NLIST							;Edit Level 00
	.ENABL	LC,GBL
	.LIST
	.TITLE	SPACE - Return macro storage to macro freespace
	.SBTTL	SPACE - Return macro storage to macro freespace
	.SBTTL
	.SBTTL		.IDENT	/V05.05/
	.SBTTL
	.IDENT	/V05.05/
;****************************************************************************
;*									    *
;*                   COPYRIGHT (c)  1983, 1986                              *
;*          BY DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.                *
;*                   ALL RIGHTS RESERVED.                                   *
;* 									    *
;*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED  *
;*  ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE  *
;*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER  *
;*  COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY  *
;*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY  *
;*  TRANSFERRED.							    *
;* 									    *
;*  THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE  *
;*  AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT  *
;*  CORPORATION.							    *
;* 									    *
;*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS  *
;*  SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.		    *
;*									    *
;****************************************************************************


;++
;  Facility:	MACRO-11  The PDP-11 macro assembler for RT/RSX/VMS and RSTS/E
;
;    Author:	Too many people to list here
;
;   Created:	From the dust and dirt
;
;  Abstract:	SPACE - Return macro storage to macro freespace
;
;     Externals	 Description
;     ---------	 -----------
;
;      Edit	Who	Date		Description of modification
;      ----	---	----		---------------------------
;--


	PURE	PUREI,I

;+
;
; **-REMMAC--REMOVE MACRO TEXT (PLACE BLOCKS IN MACRO FREE LIST)
;
; INPUTS:
;	R0=ADDRESS OF FIRST TEXT BLOCK TO BE REMOVED.
;	R1=VIRTUAL LOCN OF THE FIRST BLOCK
;
; OUTPUTS:
;	THE MACRO STORAGE BLOCKS ARE RETURNED TO THE MACRO FREE
;	LIST.  R0 AND R1 ARE LOST.
;
;-

REMMAC::MOV	R1,-(SP)	;++021 SAVE VIRT LOCN OF 1ST BLOCK
	MOV	MACNXT,-(SP)	;++021 SAVE VIRT LOCN OF 1ST FREE BLK
	BEQ	300$		;++021 IF EQ FREE LIST IS EMPTY
	MOV	R2,-(SP)	;++021 SAVE R2
	BR	200$		;++021 BRANCH INTO LOOP CODE
100$:	MOV	(R0),R1		;++021 GET VIRT LOCN OF NEXT BLOCK
	CVRL			;++021 GET ITS REAL ADDR IN R0
200$:	TST	(R0)		;++021 EXAMINE LINK TO NEXT BLOCK
	BNE	100$		;++021 IN NE NOT AT END OF LIST
	MOV	(SP)+,R2	;++021 ELSE, RESTORE R2
	MOV	(SP),(R0)	;++021 LINK IT TO FREE LIST
	WRMPG			;++021 MARK PAGE DIRTY
300$:	TST	(SP)+		;++021 CLEAN STACK
	MOV	(SP)+,MACNXT	;++021 LINK BLOCKS TO FRONT OF FREE LIST
	RETURN			;++021


	.END
