;  DEC/CMS REPLACEMENT HISTORY, Element WORDB.MAC
;  *3    18-AUG-1986 11:28:26 WORRALL "Complete HEX listing support for version 5.5 fieldtest"
;  *2    14-APR-1986 23:59:18 SYSTEM "Update 5.4 of MACRO-11"
;  *1    28-MAR-1986 02:47:15 SYSTEM "Load MACRO-11 sources from V5.3"
;  DEC/CMS REPLACEMENT HISTORY, Element WORDB.MAC
	.NLIST							;Edit Level 00
	.ENABL	LC,GBL
	.LIST
	.TITLE	WORDB - .WORD/.BYTE Storage directives
	.SBTTL	WORDB - .WORD/.BYTE Storage directives
	.SBTTL
	.SBTTL		.IDENT	/V05.05/
	.SBTTL
	.IDENT	/V05.05/
;****************************************************************************
;*									    *
;*                   COPYRIGHT (c)  1983, 1986                              *
;*          BY DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.                *
;*                   ALL RIGHTS RESERVED.                                   *
;* 									    *
;*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED  *
;*  ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE  *
;*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER  *
;*  COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY  *
;*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY  *
;*  TRANSFERRED.							    *
;* 									    *
;*  THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE  *
;*  AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT  *
;*  CORPORATION.							    *
;* 									    *
;*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS  *
;*  SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.		    *
;*									    *
;****************************************************************************


;++
;  Facility:	MACRO-11  The PDP-11 macro assembler for RT/RSX/VMS and RSTS/E
;
;    Author:	Too many people to list here
;
;   Created:	From the dust and dirt
;
;  Abstract:	WORDB - .WORD/.BYTE Storage directives
;
;     Externals	 Description
;     ---------	 -----------
;
;      Edit	Who	Date		Description of modification
;      ----	---	----		---------------------------
;--


	PURE	PUREI,I

;+
; **-BYTE-GENERATE BYTE/WORD DATA
;-

BYTE::	INC	R3		;++011 R3=1 IMPLIES ".BYTE"
				;++011 R3=2 IMPLIES ".WORD"
	MOV	(R2),-(SP)	;STACK CURRENT PC
1$:	TSTARG			;TEST FOR ARGUMENT
	BEQ	2$		;  END
	EXPR			;PROCESS GENERAL EXPRESSION
	SETIMM			;CONVERT TO OBJECT FORMAT
	STCODE			;PUT ON CODE ROLL
	ADD	R3,(R2)		;UPDATE PC
	BR	1$		;TEST FOR MORE
2$:	MOV	(SP)+,(R2)	;RESTORE INITIAL PC
	TST	$LSCNT+CODLST	;++021 WAS THERE GENERATED CODE?
	BNE	10$		;++021 IF NE YES
	CLR	MODE		;NO, STORE A ZERO
	CLR	VALUE
	SETIMM
	STCODE
10$:	RETURN			;++021


	.END
