$JOB/CCL/NOLIMIT/PRI:-16 [170,46]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$ASSIGN <40>
$SWITCH RT11
$SIZE 20
$R SY:LINK
HOOK.SV/Z/K:28.,LSD:HOOK/W/N,SY:HOOK=HOOK,[170,42]BLDBOT,RSTSLB/X
HOOKOD.SV/Z/K:28.,LSD:HOOKOD/W/N,SY:HOOKOD=HOOK/X,[170,42]BLDBOT,RSTSLB/I/T
O.ODT
O.ODT

$R SY:SILUS
HOOK.SAV/S,LSD:HOOK=HOOK.SV/N
HOOK
HOOKOD.SAV/S,LSD:HOOKOD=HOOKOD.SV/N
HOOKOD
$R SY:$PIP
HOOK.SV,HOOK.STB,HOOK.OBJ/DE/NOLOG
HOOKOD.SV,HOOKOD.STB/DE/NOLOG
$EOJ
