$JOB/CCL/NOLIMIT [170,46]
ASSIGN LST: NL
ASSIGN NL: LST
DEASSIGN NL
ASSIGN D: SY
ASSIGN D: DK
$SWITCH RT11
$SIZE 20
$R SY:LINK
PIP.SV/Z,LST:PIP/W,SY:PIP=PIP/X/K:28.,RSTSLB
PIPOD.SV/Z,LST:PIPOD/W,SY:PIPOD=PIP/X/K:28.,RSTSLB/I/T
O.ODT
O.ODT

$R SY:SILUS
PIP.SAV/S,LST:PIP=PIP.SV/N
PIP
PIPOD.SAV/S,LST:PIPOD=PIPOD.SV/N
PIPOD
$R PIP
PIP.SV,PIP.OBJ,PIP.STB/DE/NOLOG
PIPOD.SV,PIPOD.STB/DE/NOLOG
$EOJ
