;
; In task data structures, overlay runtime system, and supermode support
;
;	REG	25-JUL-87	UPDATE FOR RSX CHANGES
;
LST:ALERR/-SP
LST:AUTO /-SP
LST:AUTOT/-SP
LST:AUTOA/-SP
LST:CMPAL/-SP
LST:LOAD /-SP
LST:OVCTL/-SP
LST:OVCTR/-SP
LST:OVCTC/-SP
LST:OVIDL/-SP
LST:OVIDR/-SP
LST:OVIDC/-SP
LST:FSTMAP/-SP
LST:OVFCTL/-SP
LST:OVFCTR/-SP
LST:OVFCTC/-SP
LST:OVDAT/-SP
LST:OVRES/-SP
LST:SUPL /-SP
LST:VCTDF/-SP
LST:VEXT /-SP
LST:VEXTA/-SP
;
; Conversion routines
;
LST:CATB/-SP
LST:CAT5/-SP
LST:CAT5B/-SP
LST:CBTA/-SP
LST:C5TA/-SP
LST:CDDMG/-SP
LST:CVTUC/-SP
LST:EDDAT/-SP
LST:EDTMG/-SP
LST:HLPSUB/-SP
LST:PGLEN/-SP
LST:RQLCB/-SP
LST:SAVAL/-SP
LST:SAVRG/-SP
LST:SAVVR/-SP
;
; Supervisor mode modules
;
;LST:EDDAT.SST/-SP
;LST:EDTMG.SST/-SP
