;
; In task data structures, overlay runtime system, and supermode support
;
;	REG	25-JUL-87	UPDATE FOR RSX CHANGES
;
SYSTEM:SYSLIB.OLB/RP=SYSTEM:ALERR	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:AUTOA	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:CMPAL	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:OVDAT	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:OVRES	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:SUPL	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:VCTDF	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:VEXT	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:VEXTA	
;
; Conversion routines
;
SYSTEM:SYSLIB.OLB/RP=SYSTEM:CATB	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:CAT5	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:CAT5B	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:CBTA	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:C5TA	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:CDDMG	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:CVTUC	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:EDDAT	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:EDTMG	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:HLPSUB	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:PGLEN
SYSTEM:SYSLIB.OLB/RP=SYSTEM:RQLCB	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:SAVAL	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:SAVRG	
SYSTEM:SYSLIB.OLB/RP=SYSTEM:SAVVR	
