;
; Insert task builder runtime overlay modules
;
;	REG	25-JUL-87	MODIFY FOR LATEST RSX CHANGES
;
SYSTEM:SYSLIB/RP=UTL:LOAD.DGE
SYSTEM:SYSLIB/DG:$AUTO:$ALBPL
;
SYSTEM:SYSLIB/RP=UTL:AUTOT.DGE
SYSTEM:SYSLIB/DG:$ALBP1:$ALBP2:$ALBPL:$AUTO
;
SYSTEM:SYSLIB/RP=UTL:AUTO.DGE
SYSTEM:SYSLIB/DG:$ALBP1:$ALBP2:$ALBPL
;
;	SYSTEM:SYSLIB/RP=UTL:AUTOX.DGE
;	SYSTEM:SYSLIB/RP=UTL:AUTOY.DGE
;
SYSTEM:SYSLIB/RP=UTL:FSTMAP.DGE
;
SYSTEM:SYSLIB/RP=UTL:OVFIDC.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARKR:$MARKC:$MARDS:$MARDR
SYSTEM:SYSLIB/DG:$MARDC:$MAFKS:$MAFKR:$MAFKC:$MAFDS:$MAFDR
; leave in $MAFDC
;
SYSTEM:SYSLIB/RP=UTL:OVFIDR.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARKR:$MARDS
SYSTEM:SYSLIB/DG:$MARDR:$MAFKS:$MAFKR:$MAFDS
; leave in $MAFDR
;
SYSTEM:SYSLIB/RP=UTL:OVFIDL.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARDS:$MAFKS
; leave in $MAFDS
;
SYSTEM:SYSLIB/RP=UTL:OVFCTC.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARKR:$MARKC:$MAFKS:$MAFKR
; leave in $MAFKC
;
SYSTEM:SYSLIB/RP=UTL:OVFCTR.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARKR:$MAFKS
; leave in $MAFKR
;
SYSTEM:SYSLIB/RP=UTL:OVFCTL.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS
; leave in $MAFKS
;
SYSTEM:SYSLIB/RP=UTL:OVIDC.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARKR:$MARKC:$MARDS:$MARDR
; leave in $MARDC
;
SYSTEM:SYSLIB/RP=UTL:OVIDR.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARKR:$MARDS
; leave in $MARDR
;
SYSTEM:SYSLIB/RP=UTL:OVIDL.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS
; leave in $MARDS
;
SYSTEM:SYSLIB/RP=UTL:OVCTC.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS:$MARKR
; leave in $MARKC
;
SYSTEM:SYSLIB/RP=UTL:OVCTR.DGE
SYSTEM:SYSLIB/DG:$RDSEG:$MARKS
; leave in $MARKR
;
SYSTEM:SYSLIB/RP=UTL:OVCTL.DGE
SYSTEM:SYSLIB/DG:$RDSEG
; leave in $MARKS
;
