; CRFASM.CMD
;
; MAC COMMAND FILE TO ASSEMBLE CREF (CRF.TSK) MODULES
;
SYSTEM:CREF ,LST:CREF /CR/-SP=RSX:COMMON,CRF:MACFLM,CREF
SYSTEM:CRF  ,LST:CRF  /CR/-SP=RSX:COMMON,CRF:MACFLM,CRF
SYSTEM:CRFDB,LST:CRFDB/CR/-SP=RSX:COMMON,CRF:CRFMC ,CRFDB
SYSTEM:CRFER,LST:CRFER/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFER
SYSTEM:CRFEX,LST:CRFEX/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFEX
SYSTEM:CRFIN,LST:CRFIN/CR/-SP=CMN:COMMON,FCS:RSTS  ,CRF:MACFLM,CRFIN
SYSTEM:CRFIO,LST:CRFIO/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFIO
SYSTEM:CRFLB,LST:CRFLB/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFLB
SYSTEM:CRFOT,LST:CRFOT/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFOT
SYSTEM:CRFP1,LST:CRFP1/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFP1
SYSTEM:CRFP3,LST:CRFP3/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFP3
SYSTEM:CRFP4,LST:CRFP4/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFP4
SYSTEM:CRFPG,LST:CRFPG/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFPG
SYSTEM:CRFRF,LST:CRFRF/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFRF
SYSTEM:CRFTB,LST:CRFTB/CR/-SP=RSX:COMMON,CRF:MACFLM,CRFTB
SYSTEM:FNDFM,LST:FNDFM/CR/-SP=RSX:COMMON,CRF:MACFLM,FNDFM
SYSTEM:FNDTD,LST:FNDTD/CR/-SP=RSX:COMMON,CRF:MACFLM,FNDTD
SYSTEM:GTCRF,LST:GTCRF/CR/-SP=RSX:COMMON,CRF:MACFLM,GTCRF
SYSTEM:ICRIO,LST:ICRIO/CR/-SP=RSX:COMMON,CRF:MACFLM,ICRIO
SYSTEM:INERR,LST:INERR/CR/-SP=RSX:COMMON,CRF:MACFLM,INERR
SYSTEM:INIDM,LST:INIDM/CR/-SP=RSX:COMMON,CRF:MACFLM,INIDM
SYSTEM:SRCIV,LST:SRCIV/CR/-SP=RSX:COMMON,CRF:MACFLM,SRCIV
SYSTEM:SRCST,LST:SRCST/CR/-SP=RSX:COMMON,CRF:MACFLM,SRCST
;
