; CRFCRF.CMD
;
; CRF COMMAND FILE TO CREF CREF (CRF.TSK) MODULES
;
LST:CREF.LST/-SP
LST:CRF.LST/-SP
LST:CRFDB.LST/-SP
LST:CRFER.LST/-SP
LST:CRFEX.LST/-SP
LST:CRFIN.LST/-SP
LST:CRFIO.LST/-SP
LST:CRFLB.LST/-SP
LST:CRFOT.LST/-SP
LST:CRFP1.LST/-SP
LST:CRFP3.LST/-SP
LST:CRFP4.LST/-SP
LST:CRFPG.LST/-SP
LST:CRFRF.LST/-SP
LST:CRFTB.LST/-SP
LST:FNDFM.LST/-SP
LST:FNDTD.LST/-SP
LST:GTCRF.LST/-SP
LST:ICRIO.LST/-SP
LST:INERR.LST/-SP
LST:INIDM.LST/-SP
LST:SRCIV.LST/-SP
LST:SRCST.LST/-SP
;
