;	THIS COMMAND FILE IS CALLED BY CRF:CRFBLD.CMD
;	IT DEFINES THE GLOBAL REFERENCES FOR RSTS
;
EXTSCT=.99998:1000	; ALLOCATE PATCH SPACE IN ROOT
;
; GLOBAL REFERENCES TO ROOT AND OVERLAY SEGMENTS
;
;	GLOBAL REFERENCES FROM CRF.OLB
;
GBLREF=$ERBF,$ERBFE,$RECBF,$RECBE,$CRIDB,$CRODB	; Module:CRFIO
GBLREF=$CRSDB,$CRCDB,$CDLUN			;
GBLREF=$CRFEX					; Module:CRFEX
GBLREF=D$SYM,D$SREF,D$SVAL,D$ATTR,D$FMT,D$LTH	; Module:CRFTB
GBLREF=N$DLGH,R$CNAM,R$CTYP,R$CVER,R$CDID,R$CDEV;
GBLREF=R$CUNT,R$CFLG,R$CRVR,R$CODV,R$COUN,R$FNXT;
GBLREF=R$FSYM,R$FLG,R$FLTH,S$YNXT,S$YPRV,S$YUP	;
GBLREF=S$YM,S$YFLG,S$YREF,S$YVAL,S$YLTH,$CRFLG	;
GBLREF=$CRFGM,$CRFTK,$CRFID,$CRFDT,$CRFIF,$CRIDN;
GBLREF=$ERVCT,$EXSTS,$FRHD,$FMTPT,$RCVBF	;
GBLREF=S$YNXT,S$YPRV,S$YUP,S$YM,B$HOL,B$HCT	; Module:SRCIV
GBLREF=B$DAT,H$ISYM,H$NODE,H$LBR,H$RBR,H$FINS	;
GBLREF=H$FNOD,L$RNOD,L$ESIZ,L$NSIZ,$ISEDV,$ISYMV;
GBLREF=$SRCHV,$SRCIV				;
GBLREF=$CREF,$EXIT				; Module:CREF
GBLREF=$FMCT					; Module:CRFDB
GBLREF=$CRFIN					; Module:CRFIN
GBLREF=$ICRIO,SETNM				; Module:ICRIO
GBLREF=$INIDM					; Module:INIDM
GBLREF=$CRFP1					; Module:CRFP1
GBLREF=$CRFP4					; Module:CRFP4
GBLREF=$FNDFM					; Module:FNDFM
GBLREF=$FNDTD					; Module:FNDTD
GBLREF=$GTCRF					; Module:GTCRF
GBLREF=$BYTCT,$NBYTE,$PAGNO,$CRFP3		; Module:CRFP3
GBLREF=$CRFLB					; Module:CRFLB
GBLREF=$CRFSH,$CRFOT				; Module:CRFOT
GBLREF=$CRFPG					; Module:CRFPG
GBLREF=$CRFRF					; Module:CRFRF
GBLREF=$SRCST					; Module:SRCST
GBLREF=$ERTRP,$ERMSG				; Module:CRFER
;
;	GLOBAL REFERENCES FROM SYSLIB.OLB
;
GBLREF=$EDMSG					; Module:EDTMG
GBLREF=.GETSQ					; Module:GETSQ
GBLREF=.POINT,.MARK				; Module:PNTMRK
GBLREF=.PUTSQ					; Module:PUTSQ
GBLREF=.READ					; Module:READ
GBLREF=.WRITE					; Module:WRITE
GBLREF=.ASLUN,..ALUN				; Module:ASSLUN
GBLREF=.CLOSE					; Module:CLOSE
GBLREF=.DLFNB					; Module:DLFNB
GBLREF=.FINIT,..FINI				; Module:FINIT
GBLREF=.MRKDL					; Module:MRKDL
GBLREF=.OPFNB					; Module:OPFNB
GBLREF=.ENTER,.FIND,.REMOV			; Module:UDIREC
;
;	GLOBAL REFERENCES FROM TKB.OLB
;
GBLREF=$ALBLK					; Module:ALBLK
GBLREF=$ALVRT					; Module:ALVRT
GBLREF=$CVRL					; Module:CVRL
GBLREF=$FNDPG					; Module:FNDPG
GBLREF=$GTCOR					; Module:GTCOR
GBLREF=$LCKPG,$UNLPG,$WRMPG			; Module:MRKPG
GBLREF=$RDPAG,$WRPAG				; Module:RDPAG
GBLREF=$RQVCB					; Module:RQVCB
GBLREF=$HGVAD,$PAGLS,$PAGHD,$TIME,$WRKPT	; Module:VMDAT
GBLREF=$CVLOK,$LNKVM,$GNVI			; Module:VMUTL
GBLREF=$ALSVB					; Module:ALSVB
GBLREF=$INIVM					; Module:INIVM
GBLREF=$ISYMR,$SRCHR				; Module:RSRCH
