;
; MAC COMMAND FILE TO ASSEMBLE FCS MODULES FOR MULTIPLE BUFFERING, BIG
; BUFFERING, AND ANSI MAGTAPE.
;
; MODULES WHICH ARE AFFECTED BY BIG BUFFERING AND ANSI MAGTAPE BUT 
; NOT BY MULTIPLE BUFFERING ARE ALSO ASSEMBLED HERE.  ALL MODULES
; ASSEMBLED BY THIS FILE WILL HAVE THE EXTENSION MBF.
;
; ALTERED:
;		25-OCT-79 STEVE RUZICH FCSTYP
;		21-NOV-79 STEVE RUZICH MOVE THIS FILE TO SYSTEM:,
;			REMOVING FCSMPLUS.MAC.
;
SYSTEM:ANSPAD.MBJ,LST:ANSPAD.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSBIGBUF,FCSPRE,ANSPAD
;
SYSTEM:ASSLUN.MBJ,LST:ASSLUN.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSBIGBUF,FCSPRE,ASSLUN
;
SYSTEM:BIGBUF.MBJ,LST:BIGBUF.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSBIGBUF,FCSPRE,BIGBUF
;
SYSTEM:CLOSE.MBJ,LST:CLOSE.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,CLOSE
;
SYSTEM:CREATE.MBJ,LST:CREATE.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,FCSANSI,FCSBIGBUF,FCSPRE,CREATE
;
SYSTEM:DIRECT.MBJ,LST:DIRECT.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,FCSANSI,FCSBIGBUF,FCSPRE,DIRECT
;
SYSTEM:FCSTYP.MBJ,LST:FCSTYP.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,FCSTYP
;
SYSTEM:GET.MBJ,LST:GET.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSBIGBUF,FCSPRE,GET
;
SYSTEM:GETSQ.MBJ,LST:GETSQ.MST/CR/-SP=-
RSX:COMMON,FCS:GPSEQ,FCSANSI,FCSBIGBUF,FCSPRE,GET
;
SYSTEM:OPEN.MBJ,LST:OPEN.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,OPEN
;
SYSTEM:OPENR.MBJ,LST:OPENR.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,OPENR,FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,OPEN
;
SYSTEM:OPFID.MBJ,LST:OPFID.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,OPFID,FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,OPEN
;
SYSTEM:OPFNB.MBJ,LST:OPFNB.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,OPFNB,FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,OPEN
;
SYSTEM:POINT.MBJ,LST:POINT.MST/CR/-SP=-
CMN:COMMON,FCS:RSTS,FCSANSI,FCSBIGBUF,FCSPRE,POINT
;
SYSTEM:PUT.MBJ,LST:PUT.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSBIGBUF,FCSPRE,PUT
;
SYSTEM:PUTSQ.MBJ,LST:PUTSQ.MST/CR/-SP=-
RSX:COMMON,FCS:GPSEQ,FCSANSI,FCSBIGBUF,FCSPRE,PUT
;
SYSTEM:RDWAIT.MBJ,LST:RDWAIT.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,RDWAIT
;
SYSTEM:RETADR.MBJ,LST:RETADR.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSBIGBUF,FCSPRE,RETADR
;
SYSTEM:RSTFDB.MBJ,LST:RSTFDB.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,RSTFDB
;
SYSTEM:RWBLK.MBJ,LST:RWBLK.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,RWBLK
;
SYSTEM:WATSET.MBJ,LST:WATSET.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSBIGBUF,FCSPRE,WATSET
;
SYSTEM:WTWAIT.MBJ,LST:WTWAIT.MST/CR/-SP=-
RSX:COMMON,FCS:FCSANSI,FCSMULBUF,FCSBIGBUF,FCSPRE,WTWAIT
