;
;	LBR control file to concatenate object files that
;	must have their entry points deleted in FCSNEP.
;
SYSTEM:FCSNEP.OLB/RP/-EP=SYSTEM:OPENR.NBJ
SYSTEM:FCSNEP.OLB/RP/-EP=SYSTEM:DELJMP.OBJ
SYSTEM:FCSNEP.OLB/RP/-EP=SYSTEM:FCSJMP.OBJ
SYSTEM:FCSNEP.OLB/RP/-EP=SYSTEM:FCSVEC.OBJ
SYSTEM:FCSNEP.OLB/RP/-EP=SYSTEM:GPTJMP.OBJ
SYSTEM:FCSNEP.OLB/RP/-EP=SYSTEM:OPNJMP.OBJ
