;
; TKB BUILD FILE FOR PLAS OVERLAYED FCSRES
; ON A MAPPED RSX-11M SYSTEM
; USING ANSLIB
; CREATED BY SGNBLDBLD.CMD VERSION 1.62
;
[1,1]FCSRES/-HD/PI,[1,34]FCSRES/-SP/MA,[1,1]FCSRES=
[1,24]FCSRS1BLD.ODL/MP
STACK=0
;
;
; ENTRY POINTS NOT USED BY RSX UTILITIES ARE
; COMMENTED OUT.
;
PAR=FCSRES:0:26500
;
;	OPEN OVERLAY ENTRY POINTS FROM OPEN, PARSE, CLOSE
;
GBLREF=.OPEN,.OPFNB,.OPFID,.ASCPP,.PPASC,.FINIT,.CLOSE,$RQCB,$RLCB
;GBLREF=.PARSE,.PRSDI,.PRSDV,.PRSFN,.ODCVT,.DCCVT,.VRCVT,.ASLUN
GBLREF=.PARSE,.PRSDV,.ODCVT,.DCCVT,.VRCVT,.ASLUN
;		FROM GETDID:
GBLREF=.GTDID
;		FROM GETDIR:
GBLREF=.GTDIR
;		FROM EXTEND:
GBLREF=.EXTND
;		FROM PPNR50:
;GBLREF=.PPR50
;		FROM UDIREC:
GBLREF=.ENTER,.FIND,.REMOV
;		FROM TRNCLS:
GBLREF=.TRNCL
;		FROM MRKDL:
GBLREF=.MRKDL
;		FROM DELETE:
GBLREF=.DELET
;		FROM DLFNB:
GBLREF=.DLFNB
;		FROM RENAME:
GBLREF=.RENAM
;		FROM $PRINT:
GBLREF=.PRINT
;		FROM DSPAT:
;GBLREF=$DSPAT
;
;	GET-PUT OVERLAY - ENTRY POINTS FROM GET, PUT, READ, WRITE
;
;GBLREF=.GET,.PUT,.READ,.WRITE,$MUL,$DIV,$DMUL,$DDIV,.CTRL,.GETSQ
GBLREF=.GET,.PUT,.READ,.WRITE,$MUL,$DIV,$DMUL,$DDIV,.GETSQ
GBLREF=.POSIT,.POSRC,.PUTSQ,.FCTYP
;
;	GET-PUT OVERLAY - ENTRY POINTS FROM OPTIONAL MODULES:
;
;		FROM PNTMRK:
GBLREF=.POINT,.MARK
;		FROM WAITU:
GBLREF=.WAIT
;		FROM XQIOU:
GBLREF=.XQIO
;		FROM RWFSR2:
GBLREF=.RDFDR,.RDFFP,.RDFUI,.RFOWN,.WDFDR,.WDFFP,.WDFUI,.WFOWN
;
;
;		FROM EXST:
GBLREF=$EXST
;
;		FROM EDTMG:
GBLREF=$EDMSG
;
;		FROM CAT5:
GBLREF=$CAT5
;
;		FROM C5TA:
GBLREF=$C5TA
;
;		FROM CATB:
GBLREF=$COTB,$CDTB
;
;		FROM CBTA:
GBLREF=$CBDAT,$CBDMG,$CBDSG,$CBOSG,$CBTA,$CBTMG,$CBVER,$CBOMG
;
;		FROM EDDAT:
GBLREF=$DAT,$TIM
;
;		FROM CDDMG:
GBLREF=$CDDMG
;
;
;	REGISTER SAVING ROUTINES $SAVAL, .SAVR1, $SAVVR, AND $SAVRG SHOULD
;	NEVER BE MADE ACCESSABLE FROM A MEMORY RESIDENT OVERLAYED LIBRARY.
;
/
