;
; CRF COMMAND FILE TO CREF FCS MODULES FOR MULTIPLE BUFFERING, BIG
; BUFFERING, AND ANSI MAGTAPE.
;
; MODULES WHICH ARE AFFECTED BY BIG BUFFERING AND ANSI MAGTAPE BUT 
; NOT BY MULTIPLE BUFFERING ARE ALSO ASSEMBLED HERE.  ALL MODULES
; ASSEMBLED BY THIS FILE WILL HAVE THE EXTENSION MBF.
;
; ALTERED:
;		25-OCT-79 STEVE RUZICH FCSTYP
;		21-NOV-79 STEVE RUZICH MOVE THIS FILE TO SYSTEM:,
;			REMOVING FCSMPLUS.MAC.
;
LST:ANSPAD.MST/-SP
LST:ASSLUN.MST/-SP
LST:BIGBUF.MST/-SP
LST:CLOSE.MST/-SP
LST:CREATE.MST/-SP
LST:DIRECT.MST/-SP
LST:FCSTYP.MST/-SP
LST:GET.MST/-SP
LST:GETSQ.MST/-SP
LST:OPEN.MST/-SP
LST:OPENR.MST/-SP
LST:OPFID.MST/-SP
LST:OPFNB.MST/-SP
LST:POINT.MST/-SP
LST:PUT.MST/-SP
LST:PUTSQ.MST/-SP
LST:RDWAIT.MST/-SP
LST:RETADR.MST/-SP
LST:RSTFDB.MST/-SP
LST:RWBLK.MST/-SP
LST:WATSET.MST/-SP
LST:WTWAIT.MST/-SP
