;
; LBR COMMAND FILE TO LBR FCS MODULES FOR MULTIPLE BUFFERING, BIG
; BUFFERING, AND ANSI MAGTAPE.
;
; MODULES WHICH ARE AFFECTED BY BIG BUFFERING AND ANSI MAGTAPE BUT 
; NOT BY MULTIPLE BUFFERING ARE ALSO ASSEMBLED HERE.  ALL MODULES
; ASSEMBLED BY THIS FILE WILL HAVE THE EXTENSION MBF.
;
; ALTERED:
;		25-OCT-79 STEVE RUZICH FCSTYP
;		21-NOV-79 STEVE RUZICH MOVE THIS FILE TO SYSTEM:,
;			REMOVING FCSMPLUS.MAC.
;
SYSTEM:MULLIB.OLB/RP=SYSTEM:ANSPAD.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:ASSLUN.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:BIGBUF.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:CLOSE.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:CREATE.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:DIRECT.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:FCSTYP.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:GET.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:GETSQ.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:OPEN.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:OPENR.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:OPFID.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:OPFNB.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:POINT.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:PUT.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:PUTSQ.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:RDWAIT.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:RETADR.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:RSTFDB.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:RWBLK.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:WATSET.MBJ
SYSTEM:MULLIB.OLB/RP=SYSTEM:WTWAIT.MBJ
