$JOB/CCL/NOLIMIT/PRIORITY:-16 [170,49]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$ASSIGN <40>
$SWITCH RT11
$R SY:PIP
*.BAK/DE:NOWARN/LOG
$SIZE 20
$R SY:MACRO
TTSYST,LSD:TTSYST/C=TTSYST
$EOJ
