;+
; ERROR
;

	.TITLE	FMSERR	- FMS FIELD PRIMITIVES ERROR MESSAGES
	.SBTTL	FMSERR	- FMS FIELD PRIMITIVES ERROR MESSAGES
	.SBTTL
	.IDENT	/V1.5/
	.SBTTL

	.ENABL	LC,GBL
;
;
;		      COPYRIGHT (C) 1981 BY
;		DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
;
;
; MODULE:	FMS Field Primitives Error Messages
;
; VERSION:	V1.5
;
; AUTHOR:	Cheryl Vedoe
;
; DATE:		12-November-81
;
;

;
; Define the PSECT for the error text.
;

	.PSECT	FMSERR,D

;
; Define the error symbol to indicate this is the error module.
;

	FMS$E	= 1

;
; Initialize the error message number.
;

	.ER.N	= 1

;-
;+
; ERROR
;
;	Define the error macro.
;
;	There are two definitions for the error macro, one for the
;	source and one for the error module. To determine which form
;	of the macro is appropriate, it is assumed the symbol FMS$E
;	is equal to 1 in the error module and equal to 0 in all other
;	modules which invoke the error macro.
;

	.MACRO	ERROR	MSG

.IF	EQ,FMS$E			; If not error module

;
;	Process keyboard error.
;
; 	Ring the bell and output the error message to the last line
;	if a message is	associated with the error; otherwise, ring
;	the bell and clear the last line.
;
;	All registers preserved.
;

	JSR	R3,ERROR
	.IRP	N,\.ER.N
	.WORD	FMSE'N
	.ENDM
	.ER.N	= .ER.N + 1

.IFF					; If error module

;
; Assemble the error message in the error module.
;

	.PSECT	FMSERR
	.IRP	N,\.ER.N
FMSE'N::
	.ENDM
	.ASCIZ	\MSG\
	.ER.N	= .ER.N + 1

.ENDC					; EQ,FMS$E

	.ENDM	ERROR

;-
;+
; ERROR
;
	ERROR	<>
;
; Cannot echo character in current position.
;-
;+
; ERROR
;
	ERROR	<>
;
; Changing to insert mode is illegal for the current field.
;-
;+
; ERROR
;
	ERROR	<>
;
; Changing to overstrike mode is illegal for the current field.
;-
;+
; ERROR
;
	ERROR	<NON-DISPLAYABLE CHARACTER>
;
; No validation is required in the current position. However, the 
; character entered cannot be displayed and therefore is invalid.
;-
;+
; ERROR
;
	ERROR	<ALPHABETIC REQUIRED>
;
; An alphabetic character (A-Z,a-z,'space') is required in the
; current position.
;-
;+
; ERROR
;
	ERROR	<NUMERIC REQUIRED>
;
; A numeric character (0-9) is required in the current position.
;-
;+
; ERROR
;
	ERROR	<ALPHANUMERIC REQUIRED>
;
; An alphabetic or numeric character is required in the current position.
;-
;+
; ERROR
;
	ERROR	<SIGNED NUMERIC REQUIRED>
;
; A valid signed numeric character (0-9 . - + ,) is required in
; the current position.
;-
;+
; ERROR
;
	ERROR	<>
;
; Cursor right is illegal.
;- 
	.DSABL	LSB
;+
; ERROR
;
	ERROR	<>
;
; Cursor left is illegal.
;-
;+
; ERROR
;
	ERROR	<>
;
; Delete character is illegal.
;-

.END
