.INCLUDE /CMN:COMMON/
.INCLUDE /CMN:KERNEL/
.INCLUDE /CMN:KBDEF/
TITLE	PDVVEC,<Port driver default vector table>,0A,10-MAY-91,KPH/DRP

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	PDVVEC EDIT HISTORY

;+
;
;  000  KPH  10-Jul-87	Creation in the dark
;
;			[RSTS/E V9.7]
;  001	DRP  07-Dec-88	Added "Disable line" entry along with "Set break",
;			"Clear break" and "Get line status".
;
;			[RSTS/E V10.0]
;  002	DRP  20-Nov-89	Add "Connect" and "Disconnect".
;-

.SBTTL	Define our .PSECTs

	ORG	PDVVEC

.SBTTL	Define our .MACROs

.MACRO	PRTDSP	EPT,WHERE
.=PDVVEC+<KP$'EPT'-120000>
	 .WORD	WHERE
.GLOBL	WHERE
.ENDM	

.SBTTL	Define the default dispatch table

	ORG	PDVVEC

	.BLKW0	<<<KP$MAX-120000>/2>-1>,0 ; Initialize table with zeroes

	PRTDSP	OUT,TTSTOR	;Set up standard output routine
	PRTDSP	SRT,RTSPC	;Nothing to do on startup
	PRTDSP	SUO,RTSPC	;Nothing to do to suspend output
	PRTDSP	SUI,SETFLO	;Suspend input - set flow control
	PRTDSP	RSI,SETFLO	;Resume input - set flow control
	PRTDSP	ABT,RTSPC	;Nothing to do to abort output
	PRTDSP	DTR,RTSPC	;Nothing to do to set DTR
	PRTDSP	PRM,RTSPC	;No line parameters to set
	PRTDSP	SEC,RTSPC	;No once a second service
	PRTDSP	ERL,RTSPC	;No special error logging
	PRTDSP	DSB,RTSPC	;Nothing to do to disable a line	;001
	PRTDSP	SBK,RTSPC	;Nothing to do to set break on a line	;001
	PRTDSP	CBK,RTSPC	;Nothing to do to clear break in a line	;001
	PRTDSP	LST,RTSPC	;Nothing to do to get line status	;001
	PRTDSP	CON,RTSPC	;Nothing to do to connect		;002
	PRTDSP	DSC,RTSPC	;Nothing to do to disconnect		;002

.END
