TITLE	CMNDEF,<Common definition for OMS/OMSMGR>,0A,10-MAY-91,DBM

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	CMNDEF Edit History
;+
; EDIT	BY	DATE		REASON
; 000	DBM	11-Jan-90	Creation
;-

;+
; Constants:
;
OSCMAX	=: 127.			; Highest keyboard # on RSTS/E systems
REQMAX	=: 9999.		; Highest request sequence # assigned
REQSIZ	=: 500.			; Maximum length of request text
PTCL.V	=: 100.			; Protocol version (10.0)
PTCL.R	=: 'I			; Revision level (I)
OMSLOT	=: 11.			; OMS Local object type

	.DSECT			; ORP command values
OC.NOP:	.BLKB			; No-Operation
OC.REP:	.BLKB			; Reply
OC.REQ:	.BLKB			; Request
OC.SET:	.BLKB			; Set Operator services
OC.STP:	.BLKB			; Stop Operator services
OC.BAD:				; First invalid command value

	.DSECT			; ORP command field values
	.BLKB			; (0 is reserved)
OC$TXT:	.BLKB			; Request/reply text
OC$SEQ:	.BLKB			; Request sequence #
OC$REP:	.BLKB			; /[NO]REPLY field
OC$FAC:	.BLKB			; /FACILITY field
OC$ML:	.BLKB			; Message level field
OC$ABO:	.BLKB			; /[NO]ABORT field
OC$BAD:				; First invalid field value

	.PSECT	CMNDEF,RW,D,GBL,REL,OVR
CMNDEF:				; MAP (CMNDEF)
JUNK:	.BLKW			; Junk word
FQB:	.BLKB	40.		; SYS call work area
PPN:	.BLKW			; [p,pn] of running job
BITVAL:	.BLKW	16.		; BITVAL(15%) array
DEBUG:	.BLKW			; Debugging flag
SEND:	.BLKW			; [NO]send flag
KB.WID:	.BLKW			; Keyboard width
SYS.CH:	.BLKW			; Channel # for work file
OUT.CH:	.BLKW			; Channel # for output file
LOG.CH:	.BLKW			; Channel # for log file
JOB.NO:	.BLKB			; Current job #
KB.NO:	.BLKB			; Current KB #

	.PSECT	OMSINT,RW,D,GBL,REL,OVR
OMSINT:				; MAP (OMSINT)
OMSDAT:	.BLKW			; Date package was last started
OMSTIM:	.BLKW			; Time package was last started
OMSACT:	.BLKB	4		; Date/Time package was last modified
OMSFAC:	.BLKB	6		; Facility/receiver name of package
OMSVER:	.BLKB			; OMS version identifier
OMSREV:	.BLKB			; OMS revision level
OMSRTN:	.BLKB	6		; Not used (Receiver name)
OMSCTX:	.BLKW			; Not used (Return context)
OMSREM:	.BLKW			; Not used (Reminder index)
OMSLEN:	.BLKW			; Length of package name
OMSFLG:	.BLKW			; Not used (Request flags)
OMSNUM:	.BLKW			; Not used (Next Sequence # ????)
OMSSTS:	.BLKB			; Current /KEEP status
OMSTYP:	.BLKB			; Not used (Request type)
OMSJOB:	.BLKB			; Not used (OMS Job # ???)
OMS.KB:	.BLKB			; Not used (OMS KB # ???)
OMSPPN:	.BLKW			; Not used (OMS [p,pn] ???)
HDRSIZ	=: .-OMSINT
OMSTXT:	.BLKB	REQSIZ		; Package name ("Operator/Message Services")
RECSIZ	=: .-OMSINT		; Size of request record

	.PSECT	OMSREQ,RW,D,GBL,REL,OVR
OMSREQ:				; MAP (OMSREQ)
REQDAT:	.BLKW			; Date of request (RSTS/E format)
REQTIM:	.BLKW			; Time of request (RSTS/E format)
REQACT:	.BLKB	4		; Date/Time of next action
REQFAC:	.BLKB	6		; Facility of request
REQVER:	.BLKB			; OMS version identifier
REQREV:	.BLKB			; OMS revision level
REQRTN:	.BLKB	6		; Return address (Receiver name)
REQCTX:	.BLKW			; Return context
REQREM:	.BLKW			; Reminder index
REQLEN:	.BLKW			; Length of request text
REQFLG:	.BLKW			; Request flags
REQNUM:	.BLKW			; Sequence #
REQSTS:	.BLKB			; Request status
REQTYP:	.BLKB			; Request type
REQJOB:	.BLKB			; Job # of requestor
REQ.KB:	.BLKB			; KB # of requestor
REQPPN:	.BLKW			; [p,pn] of requestor
HDRSIZ	=: .-OMSREQ
REQTXT:	.BLKB	REQSIZ		; Text of request
RECSIZ	=: .-OMSREQ		; Size of request record

	.BSECT			; Flag bits (REQ.FLG)
FLGOPR:	.BLKB	.		; Reply is by user/operator
FLGBEL:	.BLKB	.		; Broadcast should include <BEL> character

	.BSECT			; Status bits (REQ.STS)
STSPEN:	.BLKB	.		; Pending reply
STSABO:	.BLKB	.		; Aborted reply
STSANS:	.BLKB	.		; Answered reply
STSMSK	=: .-1			; Status mask

	.BSECT			; Message level bits (REQ.TYP, OMS.STS)
ML.MSG:	.BLKB	.		; Message level = MESSAGES
ML.REQ:	.BLKB	.		; Message level = REQUESTS
ML.ALL	=: .-1			; Flag for Message level = ALL
ML.REP:	.BLKB	.		; Reply record flag
ML.MSL	=: .-1			; Message level mask

