;
;	OMSMGR.CMD
;
;	COPYRIGHT (c) 1974, 1988
;	DIGITAL EQUIPMENT CORP., MAYNARD, MASS.
;
;	TKB command file to build OMSMGR.TSK V10.0
;
;	Build using:
;
;		CUSP resident library CSPLIB
;		RMS  resident library RMSRES
;
SYSTEM:OMSMGR,LST:OMSMGR/MA/CR/-SP=SYSTEM:OMSMGR/MP
TASK=OMSMGR
ACTFIL=3
UNITS=3
RESLIB=LB:CSP100/RO
EXTTSK=512
//
