!
!	Modified 30-Jan-86 by Vogel - change to V9 batch format
ASSIGN SY: SY
ASSIGN SY: DK
SWITCH RT11
R SY:PIP
RTS0.BAK=RC.OBJ,EC.OBJ,SC.OBJ,SU.OBJ
RTS1.BAK=TR.OBJ,ED.OBJ,RX.OBJ
RTS.OBJ/NEWFILE=RTS0.BAK,RTS1.BAK
*.BAK/DE/LOG
$
