TITLE	MA2F,<2-WORD MATH WITH FPU>,08,13-MAY-86,MHB/JDM

;                   Copyright 1974,1990 by Digital Equipment Corporation
;                                  All rights reserved.
;
;          This software is furnished under a license and may be used and copied
;          only  in  accordance  with  the  terms  of  such license and with the
;          inclusion of the above copyright notice.  This software or any copies
;          shall not be provided to any other person.   No title to or ownership
;          of the software is hereby transferred.
;
;          The information in this software is subject to change without notice.
;
;          DIGITAL  assumes  no  responsibility  for the  use, functionality, or
;          reliability of its  software  on equipment  which  is not supplied by
;          DIGITAL.

.SBTTL	PARAMETERS FOR FPU 2-WORD MATH PACKAGE

FLTLEN	=	2
.MATH.	=	0
FPU	=	1
FPV	=	1
F0	=	%0
F1	=	%1
F2	=	%2
F3	=	%3
F4	=	%4
F5	=	%5
;NO FIS

