TITLE	RX,<RUN-TIME MESSAGES>,08,13-MAY-86,TPH/JDM

;                   Copyright 1974,1990 by Digital Equipment Corporation
;                                  All rights reserved.
;
;          This software is furnished under a license and may be used and copied
;          only  in  accordance  with  the  terms  of  such license and with the
;          inclusion of the above copyright notice.  This software or any copies
;          shall not be provided to any other person.   No title to or ownership
;          of the software is hereby transferred.
;
;          The information in this software is subject to change without notice.
;
;          DIGITAL  assumes  no  responsibility  for the  use, functionality, or
;          reliability of its  software  on equipment  which  is not supplied by
;          DIGITAL.

.SBTTL	***** WARNING, THIS SOURCE CONTAINS LOWER CASE CHARACTERS
.SBTTL					

	.ENABL	LC

	DEFORG	RX

	.GLOBL	CRLF0,ASKNEW,ASKOLD,ASKNAM,READYM
	.GLOBL	PROMPT,ATLINE,KSIZEM
	.GLOBL	BYEM,STR$LI,FTLERM

.MACRO	STR$	LABEL,STRING
	.EVEN
$$$$$$	=	.
	.ASCII	STRING
$$$$$0	=	.
	.EVEN
.LIST
LABEL	=	.-2		;LINK TO NEXT IS UNUSED
.NLIST
	.WORD	$$$$$$-LABEL	;SELF-RELATIVE PTR TO STRING
	.WORD	$$$$$0-$$$$$$	;LENGTH OF STRING
.ENDM	STR$

;STR$	STR$IN,<"$INIT">	;Removed 90.2.12  WJS

STR$	STR$LI,<"$LOGIN">

;STR$	STR$LO,<"$LOGOUT">	;Removed 90.2.12  WJS

KSIZEM:	.ASCII	"K of memory used"
CRLF0:	.BYTE	15,12,00

ASKNEW:	.ASCIZ	"New"

ASKOLD:	.ASCIZ	"Old"

ASKNAM:	.ASCIZ	" file name--"

..RDY.	== .
READYM:	.BYTE	15,12
	.ASCII	"Ready"
	.BYTE	15,12,12,00

PROMPT:	.ASCIZ	"? "

ATLINE:	.ASCIZ	" at line"

BYEM:	.BYTE	15,12
	.ASCII	"Bye"
	.BYTE	15,12,12,00

FTLERM:	.ASCIZ	"?Error text lookup failure"

	.EVEN

	.END

