; PATASM.CMD
;
; MAC COMMAND FILE TO ASSEMBLE PATCH (PAT.TSK) MODULES
;
SYSTEM:BLGSD,LST:BLGSD/CR/-SP=RSX:COMMON,PAT:MACFLM,BLGSD
SYSTEM:CMLIO,LST:CMLIO/CR/-SP=RSX:COMMON,PAT:MACFLM,CMLIO
SYSTEM:EDGSD,LST:EDGSD/CR/-SP=RSX:COMMON,PAT:MACFLM,EDGSD
SYSTEM:GTBYT,LST:GTBYT/CR/-SP=RSX:COMMON,PAT:MACFLM,GTBYT
SYSTEM:INIDM,LST:INIDM/CR/-SP=RSX:COMMON,PAT:MACFLM,INIDM
SYSTEM:MRGFL,LST:MRGFL/CR/-SP=RSX:COMMON,PAT:MACFLM,MRGFL
SYSTEM:OBSCN,LST:OBSCN/CR/-SP=RSX:COMMON,PAT:MACFLM,OBSCN
SYSTEM:OPNFL,LST:OPNFL/CR/-SP=RSX:COMMON,PAT:MACFLM,OPNFL
SYSTEM:PATBL,LST:PATBL/CR/-SP=RSX:COMMON,PAT:MACFLM,PATBL
SYSTEM:PATCH,LST:PATCH/CR/-SP=RSX:COMMON,PAT:MACFLM,PATCH
SYSTEM:PATER,LST:PATER/CR/-SP=RSX:COMMON,PAT:MACFLM,PATER
SYSTEM:PATIN,LST:PATIN/CR/-SP=RSX:COMMON,PAT:MACFLM,PATIN
SYSTEM:PATIO,LST:PATIO/CR/-SP=RSX:COMMON,PAT:MACFLM,PATIO
SYSTEM:PTALO,LST:PTALO/CR/-SP=RSX:COMMON,PAT:MACFLM,PTALO
SYSTEM:PTCRF,LST:PTCRF/CR/-SP=RSX:COMMON,PAT:MACFLM,PTCRF
SYSTEM:PTSCN,LST:PTSCN/CR/-SP=RSX:COMMON,PAT:MACFLM,PTSCN
SYSTEM:PTSRC,LST:PTSRC/CR/-SP=RSX:COMMON,PAT:MACFLM,PTSRC
SYSTEM:SCRLD,LST:SCRLD/CR/-SP=RSX:COMMON,PAT:MACFLM,SCRLD
SYSTEM:SRCMN,LST:SRCMN/CR/-SP=RSX:COMMON,PAT:MACFLM,SRCMN
