;
; TKB .CMD FILE FOR PAT
; ON A MAPPED RSX-11M SYSTEM
; USING SYSLIB
; CREATED BY SGNBLDBLD.CMD VERSION 1.62
;
SYSTEM:PAT/FP/CP/MM,PAT/MA/CR/-SP,PAT=
PAT:PATBLD/MP
TASK=...PAT
STACK=128
UNITS=4
ASG=TI:1
ASG=TI:2
PAR=GEN:0:40000
EXTSCT=$$ERB0:100
TSKV=$ERVCT:10
GBLDEF=$CDDMG:0
@PAT:PATGBL.CMD
//
