; PATCRF.CMD
;
; CRF COMMAND FILE TO CROSS REFERENCE PATCH (PAT.TSK) MODULES
;
LST:BLGSD.LST/-SP
LST:CMLIO.LST/-SP
LST:EDGSD.LST/-SP
LST:GTBYT.LST/-SP
LST:INIDM.LST/-SP
LST:MRGFL.LST/-SP
LST:OBSCN.LST/-SP
LST:OPNFL.LST/-SP
LST:PATBL.LST/-SP
LST:PATCH.LST/-SP
LST:PATER.LST/-SP
LST:PATIN.LST/-SP
LST:PATIO.LST/-SP
LST:PTALO.LST/-SP
LST:PTCRF.LST/-SP
LST:PTSCN.LST/-SP
LST:PTSRC.LST/-SP
LST:SCRLD.LST/-SP
LST:SRCMN.LST/-SP
