; LBRLIB.CMD
;
; LBR COMMAND FILE FOR ENTERING ALL THE PAT MODULES INTO PAT.OLB
;
SYSTEM:PAT.OLB/CR:44.:0.:19.:OBJ
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:BLGSD
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:CMLIO
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:EDGSD
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:GTBYT
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:INIDM
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:MRGFL
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:OBSCN
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:OPNFL
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PATBL
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PATCH
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PATER
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PATIN
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PATIO
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PTALO
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PTCRF
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PTSCN
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:PTSRC
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:SCRLD
SYSTEM:PAT.OLB/RP/-EP=SYSTEM:SRCMN
