.IIF	NDF	L$$IST,	.NLIST
.IIF	NDF	L$$IST,	.DSABL	CRF
TITLE	CHECK,<Check CONFIG Parameters>,0B,21-JUN-91,MHB/SJK/JTC/RTW/GPK/RRF/MND/AJK/WJS/TPT/PRL/MNB/FRL/JHC/DBM/KPH/DWF/PJH/DSD/FEK

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	Edit History for Check
;+
;
;  000	RRF  06-MAR-81	CREATION - COPIED FROM V7.0-07
;  001	TG   27-Jun-80	Added NAMDIR default
;  002	JTC  09-Jun-80	Globalized PKSTKB for UU.SYS
;  003	RTW  19-Aug-80	Added check for DMP/DMV
;  004	RTW  21-Aug-80	Reorder check for DMP/DMV
;  005	GPK  16-Feb-81	Added XPEEK and DDCU stuff
;  006	TG   17-Feb-81	Added defaults for terminal sevice stuff
;  007  GPK  15-Apr-81	Added DDCU stuff for XM
;  008  RRF  14-Jun-81	Added alternate phase capability for L3Q bits
;  009  RVR  15-Jun-81	Fixed DMC(XM) and DMP(XD) DDB sizes
;  010	GPK  10-Aug-81	Yet another DDB size change
;  011	GPK  12-AUG-81	Changed LP default width to 132.
;  012	GPK  06-Aug-81	Changed DMC/DMP DDB size
;  013  MND  14-OCT-81  Corrected 007 (DDCU)
;  014  AJK  13-Jan-82  Added DU to disk name list
;  015  WJS  19-Oct-82	Added defaults for EMT Logger and CNTRLT;
;                          added check for CNT.DU
;
;			[RSTS V9.0]
;  016  TPT  18-Apr-83	Removed 2741/DC11 specific code
;  017  TPT  28-Jun-83	Preliminary DHV11 support	
;  018	PRL  21-Nov-83	Update LP's DDB size for 32-bit line counter
;  019	MNB  22-Nov-83	Replaced DC with DV in disk NAME macro
;  020  FRL  23-Nov-83  Added extended L3Q capability
;  021  FRL  09-Jan-84  Deleted TU58 macro
;  022  JHC  10-May-84	Increase MS DDB size for multiqueuing driver
;  023	GPK  11-May-84	Add QKBTIC; update XM, XD DDB sizes
;			Generate DDCU table entries for KB:
;  024	JHC  19-Jun-84  Enlarge DDS.MS to accomodate DDB which
;			enables infinite I/O to MSDVR.
;
;			[RSTS V9.1]
;  025	DBM  17-May-84	TMSCP changes
;  026	DBM  28-Aug-85	Put MSCP disk rounding back in for now
;  028	TPT  15-Sep-85	Increase size of MU DDBs
;
;			[RSTS/E V9.3]
;  029	JHC  31-Oct-85	DEUNA/DEQNA modifications
;  030  KPH  27-Mar-86	Update size of DECnet DDBs
;  031	DWF  12-May-86	Update size of XD DDBs
;  032  KPH  04-Aug-86	Update size of XM DDBs
;  033	DBM  26-Aug-86	4 QNA's.  Increase size of XH/XE DDB's
;
;			[RSTS/E V9.4]
;  034	PJH  09-Feb-87	Add DZ, DW disks for GPK, add GPK term dvr checks
;  035	PJH  02-Mar-87	Add dummy CNT.DW, CNT.DZ counts of 0
;
;			[RSTS/E V9.6]
;  036  KPH  13-Oct-87	Removed L3Q definitions for KB devices
;			Changed KB DDB definitions for INIT creation
;			Changed PK DDB definitions for INIT creation
;  037	DSD  08-Feb-88	Add NO DDB definitions for INIT creation
;  038	DSD  09-Feb-88	Don't allow NO device to be control/C interruptable
;
;			[RSTS/E V10.0]
;  039	DSD  22-Jun-89	Add NO DDB creation
;  040  BGN  01-Jun-90  Allow NO device to be control/C interruptable
;
;			[RSTS/E V10.1]
;  041	FEK  10-Dec-90	Remove unnecessary calls to DEVL3Q
;-

	.SBTTL
; Device naming macros

.MACRO	$DISKS	Z
Z'.IRP	NAME,<DV,DF,DS,DK,DL,DM,DP,DR,DB,DZ,DW,DU>			;034
.ENDM	$DISKS

.MACRO	$NAMES	LAB,RAB,Z
Z'.IRP	NAME,<LAB'SY'RAB>
.ENDM	$NAMES

.MACRO	DEVL3Q	NN,ITEM,APR						;020
.IF	NB	<APR>							;020
	L3QENT	Q'NN''ITEM,ITEM'$'NN,APR'AP5				;020
.IFF									;020
	L3QENT	Q'NN''ITEM,ITEM'$'NN,NN'DAP5				;020
.ENDC									;020
.GLOBL	ITEM'$'NN							;020
.ASECT									;020
.ENDM	DEVL3Q								;020

.MACRO	DEVICE	NN,AN,L3QBITS,APR,ZZ,PHASE
.DSABL	CRF
$$$$$$	=	1
$DISKS
.IIF	IDN	<NN>,<NAME>,	.ERROR ; Device NN: already defined as a disk
.IIF	IDN	<AN>,<NAME>,	$$$$$$ = 0
ZZ'.ENDM
$NAMES
.IIF	IDN	<NN>,<NAME>,	.ERROR ; Device NN: already defined
.IIF	IDN	<AN>,<NAME>,	$$$$$$ = 0
ZZ'.ENDM
$NAMES	^!^%NAME,<LAB'!,^!,NN''RAB>%!
.MACRO	$NAMES	LAB,RAB,Z
Z'.IRP	NAME
.ENDM	$NAMES
ZZ'.ENDM
.IF	NB	<AN>
.IF	NE	$$$$$$
ALT.'NN	=	"AN
.ENDC
.ENDC
.MACRO	L3Q$'NN
.IF	B	<PHASE>
.IRP	ITEM,<L3QBITS>
DEVL3Q	NN,ITEM
.ENDM
.ENDC
.ENDM	L3Q$'NN
.ENABL	CRF
.ENDM	DEVICE

.MACRO	COUNT	DV,CNTRLS
CTL.'DV	=	CNTRLS
CNT.'DV	=	0
$$$$$$	=	0
.REPT	CNTRLS
.RADIX	10
.IRP	N,<\$$$$$$>
.RADIX	8
CNT.'DV	=	CNT.'DV+DV''N'UN
.ENDM
$$$$$$	=	$$$$$$+1
.ENDR
.ENDM	COUNT

.IIF	NDF	QBUSRJ, QBUSRJ=0	; Assume no DUV11 RJ2780

.IIF	NDF	JSTATS,	JSTATS=0	; Assume no job statistics
.IIF	NDF	DSTATS,	DSTATS=0	; Assume no disk statistics
.IIF	NDF	QSTATS,	QSTATS=0	; Assume no queue statistics
.IIF	NDF	EMTLOG, EMTLOG=0	; Assume no EMT logging		; 015

.IIF	NDF	CNT.DW, CNT.DW==0	; Assume no GPK devices		;035
.IIF	NDF	CNT.DZ, CNT.DZ==0	; Assume no GPK devices		;035

.IIF	NDF	L$$IST,	.ENABL	CRF
.IIF	NDF	L$$IST,	.LIST

; Required devices
; ORDER MUST BE RETAINED. or all of the nice little DEV tables in TBL
; will start ignoring reality.

DEVICE	KB,TT				; Terminals			;036

CTL.KB	=	<TTINTM/2>-1 ; Set up number of controllers		;036
CNT.KB	=	128.	; Make enough room for 128 terminals		;036
;DDS.KB	=		; DDB set up by INIT				;036
CCC.KB	=	1	; Device is control/C interruptable
SLP.KB	=	1	; Device checking needed before "sleep"

DEVICE	NL		; Null device
CNT.NL	=	1.	;  only NL0: please
DDS.NL	=	10	;  10 byte DDB's
CCC.NL	=	0	;  device is not control/C interruptable

DEVICE	PK		; Pseudo-keyboards
;CNT.PK	=		; Count set up in INIT
;DDS.PK	=		; DDB set up in INIT				;036
CCC.PK	=	1	;  device is control/C interruptable
SLP.PK	=	1	;  device checking needed before "sleep"

DEUNA	==	4	; Define Four DEUNA's for every system		;029
DEQNA	==	4	; And four DEQNA's for every system		;033

.IF	NE	DEUNA

DEVICE	XE		; UNIBUS Ethernet network adapter		;029
$$$$$$	=	0
.REPT	DEUNA		;  Each DEUNA has a 'fake' circuit		;029
.RADIX	10
.IRP	N,<\$$$$$$>
.RADIX	8
XE'N'UN	=	1
.ENDR
$$$$$$	=	$$$$$$+1
.ENDR
COUNT	XE,DEUNA	;  set up CNT.XE and CTL.XE
DDS.XE	=	110	;  100 byte DECnet standard DDB + 10 bytes	;033
CCC.XE	=	1	;  Device is control/C interruptable		;029
SLP.XE	=	1	;  Check device before "sleep"			;029
UMR.XE	=	1	;  Device manipulates UMRs (yes, but we MERGE in) ;029

.ENDC

.IF	NE	DEQNA

DEVICE	XH		; QBUS Ethernet network adapter			;029
$$$$$$	=	0
.REPT	DEQNA		;  Each DEQNA has a 'fake' circuit		;029
.RADIX	10
.IRP	N,<\$$$$$$>
.RADIX	8
XH'N'UN	=	1
.ENDR
$$$$$$	=	$$$$$$+1
.ENDR
COUNT	XH,DEQNA	;  set up CNT.XH and CTL.XH			;029
DDS.XH	=	110	;  100 byte DECnet standard DDB + 10 bytes	;033
CCC.XH	=	1	;  Device is control/C interruptable		;029
SLP.XH	=	1	;  Check device before "sleep"			;029

.ENDC

DEVICE	NO,,<DNE>	; NO pseudo-driver				;037
CNT.NO	=	1	; NO hasn't any real controllers but say 1	;037
DDS.NO	=	242	;  242 byte DDB's (DDB never used)		;039
CCC.NO	=	1	;  device is control/C interruptable		;040
SLP.NO	=	1	;  device checking needed before "sleep"	;037
									;037
; End of order dependant required devices.
; Optional Devices

.IF	NE	RJ2780

DEVICE	RJ,,<IDL>	; 2780 remote job entry
CNT.RJ	=	1.	;  only RJ0: please
DDS.RJ	=	14	;  14 byte DDB's
CCC.RJ	=	0	;  device is not control/C interruptable

.ENDC

.IF	NE	DMC11

DEVICE	XM,,<DNE>	; DDCMP NPR line interface
$$$$$$	=	0
.REPT	DMC11		;  each DMC controller gets one circuit
.RADIX	10
.IRP	N,<\$$$$$$>
.RADIX	8
XM'N'UN	=	1
.ENDR
$$$$$$	=	$$$$$$+1
.ENDR
COUNT	XM,DMC11	;  set CNT.XM and CTL.XM
DDS.XM	=	206	;  206 byte DDB's				;032
CCC.XM	=	1	;  device is control/C interruptable
SLP.XM	=	1	;  device checking needed before "sleep"

.ENDC

.IF	NE	DMP11

DEVICE	XD,,<DNE>	; DDCMP NPR multi-drop line interface
COUNT	XD,DMP11	;  set CNT.XD and CTL.XD
DDS.XD	=	230	;  230 byte DDB's				;031
CCC.XD	=	1	;  device is control/C interruptable
SLP.XD	=	1	;  device checking needed before "sleep"

.ENDC

.IF	NE	LP11

DEVICE	LP		; Line printer
CNT.LP	=	LP11	;  # of printers
DDS.LP	=	46	;  46 byte DDB's (aux proc assisted)		;018
CCC.LP	=	1	;  device is control/C interruptable
BFQ.LP	=	20.	;  buffer quota
HOR.LP	=	132.	;  horizontal width

.ENDC

.IF	NE	PR11

DEVICE	PR		; Paper tape reader
CNT.PR	=	PR11	;  # of readers
DDS.PR	=	20	;  20 byte DDB's
CCC.PR	=	1	;  device is control/C interruptable
BFQ.PR	=	10.	;  buffer quota

.ENDC

.IF	NE	PP11

DEVICE	PP		; Paper tape punch
CNT.PP	=	PP11	;  # of punches
DDS.PP	=	20	;  20 byte DDB's
CCC.PP	=	1	;  device is control/C interruptable
BFQ.PP	=	10.	;  buffer quota

.ENDC

.IF	NE	CR11

DEVICE	CR		; Column interrupt card reader
CNT.CR	=	CR11	;  # of readers
DDS.CR	=	262	;  262 byte DDB's
CCC.CR	=	1	;  device is control/C interruptable

.ENDC

.IF	NE	CD11

DEVICE	CD,CR		; NPR card reader
CNT.CD	=	CD11	;  # of readers
DDS.CD	=	262	;  262 byte DDB's
CCC.CD	=	1	;  device is control/C interruptable

.ENDC

.IF	NE	TM11

DEVICE	MT,,<CON,DNE>	; TU10/TE10/TS03 magtape
CNT.MT	=	TM11	;  # of drives
DDS.MT	=	46	;  46 byte DDB's
CCC.MT	=	0	;  device is not control/C interruptable
UMR.MT	=	1	;  device handles UNUBUS map entries

.ENDC

.IF	NE	TM02

DEVICE	MM,MT,<CON,DNE>	; TU16/TE16/TU45 magtape
CNT.MM	=	TM02	;  # of drives
DDS.MM	=	46	;  46 byte DDB's
CCC.MM	=	0	;  device is not control/C interruptable
UMR.MM	=	1	;  device handles UNIBUS map entries

.ENDC

.IF	NE	TS11

DEVICE	MS,MT,<DNE,CON>	; TS11 magtape
CNT.MS	=	TS11	;  # of drives
DDS.MS	=	134	;  134 byte DDB's				;024
CCC.MS	=	0	;  device is not control/C interruptable
UMR.MS	=	1	;  device handles UNIBUS map entries

.ENDC

;025+
.IF	NE	TMSCP

DEVICE	MU,MT,<DNE>	; TMSCP tapes					;041
CNT.MU	=	TMSCP	;  # of drives
DDS.MU	=	56	;  54 byte DDB's				;028
CCC.MU	=	0	;  Device is not control/C interruptable
UMR.MU	=	1	;  Device handles UNIBUS map entries

.IFF

CNT.MU	=	0	; No TMSCP support

.ENDC
;025-

.IF	NE	TC11

DEVICE	DT,,<FIP,DNE,RES> ; DECtape
CNT.DT	=	TC11	;    # of drives
DDS.DT	=	40	;    40 byte DDB's
CCC.DT	=	0	;    device is not control/C interruptable

.ENDC

.IF	NE	RX11

DEVICE	DX,DY,<CON>	; Floppy disk
CNT.DX	=	RX11	;  # of drives
DDS.DX	=	34	;  34 byte DDB's
CCC.DX	=	0	;  device is not control/C interruptable
UMR.DX	=	1	;  device handles UNIBUS map entries

.ENDC

.IF	NE	II11

DEVICE	II		; IBM interface DUP-11
CNT.II	=	II11	;  # of drives
DDS.II	=	24	;  24 byte DDB's
CCC.II	=	1	;  device is control/C interruptable
SLP.II	=	1	;  device needs check for sleep

.ENDC

.IF	NE	KMC11

DEVICE	XK		; KMC-11 micro-processor
CNT.XK	=	KMC11	;  # of drives
DDS.XK	=	46	;  46 byte DDB's
CCC.XK	=	0	;  device is not control/C interruptable

.ENDC

.IIF DF CNT.DU	CNT.DU = <CNT.DU+3>/4*4	;Make MSCP disks a mutilple of 4 ;026
