.INCLUDE	%CMN:COMMON%
.INCLUDE	%CMN:KERNEL%
.INCLUDE	%EDV:XEDEF%
TITLE	XEDINT,<PMM segment of the UNA driver>,0A,10-MAY-91,KPH/DBM/JHC

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	EDIT HISTORY FOR XEDINT
;+
;
;  000	JHC 14-Jun-85	CREATION -- copied from old napkins
;  001	JHC 04-Nov-86	Make sure ERLDVR resolves to PMM segment,
;			and require DEVICE priv to open/assign.
;
;-



	DEFORG	XEDVR

	DEFORG	XEDCTL

	DEFORG	XEDINT

INCLUDE	<ERLDVR>							;001



; Define 'DDSTS' value for UNA

STS.XE	==	DDPRVO/400
		;special flag
		; DEVICE privilege needed to open/assign this		;001

; Define flags for UNA

FLG.XE	==	FLGFRC!DDNFS!ETHHND!FLGMOD
		;Call it Byte Oriented to straighten out LPs
		;Non-file structured
		;Ethernet device index
		;Device Accepts Modifiers

; Define width

SIZ.XE	==	5*14.+1
		;Default for "NO WIDTH"

; Define default buffer size

BUF.XE	==	512.
		;Default buffer is 512. bytes.
			;Maximum buffer is 1514. bytes
			;Minimum buffer is 60. bytes



;+
; Define Extent of XEDCTL region
;-

	TMPORG	XEDCTL

XECORE:: .BLKB0	XESIZ	;set up the XEDCTL region...

	UNORG



XEDINT:	CALLX	INTSAV,R5
	  .WORD	1200		;Actual APR5 value filled in
	  .WORD	0		;Entry for interrupt service filled in

ERL$XE::JMP	@#0		;Entry for error logging filled in

UMR$XE::JMP	@#0		;Entry to UMR service filled in

.END
