$JOB/CCL/NOLIMIT [170,137]
$!
$! KCG	11-May-84	Add MSRSUB and DNEHLL to RT library
$!
ASSIGN LST: NL
ASSIGN NL: LST
DEASSIGN NL
ASSIGN D: SY
ASSIGN D: DK
ASSIGN <40>
ASSIGN D:[170,76] L
$SWITCH RT11
$R SY:PIP
*.BAK/DE:NOWARN/NOLOG
$R SY:MACRO
OVLHD,LST:OVLHD/C=OVLHD/N:TTM/L:CND:MEB
$R SY:PIP
TEMP.OBJ=RTLIB.OBJ/LO
$SIZE 20
$R SY:LIBR

SYSLIB/A,TT:=OVLHD,L:DNEHLL.RTO,L:MSRSUB.RTO
SYSLIB,TT:=SYSLIB,RTLIB
$EOJ
