$JOB/CCL/NOLIMIT/PRI:-16 [170,32]
$ASSIGN D: SY
$ASSIGN D: DK
$ASSIGN <40>
$SWITCH RT11
$SIZE 28
$R SY:LINK
ONLPAT.SV/Z,ONLPAT/W/A/N,ONLPAT=ONLPAT/X,ONLINE,[170,42]INIPAT/C
[170,42]SILNDX,[170,46]RSTSLB
$R SY:SILUS
ONLPAT.SAV/S,ONLPAT=ONLPAT.SV/N
ONLPAT
$R SY:PIP
ONLPAT.SV,ONLPAT.STB/DE/NOLOG
$EOJ
