; TKBCRF.CMD
;
; CRF COMMAND FILE TO CROSS REFERENCE THE TASK BUILDER (TKB.TSK) MODULES
;
; TASK BUILDER VERSION M32
;
; REG	25-JUL-87	UPDATED FOR LATEST RSX VERSION OF TKB FOR RSTS V9.5
; SEL 	24-Jun-91	UPDATED FOR LATEST RSX VERSION OF TKB FOR RSTS V10.1
;
LST:ACMOD .LST/-SP
LST:ADRSM .LST/-SP
LST:ADRST .LST/-SP
LST:ALALO .LST/-SP
LST:ALELD .LST/-SP
LST:ALSGD .LST/-SP
LST:BCNTL .LST/-SP
LST:BLDSG .LST/-SP
LST:BLMNT .LST/-SP
LST:CMLCL .LST/-SP
LST:CORAL .LST/-SP
LST:DKALO .LST/-SP
LST:DSALO .LST/-SP
LST:ERMSG .LST/-SP
LST:FNIT .LST/-SP
LST:GTBYT .LST/-SP
LST:GTCML .LST/-SP
LST:GTPPR .LST/-SP
LST:HEADR .LST/-SP
LST:INITL .LST/-SP
LST:IODAT .LST/-SP
LST:LMS1 .LST/-SP
LST:LMS2 .LST/-SP
LST:MLSG0 .LST/-SP
LST:MLSG1 .LST/-SP
LST:MLSG2 .LST/-SP
LST:MPONE .LST/-SP
LST:MPOUT .LST/-SP
LST:MPTWO .LST/-SP
LST:MULSG .LST/-SP
LST:NXTFL .LST/-SP
LST:PCTRL .LST/-SP
LST:PRCER .LST/-SP
LST:PRCLM .LST/-SP
LST:PRFND .LST/-SP
LST:P2CLB .LST/-SP
LST:P2CLS .LST/-SP
LST:P2LBR .LST/-SP
LST:P2OPT .LST/-SP
LST:P2POP .LST/-SP
LST:P2PRS .LST/-SP
LST:P3LBS .LST/-SP
LST:P3MDS .LST/-SP
LST:P3PRE .LST/-SP
LST:P4MAL .LST/-SP
LST:P5CEL .LST/-SP
LST:P5CLS .LST/-SP
LST:P5CRF .LST/-SP
LST:P5ELM .LST/-SP
LST:P5EOS .LST/-SP
LST:P5IMG .LST/-SP
LST:P5MAP .LST/-SP
LST:P5MDS .LST/-SP
LST:P5MEL .LST/-SP
LST:P6STB .LST/-SP
LST:RESLB .LST/-SP
LST:RSRCH .LST/-SP
LST:SCAN .LST/-SP
LST:SCVTR .LST/-SP
LST:SGALO .LST/-SP
LST:SGTBL .LST/-SP
LST:SLSRC .LST/-SP
LST:SNGSG .LST/-SP
LST:SRCINS .LST/-SP
LST:SRCIV .LST/-SP
LST:STFDB .LST/-SP
LST:STINP .LST/-SP
LST:STOPT .LST/-SP
LST:SYALO .LST/-SP
LST:TABLS .LST/-SP
LST:TASKB .LST/-SP
LST:VSECT .LST/-SP
LST:WSINI .LST/-SP
LST:WSRCC .LST/-SP
LST:WSRCS .LST/-SP
LST:WSRFS .LST/-SP
;
;CREF the Fast Taskbuilder (HFT.TSK) files
;
LST:EXTSKX.LST/-SP
LST:INIDMX.LST/-SP
LST:INIVSX.LST/-SP
LST:RDPASX.LST/-SP
LST:TASKBX.LST/-SP
LST:VMDATX.LST/-SP
