; VMUCRF.CMD
;
; CRF COMMAND FILE TO CROSS REFERENCE THE TASK BUILDER VIRTUAL MEMORY MODULES 
;
; TASK BUILDER VERSION M32
;
LST:ALBLK .LST/-SP
LST:ALSVB .LST/-SP
LST:ALVRT .LST/-SP
LST:CVRL  .LST/-SP
LST:CVRS  .LST/-SP
LST:EXTSK .LST/-SP
LST:FNDPG .LST/-SP
LST:GTCOR .LST/-SP
LST:GTCOS .LST/-SP
LST:INIDM .LST/-SP
LST:INIVM .LST/-SP
LST:INIVS .LST/-SP
LST:MRKPG .LST/-SP
LST:RDPAG .LST/-SP
LST:RDPAS .LST/-SP
LST:RQVCB .LST/-SP
LST:VMDAT .LST/-SP
LST:VMDAS .LST/-SP
LST:VMUTL .LST/-SP
;
;	PIP UTILITY ROUTINES
;
LST:GTKNM .LST/-SP
