; VMULIB.CMD
;
; LBR COMMAND FILE FOR ENTERING TASK BUILDER VIRTUAL MEMORY MODULES
;
SYSTEM:VMLIB.OLB/CR:259.:512.:19.:OBJ
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:ALBLK
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:ALSVB
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:ALVRT
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:CVRL
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:CVRS
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:EXTSK
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:FNDPG
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:GTCOR
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:GTCOS
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:INIDM
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:INIVM
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:INIVS
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:MRKPG
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:RDPAG
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:RDPAS
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:RQVCB
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:VMDAT
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:VMDAS
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:VMUTL
;	PIP UTILITY ROUTINES
;
SYSTEM:VMLIB.OLB/RP/-EP=SYSTEM:GTKNM
;

