.INCLUDE /SYSTEM:BCKPFX/
TITLE	BCKMSG,<Messages for BACKUP>,0A,13-MAY-91,BSB/KPH/GMB/FRL/BGN

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	Edit history for BCKMSG

;+
;
;  000	BSB  09-NOV-83	Creation for Version 9.0
;  001	KPH  12-Nov-84	Add message NORRGN
;  002	KPH  29-Nov-84	Add messages for /NOTELL; fix some messages
;			Add message for privilege check
;  003  KPH  07-Mar-85	These things we write are "Backup sets"
;			Add OPNINI
;  004  GMB  12-Apr-85	Added !~I to M.INF messages
;
;			[RSTS V9.1]
;  005  KPH  13-Jun-85	Remove BADDEN message
;  006  KPH  23-Aug-85	Add messages for BACKUP "phases"
;			Add BADPRO message
;			Add BADPRV message
;
;			[RSTS V9.2]
;  007  GMB  19-Sep-85	Changed all messages to use new CUIMSG format
;			Changed package number to 1 (in memory)
;  008  FRL  14-Feb-86	Fix warning in case of backup/verify
;
;			[RSTS V9.3]
;  009  KPH  22-Jan-86	Change CRC error message
;  010  FRL  28-Apr-86  Add installation messages and redefine /[NO]TELL
;
;			[RSTS V10.0]
;  011  BGN  26-Oct-89  New message for image mode
;  012  BGN  10-Nov-89	More new messages for image mode
;  013	REG  30-NOV-89	Merge /INIT code from GPK
;  014	REG  12-Dec-89	Add image volume dismount message
;  015	REG  08-Jan-90	Add error for PPN/filespecs with /IMAGE
;  016	REG  18-Feb-90	/REPLACE=ASSIST
;  017  REG  30-Mar-90	Add [NO]QUERY to /INIT=
;  018  REG  10-Feb-90	Add adaptive code for blocksize/regions
;  019  REG  17-APR-90	Add "_" to CLUSTER_SIZE
;  020  REG  20-Apr-90	Add "Invalid qualifier for tape" error
;  021  REG  20-Apr-90	Improve dynamic region error
;  022  REG  20-Apr-90	Add error for HOOK privs
;  023  REG  24-Apr-90	Add error for incorrect input volume
;  024  REG  03-May-90	Add WRTNFS to list required for hook
;  025  REG  24-May-90	Make region size error message better
;  026  REG  20-Jun-90	Add ?Error opening input disk
;  027  REG  01-Aug-90	Add PC to Unexpected error message
;  028  REG  08-AUG-90	Add OMS errors
;  029  REG  14-Aug-90	Add dynamic memory exhausted message
;  030  REG  29-Aug-90	Add "/updating" to error creating [PPN]
;
;			[RSTS V10.1]
;  031  REG  08-Mar-91	Add diagnostic messages
;  032  REG  22-Apr-91	Clarify buffer and block size messages
;-


.SBTTL	Message definition for BACKUP

.MCALL	$CUI
$CUI	MSG
$CUI	TABLE

DEFPKG	;PKGNUM=3.

; Diagnostic messages							;031
	
;   DEFMSG GD1,<"Get D ID=!OW">						;031
;   DEFMSG MD1,<"Map D ID=!OW">						;031
;   DEFMSG WRA,<".WRITA ID=!OW Bk=!OW">					;031
;   DEFMSG WRC,<"WRTCMP ID=!OW Bk=!OW">					;031
;   DEFMSG RDA,<".READA ID=!OW">					;031
;   DEFMSG RDC,<"REDCMP ID=!OW">					;031
;   DEFMSG CHK,<"-CHK ID6=!OW ID7=!OW">					;031
;   DEFMSG ASY,<"-ASY ID6=!OW ID7=!OW">					;031
;   DEFMSG QWR,<"QWRITE ID=!OW Flag=!OW">				;031
;   DEFMSG GX1,<"Get X ID=!OW">						;031
;   DEFMSG MX1,<"Map X ID=!OW">						;031

; CUI related messages

  DEFMSG  OUTDYN,<"?Dynamic memory exhausted">				;029
  DEFMSG  REQABO,<"?Request aborted by Operator">			;028
  DEFMSG  OMSERR,<"?Unexpected Operator/Message Services error">	;028
  DEFMSG  OMSNUP,<"?Operator/Message Services not running">		;028
  DEFMSG  CONARG,<"?Conflicting arguments">
  DEFMSG  INVDSK,<"?Invalid qualifier for disk">
  DEFMSG  INVTAP,<"?Invalid qualifier for tape">			;020
  DEFMSG  ILLDEV,<"?Invalid device specified">
  DEFMSG  DEVDSK,<"?Device must be disk">
  DEFMSG  DEVDMT,<"?Device must be disk or tape">
  DEFMSG  DEVNOV,<"?Device name may not be specified">
  DEFMSG  SAMSRC,<"?Source device must be the same">
  DEFMSG  BLKMUL,<"?Blocksize must be a multiple of !UW">
  DEFMSG  NEDPRV,<"?Qualifier requires !AC privilege">
  DEFMSG  ICLUER,<"?Clustersize must be a power of 2">			;013
  DEFMSG  PFNALL,<"?PPN and file specifications are not allowed with /IMAGE"> ;015

  DEFMSG  UNXERR,<"?Unexpected error !UW in !AC at !OW">		;027

; Restore (RSTRMS) messages

  DEFMSG  BADRLN,<"?Invalid record length in Backup set - record skipped"> ;003
  DEFMSG  BADSTR,<"?Unsupported record structure level - record skipped">
  DEFMSG  INVALN,<"?Invalid attribute length - attribute skipped">
  DEFMSG  INVATR,<"?Invalid attribute - attribute skipped">
  DEFMSG  LSTDTA,<"?Unable to recover part of Backup set">		;003
  DEFMSG  ERRDST,<"?Error reading Backup set">				;003
  DEFMSG  BADCRC,<"%CRC error detected for block">			;009
  DEFMSG  MISXOR,<"%XOR block missing from Backup set">			;003
  DEFMSG  ERRMOV,<"?Error mounting output disk">
  DEFMSG  WRGOVL,<"?This is not the correct output volume">
  DEFMSG  WRGIVL,<"?This is not the correct input volume">		;023
  DEFMSG  ERRROL,<"?Error reading output volume label">

  DEFMSG  NOVXOR,<"%XOR verification failed - group may be unreliable">

; Summary restore messages

  DEFMSG  SUMNFR,<"?Summary record not first record of Backup set">	;003

; File restore messages

  DEFMSG  BADATR,<"?File attributes for file [!UB,!UB]!AD may be incorrect">
  DEFMSG  INVFNL,<"?File name attribute invalid - skipping file">
  DEFMSG  ERRATR,<"?Error writing file attributes for file [!UB,!UB]!AD">
  DEFMSG  ERROPO,<"?Error opening file [!UB,!UB]!AD for output">
  DEFMSG  MISDTA,<"?Some file data in file [!UB,!UB]!AD may be missing">
  DEFMSG  NOHQUD,<"?File data in file may be incorrect">
  DEFMSG  NONAME,<"?File name attribute missing - skipping file">
  DEFMSG  NOREPL,<"!~IFile [!UB,!UB]!AD not replaced">		;004
  DEFMSG  RPTBLK,<"?File data block for file [!UB,!UB]!AD duplicated in Backup set"> ;003
  DEFMSG  SKPBLK,<"?File data block for file [!UB,!UB]!AD missing in Backup set"> ;003
  DEFMSG  UNXWRO,<"?Unexpected error writing to output file [!UB,!UB]!AD">
  DEFMSG  XTRDTA,<"%Extra file data found in file [!UB,!UB]!AD - ignoring it"> ;002
  DEFMSG  ERRDAT,<"?Error restoring file dates for file [!UB,!UB]!AD">
  DEFMSG  ERRSRN,<"?Error setting RTS name for file [!UB,!UB]!AD">
  DEFMSG  ERRSCF,<"?Error setting file flags for file [!UB,!UB]!AD">
  DEFMSG  NOTCTG,<"!~IFile [!UB,!UB]!AD restored as non-contiguous"> ;004
  DEFMSG  BADPRO,<"%File [!UB,!UB]!AD protection code is !UB, not !UB"> ;006

  DEFMSG  ERROVE,<"?Error opening file [!UB,!UB]!AD for verification">
  DEFMSG  ERRVDI,<"%Verification failure for directory information for file [!UB,!UB]!AD">
  DEFMSG  ATRMIS,<"%Verification failure for file attributes for file [!UB,!UB]!AD">
  DEFMSG  UNXVRO,<"?Unexpected error verifying file data for file [!UB,!UB]!AD">
  DEFMSG  ERRVFD,<"%Verification failure for file data for file [!UB,!UB]!AD">
  DEFMSG  ERRVFR,<"?Error obtaining file flags for file  [!UB,!UB]!AD for verification">

; Compare messages

  DEFMSG  YESNO,<'%Please answer "YES" or "NO"'>
  DEFMSG  ALLNON,<'%Applicable qualifiers are /ALL or /NONE'>		;016

; Mount messages

  DEFMSG  PLSMNI,<"!~IPlease mount image output volume:">		;011
  DEFMSG  PLSMNT,<"!~IPlease mount volume !UW of Backup set !AD">	;004
  DEFMSG  PLSMNX,<"!~FMount volume !UW on device _!AD">			;010
  DEFMSG  PLSMNO,<"!~FMount next volume on device _!AD">		;010
  DEFMSG  WRGVL2,<"!~FThis is not the correct volume - please try again"> ;010
  DEFMSG  ONLDEV,<"%Please specify only a device name">
  DEFMSG  INVCHR,<"%An unrecognized character was typed - try again">
  DEFMSG  ININOI,<"%Valid qualifiers are /INITIALIZE[=(arguments)] and /NOINITIALIZE">
  DEFMSG  ININO1,<"%Valid arguments: [NO]ERASE,[NO]EXERCISE[=0-3],CLUSTER_SIZE=1-64,[NO]QUERY">;019
  DEFMSG  ERROPS,<"?Error opening Backup set">			;003
  DEFMSG  ERROPD,<"?Error opening input disk">				;026
  DEFMSG  SAMDEV,<"%All volumes must be of the same media type">
  DEFMSG  NOSRES,<"%No qualifiers are valid">				;008
  DEFMSG  ERRASS,<"?Error assigning Backup set device">		;003
  DEFMSG  ERRINI,<"?Error initializing Backup set">			;003
  DEFMSG  INVSAT,<"%Invalid Backup set attributes - can't use it">	;003
  DEFMSG  ERRSAT,<"?Error reading Backup set attributes">		;003
  DEFMSG  ERRNFS,<"?Error opening Backup set non-file structured">	;003
  DEFMSG  DENNAV,<"!~IDensity of !UW BPI not available, using !UW BPI instead"> ;004
  DEFMSG  ERRRSL,<"?Error reading Backup set volume label">		;003
  DEFMSG  ERRRWS,<"?Error rewinding Backup set">			;003
  DEFMSG  NOTANS,<"?Backup set does not contain a valid ANSI label">	;003
  DEFMSG  WRGSET,<"%Backup set volume label is not !AD">		;003
  DEFMSG  NOTINI,<"%Volume has not been initialized">
  DEFMSG  ERRMNT,<"?Error mounting Backup set">			;003
  DEFMSG  ERRSDS,<"?Error searching for end of DOS portion of tape">
  DEFMSG  ERRCOD,<"?Error creating output directory">

; Dismount messages

  DEFMSG  PLSDSM,<"!~IPlease dismount volume !UW of Backup set !AD"> ;004
  DEFMSG  PLSDSI,<"!~IPlease dismount image output volume">		;014
  DEFMSG  CRLF,<"!~F">							;010
  DEFMSG  PLSDSX,<"!~F"<7>"Please dismount the current volume">		;010
  DEFMSG  ERRWSA,<"?Error writing Backup set attributes">		;003
  DEFMSG  ERRCSA,<"?Error closing Backup set">				;003
  DEFMSG  ERRDSD,<"?Error deassigning Backup set device">		;003

; Initialize messages

  DEFMSG  ERRCOM,<"?Error creating disk initialization command file">
  DEFMSG  ERRWCM,<"?Error writing to disk initialization command file">
  DEFMSG  ERRCJI,<"?Error creating job to initialize disk">
  DEFMSG  ERRDSM,<"?Error dismounting disk to initialize it">
  DEFMSG  OPNINI,<"?Error opening disk non-file structured to initialize it"> ;003

; General save messages

  DEFMSG  ERRWSS,<"?Error writing Backup set">			;003
  DEFMSG  ERSEOV,<"?Error setting end-of-volume flag">

; File save messages

  DEFMSG  ERROFR,<"?Error opening file [!UB,!UB]!AD for input - skipping rest of directory">
  DEFMSG  ERRRFD,<"?Error reading file [!UB,!UB]!AD block !UL">
  DEFMSG  ERRDFF,<"?Error reading file attributes for file [!UB,!UB]!AD">
  DEFMSG  ERRLOK,<"?Error performing PPN lookup">
  DEFMSG  PLCPAS,<"Writing placed files to Backup set">		;006
  DEFMSG  PLCIMG,<"Writing placed files to image volume">		;012
  DEFMSG  FILPAS,<"Writing non-placed files to Backup set">		;006
  DEFMSG  FILIMG,<"Writing non-placed files to image volume">		;012

; Account save messges

  DEFMSG  ERRRAD,<"?Error reading account data for directory [!UB,!UB]">
  DEFMSG  ERRRAT,<"?Error reading directory attributes for directory [!UB,!UB]">
  DEFMSG  ACCPAS,<"Writing account data to Backup set">		;006
  DEFMSG  ACCIMG,<"Writing accounts to image volume">			;012

; Account restore messages

  DEFMSG  ERRCAT,<"?Error creating/updating directory [!UB,!UB]">	;030
  DEFMSG  ERWRAT,<"?Error writing directory attributes for directory [!UB,!UB]">
  DEFMSG  INVDAR,<"%Invalid directory attribute record - skipping">
  DEFMSG  BADPRV,<"%Not all privileges for account [!UB,!UB] are restored"> ;006

  DEFMSG  ERRVAD,<"?Error verifying directory [!UB,!UB]">
  DEFMSG  ERVAAT,<"?Error verifying directory attributes for directory [!UB,!UB]">
  DEFMSG  VEREAT,<"%Directory attributes verification failure for directory [!UB,!UB]">

; Buffer handling messages

  DEFMSG  ERCRGN,<"?Error creating dynamic region">
  DEFMSG  NORRGN,<"?Not enough free memory to create minimum dynamic region"> ;025
  DEFMSG  RGNSML,<"!~INot enough free memory, buffer size reduced to !UB K words">		;032
  DEFMSG  REDUBK,<"!~IBlock size reduced to !UW bytes">			;032
  DEFMSG  NORBLK,<"?Not enough free memory to read backup set with blocksize !UW"> ;025

; List file messages

  DEFMSG  ERRWLF,<"?Error writing to list file">

; Hook messages

  DEFMSG  HOOSTA,<"Hooking the output volume">				;012
  DEFMSG  HOOERR,<"%Unable to hook output volume">			;012
  DEFMSG  HOOHAL,<"%RDNFS, WRTNFS, and SYSMOD required to make output disk bootable"> ;024

	.END
