	.IIF NDF S$$YDF	, .NLIST
	.IDENT	/01.03/

;
;	COPYRIGHT (c) 1982, 1983, 1984 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD
;	 MASSACHUSETTS.  ALL RIGHTS RESERVED.
;
; THIS  SOFTWARE  IS  FURNISHED  UNDER  A LICENSE AND MAY BE USED
; AND  COPIED  ONLY IN  ACCORDANCE WITH THE TERMS OF SUCH LICENSE
; AND WITH  THE INCLUSION  OF THE ABOVE  COPYRIGHT  NOTICE.  THIS
; SOFTWARE  OR ANY OTHER  COPIES  THEREOF, MAY NOT BE PROVIDED OR
; OTHERWISE MADE  AVAILABLE TO ANY OTHER PERSON.  NO TITLE TO AND
; OWNERSHIP OF THE SOFTWARE IS HEREBY TRANSFERED.
;
; THE INFORMATION  IN THIS DOCUMENT IS SUBJECT  TO CHANGE WITHOUT
; NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT  BY  DIGITAL
; EQUIPMENT CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY OF
; ITS SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.
;
;
; Modified by
;
;	J. KAUFFMAN	9-FEB-84	01.01
;		JRK298 - ADD LOGICAL NAME BLOCK OFFSET VALUES
;
;	J. W. BERZLE	03-MAY-84	01.02
;
;		JWB085 -- ADD CONTEXT BLOCK OFFSET DEFINITIONS
;
;	T. Lekas	01-Aug-84	01.03
;		TL310 -- Add definitions for access methods offset
;			 values
;
	.MACRO	LNBDF$,L,B,SYSDEF
;+
;	LOGICAL NAME BLOCK (LNB)
;-
	.ASECT
.=0
L.NLNK:'L'	.BLKW	1	;LINK WORD
L.NTBL:'L'	.BLKB	1	;LOGICAL TABLE NUMBER			;JRK298
L.NBLK:'L'	.BLKB	1	;LOGICAL NAME BLOCK TYPE		;JRK298
L.NSTS:'L'	.BLKB	1	;STATUS WORD				;JRK298
L.NGRP:'L'	.BLKB	1	;CREATOR GROUP NUMBER (GROUP TABLE ONLY);JRK298
L.NUCB:'L'								;JRK298
L.NTCB:'L'	.BLKW	1	;CREATOR UCB (USER) OR TCB (TASK)	;JRK298
L.NLNS:'L'	.BLKB	1	;SIZE OF LOGICAL NAME STRING		;JRK298
L.NENS:'L'	.BLKB	1	;LENGTH OF EQUIVALENCE NAME STRING	;JRK298
L.NNAM:'L'			;VARIABLE LENGTH LOGICAL NAME STRING	;**-3
L.NHSZ='B'.			;SIZE OF LOGICAL NAME BLOCK HEADER
;+
;  TABLE NUMBER DEFINITIONS
;-
LT.SYS='B'0			;SYSTEM WIDE LOGICAL NAME
LT.GRP='B'1			;GROUP LOGICAL NAME (UIC GROUP NUMBER)
LT.USR='B'2			;USER SPECIFIC LOGICAL NAME
LT.TSK='B'3			;TASK SPECIFIC LOGICAL NAME
;+									;JRK298
; STATUS BIT DEFINITIONS						;JRK298
;-									;JRK298
LS.TRM='B'1			;LOGICAL HAS A TERMINAL STATUS		;JRK298
									;JRK298
									;JWB085
;+									;JWB085
;  CONTEXT BLOCK OFFSETS FOR DDS STORAGE				;JWB085
;-									;JWB085
.=0									;JWB085
C.REF:'L'	.BLKB	1	;REFERENCE COUNT			;JWB085
C.DDSL:'L'	.BLKB	1	;LENGTH OF DDS				;JWB085
C.CUIC:'L'	.BLKW	1	;UIC FOR CLOCK BLOCK PROPAGATION	;JWB085
C.FIXL='B'.			;FIXED LENGTH OF CONTEXT BLOCK		;JWB085
C.DDS:'L'								;JWB085
									;JWB085
									;TL310
;+									;TL310
; Definitions of the offsets for the parse block.			;TL310
;									;TL310
;	NOTE:								;TL310
;									;TL310
;	These definitions are the same as those in DRPFN.MAC.		;TL310
;	Any change here must be reflected there.			;TL310
;-									;TL310
.=0									;TL310
O$FLAG:'L'	.BLKW	1		;Output flags			;TL310
O$STAT:'L'	.BLKW	1		;Status value			;TL310
O$NODS:'L'	.BLKW	1		;Node spec size			;TL310
O$NODA:'L'	.BLKW	1		;Node spec address		;TL310
O$DEVS:'L'	.BLKW	1		;Device spec size		;TL310
O$DEVA:'L'	.BLKW	1		;Device spec address		;TL310
O$DIRS:'L'	.BLKW	1		;Dir spec size			;TL310
O$DIRA:'L'	.BLKW	1		;Dir spec address		;TL310
O$NAMS:'L'	.BLKW	1		;Nam spec size			;TL310
O$NAMA:'L'	.BLKW	1		;Nam spec address		;TL310
O$TYPS:'L'	.BLKW	1		;Typ spec size			;TL310
O$TYPA:'L'	.BLKW	1		;Typ spec address		;TL310
O$VERS:'L'	.BLKW	1		;Version spec size		;TL310
O$VERA:'L'	.BLKW	1		;Version spec address		;TL310
O$TRLS:'L'	.BLKW	1		;Trailing portion size		;TL310
O$TRLA:'L'	.BLKW	1		;Trailing portion address	;TL310
O$ACCS:'L'	.BLKW	1		;Access spec size		;TL310
O$ACCA:'L'	.BLKW	1		;Access spec address		;TL310
O$LTYP:'L'	.BLKB	1		;Logical type			;TL310
		.BLKB	1		;Reserved			;TL310
O$PLEN='B'.				;Length of parse block		;TL310
									;TL310
;+									;TL310
; Definitions of the values for the parse block status field O$STAT.	;TL310
;									;TL310
;	NOTE:								;TL310
;									;TL310
;	These definitions are the same as those in RMSLIB.MLB.		;TL310
;	Any change here must be reflected there.			;TL310
;-									;TL310
SU$SUC	='B'1			;Operation successful			;TL310
ER$NOD	='B'175550		;Error in node name			;TL310
ER$DEV	='B'177100		;Bad device, or inappropriate device typ;TL310
ER$DIR	='B'177060		;Error in directory name		;TL310
ER$FNM	='B'176420		;Error in file name			;TL310
ER$TYP	='B'174540		;Error in file type extension		;TL310
ER$VER	='B'174460		;Error in version number		;TL310
ER$ESS	='B'176640		;Expanded string area too short		;TL310
ER$XTR	='B'174340		;Extraneous field detected during parse	;TL310
									;TL310
;+									;TL310
; Definitions of the flag bits in the parse block flags field O$FLAG.	;TL310
;									;TL310
;	NOTE:								;TL310
;									;TL310
;	These definitions are the same as those in RMSLIB.MLB.		;TL310
;	Any change here must be reflected there.			;TL310
;-									;TL310
FS$NOD	='B'400			;Node present				;TL310
FS$DEV	='B'200			;Device present				;TL310
FS$DIR	='B'100			;Directory present			;TL310
FS$QUO	='B'2000		;Quoted filename present		;TL310
FS$NAM	='B'4			;Filename present			;TL310
FS$TYP	='B'2			;File type present			;TL310
FS$VER	='B'1			;File version present			;TL310
FS$WCH	='B'4000		;Wildcard character present		;TL310
FS$WDI	='B'1000		;Wild directory				;TL310
FS$WNA	='B'40			;Wild filename				;TL310
FS$WTY	='B'20			;Wild file type				;TL310
FS$WVE	='B'10			;Wild file version			;TL310
									;TL310
;+									;TL310
; Definitions of the values for the parse block logical type field O$LTY;TL310
;									;TL310
;	NOTE:								;TL310
;									;TL310
;	These definitions are the same as those in DRPFN.MAC.		;TL310
;	Any change here must be reflected there.			;TL310
;-									;TL310
P.LNON	='B'0		;No logical name present			;TL310
P.LNAM	='B'1		;The filename may be a logical name		;TL310
P.LDEV	='B'2		;The device name may be a logical name		;TL310
P.LNOD	='B'3		;The node specification may be a logical name	;TL310
									;TL310
	.PSECT								;**-8
	.MACRO	LNBDF$	X,Y,Z
	.ENDM
	.ENDM
									;JRK298
	.IIF NDF S$$YDF	, .LIST						;JRK298
									;JRK298
