; RSXCRF.CMD
;
; CRF COMMAND FILE TO CREF THE RSTS/E RSX (RSX.RTS) RUN-TIME SYSTEM
;
; KCG	15-Mar-84	Removed BP2 stuff
;
LST:RSXPRE.LST/-SP
LST:RSXRTS.LST/-SP
LST:RSXIO .LST/-SP
LST:RSXAST.LST/-SP
LST:RSXKBM.LST/-SP
LST:RSXAT .LST/-SP
LST:RSXMCR.LST/-SP
LST:RSXHLP.LST/-SP
LST:PATCH .LST/-SP
LST:ODT   .LST/-SP
LST:ODTID .LST/-SP
LST:TRACE .LST/-SP
