; RSXMAC.CMD
;
; LBR COMMAND FILE FOR ENTERING THE RSX MACRO MODULES INTO RSXMAC.SML
;
; REG	25-JUL-87	UPDATE FOR RSX CHANGES
; WRM	25-May-88	Add EXTM$ (extmlb.mac)
; WRM	20-Apr-89	Add SSTX$, clean up
;
SYSTEM:RSXMAC.SML/CR:150.:0.:512.:MAC
SYSTEM:RSXMAC.SML/SZ=RSX:BOM
SYSTEM:RSXMAC.SML/SZ=RSX:RXMDIR
SYSTEM:RSXMAC.SML/SZ=RSX:EXTM
SYSTEM:RSXMAC.SML/SZ=RSX:RSTSMC
SYSTEM:RSXMAC.SML/SZ=RSX:PCODE
SYSTEM:RSXMAC.SML/SZ=RSX:SNPMAC
SYSTEM:RSXMAC.SML/SZ=RSX:CSM
SYSTEM:RSXMAC.SML/SZ=RSX:TTSYM
SYSTEM:RSXMAC.SML/SZ=RSX:LNBDF
SYSTEM:RSXMAC.SML/SZ=RSX:FEADF
SYSTEM:RSXMAC.SML/SZ=RSX:TFEA
SYSTEM:RSXMAC.SML/SZ=FCS:FCSMAC
SYSTEM:RSXMAC.SML/SZ=FCS:PRTMAC
SYSTEM:RSXMAC.SML/SZ=FCS:QIOMAC
SYSTEM:RSXMAC.SML/SZ=UTL:CSIMAC
SYSTEM:RSXMAC.SML/SZ=UTL:GCLMAC
SYSTEM:RSXMAC.SML/SZ=UTL:EGCMMA
SYSTEM:RSXMAC.SML/SZ=UTL:HLPMAC
SYSTEM:RSXMAC.SML/SZ=UTL:TPMAC
SYSTEM:RSXMAC.SML/SZ=TKB:HDRDF
SYSTEM:RSXMAC.SML/SZ=TKB:LBLDF
