; SYSLIB.CMD
;
; LBR COMMAND FILE FOR ENTERING ALL THE RSX MODULES INTO SYSLIB.OLB
;
; KCG	15-Mar-84	Removed BP2 stuff
; KCG	10-May-84	Removed obsolete files and added MSRSUB
;
;SYSTEM:SYSLIB.OLB/CR:167.:1024.:20.:OBJ
SYSTEM:SYSLIB.OLB/RP    =SYSTEM:ERR.STB/SS
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RSXRTS
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RSXIO 
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RSXAST
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RSXKBM
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RSXAT 
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RSXMCR
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RSXHLP
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:PATCH 
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:ODT
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:ODTID
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:TRACE
SYSTEM:SYSLIB.OLB/RP/-EP=SYSTEM:RTSODT
;
SYSTEM:DIRSYM.TMP=SYSTEM:SYSLIB.OLB/EX:DIRSYM
SYSTEM:FCSGBL.TMP=SYSTEM:SYSLIB.OLB/EX:FCSGBL
SYSTEM:QIOSYM.TMP=SYSTEM:SYSLIB.OLB/EX:QIOSYM
;
SYSTEM:SYSLIB.OLB/RP=SYSTEM:DIRSYM.TMP/SS
SYSTEM:SYSLIB.OLB/RP=SYSTEM:FCSGBL.TMP/SS
SYSTEM:SYSLIB.OLB/RP=SYSTEM:QIOSYM.TMP/SS
SYSTEM:SYSLIB.OLB/RP=D:[170,76]MSRSUB.RXO
SYSTEM:SYSLIB.OLB/RP=D:[170,76]DNEHLL.RXO
SYSTEM:SYSLIB.OLB/RP=D:[170,76]DNECCI.OBJ
