$JOB/DCL/NOLIMIT/ERROR:FATAL/PRIORITY:-16 [1,170]
$SWITCH BAS4F

$!+
$! UTLBLD.CTL - Build the System Utility Manager UTLMGR
$!-

$RUN $UTILTY
REMOVE LOGICAL LIB
ADD LOGICAL D:$ LIB
REMOVE LOGICAL CMN
ADD LOGICAL D:[170,0] CMN
REMOVE LOGICAL CUI
ADD LOGICAL D:[170,19] CUI
LIST LOGICAL
EXIT
$EOD

$ASSIGN D:[1,1] LB
$ASSIGN D:[170,101] SYSTEM
$ASSIGN D:[170,101] LST

LST

$!
$! Assemble associated MAC files
$!
$RUN LIB:MAC
SYSTEM:UTYKEY,SYSTEM:UTYKEY/CR/-SP=CMN:COMMON,CUI:CUIMLB/ML,SYSTEM:UTYKEY
SYSTEM:UTYCUI,SYSTEM:UTYCUI/CR/-SP=CMN:COMMON,CUI:CUIMLB/ML,SYSTEM:UTYCUI
SYSTEM:UTLMSG,SYSTEM:UTLMSG/CR/-SP=CMN:COMMON,CUI:CUIMLB/ML,SYSTEM:UTLMSG
SYSTEM:GETLOG,SYSTEM:GETLOG/CR/-SP=CMN:COMMON,SYSTEM:GETLOG
SYSTEM:GETFQB,SYSTEM:GETFQB/CR/-SP=CMN:COMMON,SYSTEM:GETFQB
$EOD

$!
$! CREF the LST files
$!
$RUN LIB:CRF
SYSTEM:UTYKEY.LST
SYSTEM:UTYCUI.LST
SYSTEM:UTLMSG.LST
SYSTEM:GETLOG.LST
SYSTEM:GETFQB.LST
$EOD


$!
$! Compile all BP2 modules
$!
$RUN LIB:BP2IC2

SET /LIST/CROSS:NOKEY

OLD SYSTEM:UTLMGR
COMPILE SYSTEM:UTLMGR/CHAIN/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UFORCE
COMPILE SYSTEM:UFORCE/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UALLOC
COMPILE SYSTEM:UALLOC/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UREMJB
COMPILE SYSTEM:UREMJB/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UJOB
COMPILE SYSTEM:UJOB/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USPRIV
COMPILE SYSTEM:USPRIV/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USWTCH
COMPILE SYSTEM:USWTCH/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UDTACH
COMPILE SYSTEM:UDTACH/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UDATE
COMPILE SYSTEM:UDATE/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UDEV
COMPILE SYSTEM:UDEV/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:URTS
COMPILE SYSTEM:URTS/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UASIGN
COMPILE SYSTEM:UASIGN/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USHLOG
COMPILE SYSTEM:USHLOG/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UCMND
COMPILE SYSTEM:UCMND/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USCMND
COMPILE SYSTEM:USCMND/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UCACHE
COMPILE SYSTEM:UCACHE/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UFILE
COMPILE SYSTEM:UFILE/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USHPRV
COMPILE SYSTEM:USHPRV/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USWAP
COMPILE SYSTEM:USWAP/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USYSTM
COMPILE SYSTEM:USYSTM/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UEMT
COMPILE SYSTEM:UEMT/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USHSYS
COMPILE SYSTEM:USHSYS/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USHDEV
COMPILE SYSTEM:USHDEV/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:USHLPD
COMPILE SYSTEM:USHLPD/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UOVRLY
COMPILE SYSTEM:UOVRLY/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:UINDEX
COMPILE SYSTEM:UINDEX/NODOUBLE/NODEBUG/OBJ/NOWARN

OLD SYSTEM:DISPLY
COMPILE SYSTEM:DISPLY/NODOUBLE/NODEBUG/OBJ/NOWARN

SCRATCH
EXIT
$EOD

$RUN LIB:TKB
@SYSTEM:UTLMGR
$EOD

$RUN LIB:PIP
SYSTEM:UTLMGR.TSK<232>/RE/W
$EOD
$!
$! UTLMGR build complete
$!
$EOJ
