$! BLDODT.COM - Build the unsupported ODT.4TH Utility
$!
$ ASSIGN D:[170,107] IN
$ ASSIGN D:[170,107] OUT
$ ASSIGN D:[170,107] FORTH

$_SET JOB/KEYBOARD_MONITOR=FORTH
FLOAD IN:ODT.FTH
SAVE MAIN OUT:ODT
(BYE)
$_EOD
$_EXIT
