$JOB/CCL/NOLIMIT [170,33]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$SWITCH RT11
$R SY:$MACRO
DMPHIS,LSD:DMPHIS/C=SY:#COMMON,DMPHIS
$R SY:$LINK
DMPHIS.SV/Z,LSD:DMPHIS,SY:DMPHIS=SY:DMPHIS
$R SY:$SILUS
DMPHIS.SAV/S,LSD:DMPHIS=DMPHIS.SV/N
DMPHIS
$R SY:$PIP.SAV
DMPHIS.STB,DMPHIS.OBJ,DMPHIS.SV/DE/NOLOG
$EOJ
