$JOB/CCL/NOLIMIT/PRI:-16 [170,33]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$SWITCH RT11
$RUN SY:$PIP.SAV
SY:*.BAK/DE:NOWARN/NOLOG
SY:HISTOG.TXT<40>/RE/NOLOG
SY:MAPHIS.BAS<40>/RE/NOLOG
SY:ADDHIS.BAS<40>/RE/NOLOG
$SW BASIC
$OLD SY:ADDHIS
$COMPILE SY:ADDHIS
$OLD SY:MAPHIS
$COMPILE SY:MAPHIS
$EOJ
