$JOB/CCL/NOLIMIT [170,33]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$SWITCH RT11
$R SY:$MACRO
PRTHIS,LSD:PRTHIS/C=SY:#COMMON,PRTHIS
$R SY:$LINK
PRTHIS.SV/Z,LSD:PRTHIS,SY:PRTHIS=SY:PRTHIS
$R SY:$SILUS
PRTHIS.SAV/S,LSD:PRTHIS=PRTHIS.SV/N
PRTHIS
$R SY:$PIP.SAV
PRTHIS.STB,PRTHIS.OBJ,PRTHIS.SV/DE/NOLOG
$EOJ
