TITLE	CFGDEF,<Configuration file definitions>,0A,10-MAY-91,KPH/DSD/DRP/VAM

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	Edit history for CFGDEF

;+
;
;			[RSTS V9.6]
;  000	KPH  27-Sep-87	Creation - finally!
;  001  KPH  02-Nov-87	Add LAT support
;  002	DSD  05-Feb-88	Add NODVR load CONFIG.SYS bit
;
;			[RSTS V9.7]
;  003	DRP  29-Dec-88	Add APT support
;  004  VAM  25-Jan-89	Add cells for to-be-started SIL name and SWAP MAX.
;			Make CFGSIZ true length of CONFIG.SYS buffer.
;  005  VAM  23-May-90	Add byte to guarantee that SIL name is ASCIZ.
;-

.SBTTL	Buffer layout for CONFIG.SYS file

.DSECT	,NOCREF			;File/buffer layout for CONFIG.SYS

CFG$VE:	.BLKB			;Major version number
CFG$RE:	.BLKB			;Format revision level
CFG$01:	.BLKW			;First feature flag word
CFG$PK:	.BLKB			;Count of pseudo keyboards
	.BLKB			;Reserved.				;004
CFG$SM:	.BLKB			;New SWAP MAX to set at startup time	;004
	.BLKB			;Reserved.				;004
CFG$NA:	.BLKB	6		;Name of new SIL to start		;004
CFG$ZE:	.BLKB			;This byte marks the end of the ASCII	;005
				; SIL name above.  It is set to 0 by	;005
				; UTLMGR (for the SET SYSTEM/MONITOR	;005
				; command), by INSTAL (when a SIL is	;005
				; installed and the name is put into	;005
				; CONFIG.SYS), and by COPY (when it	;005
				; puts "SYSGEN" into CONFIG.SYS so that	;005
				; SYSGEN.SIL will be auto-started).	;005
				; This guarantees that the SIL name is	;005
				; ASCIZ.				;005
.EVEN									;004
CFGSIZ:				;Size of configuration area		;004

; INIT.SYS uses the version number and revision number to determine if
; it can use the CONFIG.SYS file. The intent is that INIT.SYS will look
; at the version number of a CONFIG.SYS file, and if it doesn't match
; the version that INIT was built with, the file will be ignored.
; If it does match, INIT will look at the revision number. If the
; revision number is higher than or equal to INIT's revision number,
; INIT will take no special action. If the revision number is lower,
; INIT will apply defaults for those fields which have been added
; since the revision.

CFG.VE	=:	1		;Current version number of CONFIG.SYS
CFG.RE	=:	0		;Current revision number of CONFIG.SYS

; Define the feature flag bits. INIT uses these to control the inclusion
; of various software features.

.BSECT	,NOCREF			;In feature flag word #1 [CFG$01]

C1$FMS:	.BLKB	.		;If set, include FMS support
C1$LAT:	.BLKB	.		;If set, don't include LAT
C1$NOD:	.BLKB	.		;If set, load async DDCMP		;002
C1$KBX:	.BLKB	.		;If set, load auxiliary KBX driver	;003
C1$ASY:	.BLKB	.		;If set, SHO SYSTEM shows asynch status	;005
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved
	.BLKB	.		;Reserved

