	.INCLUDE	/CMN:COMMON/
TITLE	ERR,<SYSTEM ERROR MESSAGE TEXTS>,0A,10-MAY-91,MHB/AWR/BGN/SDL/DNG/GPK/KPH/DRP

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	EDIT HISTORY FOR ERR

;+
;
;  000  RRF  06-MAR-81	CREATION - COPIED FROM V7.0-07
;  001	AWR  24-APR-81  CHANGE 'USER DATA ERROR' TO 'DATA ERROR' (DATERR)
;  002  BGN  04-FEB-82  CHANGE ERR MSG #'S - 176-8,180-2,227-8,245-7
;  003  SDL  05-OCT-82  CHANGE 'CLEANing' TO 'REBUILDing' IN INTPAK MESSAGE
;  004  DNG  18-FEB-83  ADD ERROR MESSAGES 185-7 FOR BP2
;  005	GPK  06-Mar-83	Change messages for ICFP, add EOV and QUOTA
;  006	GPK  17-Jan-85	Change B.xxx to be severe errors
;  007  KPH  07-Feb-85	Change PAKLCK and PRIVAT to be more meaningful
;  008	GPK  29-Mar-85	Reinstate SATTBD, upcase "ANSI"
;  009	DRP  26-Aug-86	Added err 196. - ?REMAP string is not static
;
;			[RSTS V10.0]
;  010	FEK  29-May-90	Change "Illegal argument in LOG" message
;
;-

.ENABL	LC

.MACRO	ERRDEF	NAME,TYPE,TEXT
.DSABL	CRF
.ASECT
.NCHR	$$$$$$,	<NAME>
.IF	EQ	$$$$$$
$$$$$$	=	.
.LIST
	.BLKB
.NLIST
	ORG	ERR,$$$$$$*40
.IFF
.IF	EQ	$$$$$$-6
.ENABL	CRF
.LIST
NAME::.BLKB
.NLIST
.DSABL	CRF
.IFF
.ENABL	CRF
.LIST
NAME::	.BLKB
.NLIST
.DSABL	CRF
.ENDC
	ORG	ERR,NAME*40
.ENDC
$$$$$$	=	.
.IF	NB	<TYPE>
	 .ASCII	"TYPE"TEXT
.IFF
	 .ASCII	TEXT
.ENDC
$$$$$$	=	.-$$$$$$
.RADIX 10.
.IRP	LEN,<\$$$$$$>
.IF	EQ	$$$$$$
.ERROR	;NAME MESSAGE LENGTH OF LEN'. IS ILLEGAL
.ENDC
.IF	GT	$$$$$$-28.
.ERROR	;NAME MESSAGE LENGTH OF LEN'. IS ILLEGAL
.ENDC
.ENDM
.RADIX	8.
.REPT	32.-$$$$$$
.NLIST
	.BYTE	0
.LIST
.ENDR
.ENABL	CRF
.ENDM	ERRDEF

	ORG	ERR

.SBTTL	THE MESSAGES...

.DSECT

ERRDEF	      , ,<"RSTS/E error messages">
ERRDEF	BADDIR,??,<"Bad directory for device">				;005
ERRDEF	BADNAM,?,<"Illegal file name">
ERRDEF	INUSE ,?,<"Account or device in use">
ERRDEF	NOROOM,?,<"No room for user on device">
ERRDEF	NOSUCH,?,<"Can't find file or account">
ERRDEF	NODEVC,?,<"Not a valid device">
ERRDEF	NOTCLS,?,<"I/O channel already open">
ERRDEF	NOTAVL,?,<"Device not available">
ERRDEF	NOTOPN,?,<"I/O channel not open">
ERRDEF	PRVIOL,?,<"Protection violation">
ERRDEF	EOF   ,?,<"End of file on device">
ERRDEF	ABORT ,??,<"Fatal system I/O failure">				;005
ERRDEF	DATERR,?,<"Data error on device">
ERRDEF	HNGDEV,?,<"Device hung or write locked">
ERRDEF	HNGTTY,?,<"Keyboard wait exhausted">
ERRDEF	FIEXST,?,<"Name or account now exists">
ERRDEF	DTOOOF,?,<"Too many open files on unit">
ERRDEF	BADFUO,?,<"Illegal SYS() usage">
ERRDEF	INTLCK,?,<"Disk block is interlocked">
ERRDEF	WRGPAK,?,<"Pack IDs don't match">
ERRDEF	NOTMNT,?,<"Disk pack is not mounted">
ERRDEF	PAKLCK,?,<"Device is restricted">				;007
ERRDEF	BADCLU,?,<"Illegal cluster size">
ERRDEF	PRIVAT,?,<"Account does not exist">				;007
ERRDEF	INTPAK,%,<"Disk pack needs REBUILDing">				;005
ERRDEF	BADPAK,??,<"Disk pack mount error">				;005
ERRDEF	DETKEY,?,<"I/O to detached keyboard">
ERRDEF	CTRLCE, ,<"Programmable ^C trap">				;005
ERRDEF	SATTBD,??,<"Corrupted file structure">				;008
ERRDEF	DEVNFS,?,<"Device not file-structured">
ERRDEF	BADCNT,?,<"Illegal byte count for I/O">
ERRDEF	NOBUFS,?,<"No buffer space available">
ERRDEF	B.4   ,??,<"Odd address trap">					;006
ERRDEF	B.10  ,??,<"Reserved instruction trap">				;006
ERRDEF	B.250 ,??,<"Memory management trap">				;006
ERRDEF	B.STAK,??,<"SP stack overflow">					;005
ERRDEF	B.SWAP,??,<"Disk error during swap">				;005
ERRDEF	B.PRTY,??,<"Memory parity failure">				;005
ERRDEF	MAGSEL,?,<"Magtape select error">
ERRDEF	MAGRLE,?,<"Magtape record length error">
ERRDEF	NRRTS ,??,<"Non-res run-time system">				;005
ERRDEF	VCSERR,?,<"Virtual buffer too large">
ERRDEF	VCAERR,?,<"Virtual array not on disk">
ERRDEF	SIZERR,?,<"Matrix or array too big">
ERRDEF	VCOERR,?,<"Virtual array not yet open">
ERRDEF	BSERR ,?,<"Illegal I/O Channel">
ERRDEF	LINERR,?,<"Line too long">
ERRDEF	FLTERR,%,<"Floating point error">
ERRDEF	EXPERR,%,<"Argument too large in EXP">
ERRDEF	FMTERR,%,<"Data format error">
ERRDEF	FIXERR,%,<"Integer error">
ERRDEF	BDNERR,?,<"Illegal number">
ERRDEF	LOGERR,%,<"Illegal argument">			; in LOG	;010
ERRDEF	SQRERR,%,<"Imaginary square roots">
ERRDEF	SUBERR,?,<"Subscript out of range">
ERRDEF	MINVER,?,<"Can't invert matrix">
ERRDEF	ODD   ,?,<"Out of data">
ERRDEF	ONBAD ,?,<"ON statement out of range">
ERRDEF	NEDERR,?,<"Not enough data in record">
ERRDEF	IOLERR,?,<"Integer overflow, FOR loop">
ERRDEF	DIVBY0,%,<"Division by 0">
ERRDEF	NORTS ,?,<"No run-time system">
ERRDEF	FIELDE,?,<"FIELD overflows buffer">
ERRDEF	NORACS,?,<"Not a random access device">
ERRDEF	NOTMTA,?,<"Illegal MAGTAPE() usage">
ERRDEF	ERRERR,?,<"Missing special feature">
ERRDEF	BADSWT,?,<"Illegal switch usage">
ERRDEF	EOV   ,?,<"End of volume">					;005
ERRDEF	QUOTA ,?,<"Quota exceeded">					;005
ERRDEF	      ,??,<"Unused error message 70">				;005
ERRDEF	STMERR,?,<"Statement not found">
ERRDEF	EXITTM,?,<"RETURN without GOSUB">
ERRDEF	EXITNR,?,<"FNEND without function call">
ERRDEF	UNDFNI,?,<"Undefined function called">
ERRDEF	COSERR,?,<"Illegal symbol">
ERRDEF	TLOPNV,?,<"Illegal verb">
ERRDEF	TLNZSP,?,<"Illegal expression">
ERRDEF	TLNOIT,?,<"Illegal mode mixing">
ERRDEF	TLIFFE,?,<"Illegal IF statement">
ERRDEF	TLCONI,?,<"Illegal conditional clause">
ERRDEF	TLNOTF,?,<"Illegal function name">
ERRDEF	TLQDUM,?,<"Illegal dummy variable">
ERRDEF	TLMFND,?,<"Illegal FN redefinition">
ERRDEF	TLRNNM,?,<"Illegal line number(s)">
ERRDEF	MODERR,?,<"Modifier error">
ERRDEF	      ,?,<"Can't Compile Statement">
ERRDEF	OUTOAS,?,<"Expression too complicated">
ERRDEF	FUNERR,?,<"Arguments don't match">
ERRDEF	TLTMAF,?,<"Too many arguments">
ERRDEF	TLINCD,%,<"Inconsistent function usage">
ERRDEF	CPNSDF,?,<"Illegal DEF nesting">
ERRDEF	CPUPFR,?,<"FOR without NEXT">
ERRDEF	CPUFNX,?,<"NEXT without FOR">
ERRDEF	CPUPDF,?,<"DEF without FNEND">
ERRDEF	CPUPED,?,<"FNEND without DEF">
ERRDEF	TLJNKY,?,<"Literal string needed">
ERRDEF	TLNOFN,?,<"Too few arguments">
ERRDEF	SASYNE,?,<"Syntax error">
ERRDEF	SAFNOS,?,<"String is needed">
ERRDEF	SASNOI,?,<"Number is needed">
ERRDEF	TLURTP,?,<"Data type error">
ERRDEF	TLXDIM,?,<"1 or 2 dimensions only">
ERRDEF	FUCORE,??,<"Program lost-Sorry">				;005
ERRDEF	RESERR,?,<"RESUME and no error">
ERRDEF	DIMED2,?,<"Redimensioned array">
ERRDEF	TLIDIM,%,<"Inconsistent subscript use">
ERRDEF	NOGOTO,?,<"ON statement needs GOTO">
ERRDEF	EOSERR,?,<"End of statement not seen">
ERRDEF	TLCNTD,?,<"What?">
ERRDEF	TLPRNM,?,<"Bad line number pair">
ERRDEF	EDBMCE,?,<"Not enough available memory">
ERRDEF	EDEXON,?,<"Execute only file">
ERRDEF	NRNERR,?,<"Please use the RUN command">
ERRDEF	EDCONE,?,<"Can't CONTinue">
ERRDEF	EDARSV,?,<"File exists-RENAME/REPLACE">
ERRDEF	PRERRS,?,<"PRINT-USING format error">
ERRDEF	UDMERR,?,<"Matrix or array without DIM">
ERRDEF	PRNER1,?,<"Bad number in PRINT-USING">
ERRDEF	NONOIM,?,<"Illegal in immediate mode">
ERRDEF	PRNER2,?,<"PRINT-USING buffer overflow">
ERRDEF	BADERR,?,<"Illegal statement">
ERRDEF	DISERR,?,<"Illegal FIELD variable">
ERRDEF	STPERR, ,<"Stop">
ERRDEF	DIMERR,?,<"Matrix dimension error">
ERRDEF	NOMATH,?,<"Wrong math package">
ERRDEF	XCDCOR,??,<"Maximum memory exceeded">				;005
ERRDEF	SCAERR,%,<"SCALE factor interlock">
ERRDEF	      ,?,<"Tape records not ANSI">
ERRDEF	      ,?,<"Tape BOT detected">
ERRDEF	      ,?,<"Key not changeable">
ERRDEF	      ,?,<"No current record">
ERRDEF	      ,?,<"Record has been deleted">
ERRDEF	      ,?,<"Illegal usage for device">
ERRDEF	      ,?,<"Duplicate key detected">
ERRDEF	      ,?,<"Illegal usage">
ERRDEF	      ,?,<"Illegal or illogical access">
ERRDEF	      ,?,<"Illegal key attributes">
ERRDEF	      ,?,<"File is locked">
ERRDEF	      ,?,<"Invalid file options">
ERRDEF	      ,?,<"Index not initialized">
ERRDEF	      ,?,<"Illegal operation">
ERRDEF	      ,?,<"Illegal record on file">
ERRDEF	      ,?,<"Bad record identifier">
ERRDEF	      ,?,<"Invalid key of reference">
ERRDEF	      ,?,<"Key size too large">
ERRDEF	      ,?,<"Tape not ANSI labeled">				;008
ERRDEF	      ,?,<"RECORD number exceeds max">
ERRDEF	      ,?,<"Bad RECORDSIZE on OPEN">
ERRDEF	      ,?,<"Not at end of file">
ERRDEF	      ,?,<"No primary key specified">
ERRDEF	      ,?,<"Key field beyond record end">
ERRDEF	      ,?,<"Illogical record accessing">
ERRDEF	      ,?,<"Record already exists">
ERRDEF	      ,?,<"Record/bucket locked">
ERRDEF	      ,?,<"Record not found">
ERRDEF	      ,?,<"Size of record invalid">
ERRDEF	      ,?,<"Record on file too big">
ERRDEF	      ,?,<"Primary key out of sequence">
ERRDEF	      ,?,<"Key larger than record">
ERRDEF	      ,?,<"File attributes not matched">
ERRDEF	      ,?,<"Move overflows buffer">
ERRDEF	      ,?,<"Cannot open file">
ERRDEF	      ,?,<"No file name">
ERRDEF	      ,?,<"Terminal fmt file required">
ERRDEF	      ,?,<"Cannot position to EOF">
ERRDEF	      ,?,<"Negative fill or string len">
ERRDEF	      ,?,<"Illegal record format">
ERRDEF	      ,?,<"Illegal ALLOW clause">
ERRDEF	      ,??,<"Unused ERROR message 169">				;005
ERRDEF	      ,?,<"Indexed not fully optimized">
ERRDEF	      ,?,<"RRV not fully updated">
ERRDEF	      ,?,<"Record LOCK failed">
ERRDEF	      ,?,<"Invalid RFA field">
ERRDEF	      ,?,<"Unexpired file date">
ERRDEF	      ,?,<"Node name error">
ERRDEF	      ,?,<"Negative TAB not allowed">
ERRDEF	      ,?,<"Too much data in record">
ERRDEF	      ,?,<"OPEN Error - file corrupted">
ERRDEF	      ,??,<"Unused ERROR message 179">				;005
ERRDEF	      ,?,<"No support for op in task">
ERRDEF	      ,%,<"Decimal overflow">
ERRDEF	      ,?,<"Network operation rejected">
ERRDEF	      ,?,<"REMAP overflows buffer">
ERRDEF	      ,?,<"Unaligned REMAP variable">
ERRDEF	      ,%,<"RECORDSIZE overflows MAP">
ERRDEF	      ,?,<"Improper error handling">
ERRDEF	      ,?,<"Illegal record lock clause">
ERRDEF	      ,??,<"Unused ERROR message 188">				;005
ERRDEF	      ,??,<"Unused ERROR message 189">				;005
ERRDEF	      ,??,<"Unused ERROR message 190">				;005
ERRDEF	      ,??,<"Unused ERROR message 191">				;005
ERRDEF	      ,??,<"Unused ERROR message 192">				;005
ERRDEF	      ,??,<"Unused ERROR message 193">				;005
ERRDEF	      ,??,<"Unused ERROR message 194">				;005
ERRDEF	      ,??,<"Unused ERROR message 195">				;005
ERRDEF	      ,?,<"REMAP string is not static">				;009
ERRDEF	      ,??,<"Unused ERROR message 197">				;005
ERRDEF	      ,??,<"Unused ERROR message 198">				;005
ERRDEF	      ,??,<"Unused ERROR message 199">				;005
ERRDEF	      ,??,<"Unused ERROR message 200">				;005
ERRDEF	      ,??,<"Unused ERROR message 201">				;005
ERRDEF	      ,??,<"Unused ERROR message 202">				;005
ERRDEF	      ,??,<"Unused ERROR message 203">				;005
ERRDEF	      ,??,<"Unused ERROR message 204">				;005
ERRDEF	      ,??,<"Unused ERROR message 205">				;005
ERRDEF	      ,??,<"Unused ERROR message 206">				;005
ERRDEF	      ,??,<"Unused ERROR message 207">				;005
ERRDEF	      ,??,<"Unused ERROR message 208">				;005
ERRDEF	      ,??,<"Unused ERROR message 209">				;005
ERRDEF	      ,??,<"Unused ERROR message 210">				;005
ERRDEF	      ,??,<"Unused ERROR message 211">				;005
ERRDEF	      ,??,<"Unused ERROR message 212">				;005
ERRDEF	      ,??,<"Unused ERROR message 213">				;005
ERRDEF	      ,??,<"Unused ERROR message 214">				;005
ERRDEF	      ,??,<"Unused ERROR message 215">				;005
ERRDEF	      ,??,<"Unused ERROR message 216">				;005
ERRDEF	      ,??,<"Unused ERROR message 217">				;005
ERRDEF	      ,??,<"Unused ERROR message 218">				;005
ERRDEF	      ,??,<"Unused ERROR message 219">				;005
ERRDEF	      ,??,<"Unused ERROR message 220">				;005
ERRDEF	      ,??,<"Unused ERROR message 221">				;005
ERRDEF	      ,??,<"Unused ERROR message 222">				;005
ERRDEF	      ,??,<"Unused ERROR message 223">				;005
ERRDEF	      ,??,<"Unused ERROR message 224">				;005
ERRDEF	      ,??,<"Unused ERROR message 225">				;005
ERRDEF	      ,??,<"Unused ERROR message 226">				;005
ERRDEF	      ,?,<"String too long">
ERRDEF	      ,?,<"RECORDTYPES not matched">
ERRDEF	      ,??,<"Unused ERROR message 229">				;005
ERRDEF	      ,?,<"No fields in image">
ERRDEF	      ,?,<"Illegal string image">
ERRDEF	      ,?,<"Null image">
ERRDEF	      ,?,<"Illegal numeric image">
ERRDEF	      ,?,<"Numeric image for string">
ERRDEF	      ,?,<"String image for numeric">
ERRDEF	      ,?,<"TIME limit exceeded">
ERRDEF	      ,?,^\"1st arg to SEQ$ > 2nd"\
ERRDEF	      ,?,<"Arrays must be same dim">
ERRDEF	      ,?,<"Arrays must be square">
ERRDEF	      ,?,<"Cannot change array dims">
ERRDEF	      ,?,<"Floating overflow">
ERRDEF	      ,?,<"Floating underflow">
ERRDEF	      ,?,<"CHAIN to non-existent line">
ERRDEF	      ,?,<"Exponentiation error">
ERRDEF	      ,?,<"Illegal exit from DEF*">
ERRDEF	      ,?,<"Error trap needs RESUME">
ERRDEF	      ,?,<"Illegal RESUME to SUBR">
ERRDEF	      ,?,<"Illegal subroutine return">
ERRDEF	      ,?,<"Argument out of bounds">
ERRDEF	      ,?,<"Not implemented">
ERRDEF	      ,?,<"Recursive subroutine call">
ERRDEF	      ,?,<"FILE ACP failure">
ERRDEF	      ,?,<"Directive error">
ERRDEF	      ,??,<"Unused ERROR message 254">				;005
ERRDEF	      ,??,<"Unused ERROR message 255">				;005

.ASECT

.IF	NE	.-400
.ERROR	;WRONG NUMBER OF ERROR MESSAGES
.ENDC

.END
