$JOB/CCL/NOLIMIT/PRI:-16 [170,0]
$ASSIGN LSD: NL
$ASSIGN NL: LSD
$DEASSIGN NL
$ASSIGN D: SY
$ASSIGN D: DK
$ASSIGN <40>
$SWITCH RT11
$SIZE 24
$R SY:LINK
ERR.ERR/Z,LSD:ERR/A/W,SY:ERR=ERR/X/B:0
$R SY:PIP
ERR.OBJ/DE/NOLOG
$EOD
$EOJ
