.IIF	NDF	L$$IST&ROOT$L,	.NLIST
.IIF	NDF	L$$IST&ROOT$L,	.DSABL CRF
TITLE	SILFMT,<SIL FORMAT DEFINITIONS>,0A,10-MAY-91,WJS/KPH

;
;		COPYRIGHT (c) 1974, 1991 BY
;	DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASS.
;
; THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
; ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
; INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
; COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
; OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
; TRANSFERRED.
;
; THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
; AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
; CORPORATION.
;
; DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY  OF ITS
; SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.
;

.SBTTL	Edit history for SILFMT

;+
;
;			[RSTS V9.0]
;  000	WJS  22-Sep-83	Creation
;
;			[RSTS V9.6]
;  001  KPH  13-Nov-87	Increase number of phases to 47
;
;-

.SBTTL	SILFMT - SIL format definitions

; Set the number of SIL index blocks allowed for this release

SI.NBL	  =:	3.		; Maximum number of SIL index blocks	;001


; Definitions of SIL Index entry

.DSECT	,NOCREF

SE.NAM:	.BLKW	2		; Name of module
SE.IDN:	.BLKW	2		; Ident of module
SE.BLK:	.BLKW			; Starting block of module
SE.STB:	.BLKW			; Starting block of STB
SE.STN:	.BLKW			; Number of entries in STB
SE.LOD:	.BLKW			; Load address of this module
SE.SIZ:	.BLKW			; Size of module (in bytes)
SE.XFR:	.BLKW			; Transfer address
SE.SZD:	.BLKW			; Size of module image of disk in blocks
SE.OVB:	.BLKW			; Block offset to module's overlay descriptors
SE.OVN:	.BLKW			; Number of overlay descriptors for module
SE.OFF:	.BLKW			; Starting offset on disk for this module
	.BLKW			; (reserved)
SE.XXX:	.BLKW			; Reserved for SAV format SILs
SE.LEN:				; Size of a SIL index entry

.ASSUME SE.LEN EQ 40


; Derive the number of modules SI.NBL SIL index blocks can contain

SI.OTH	  =:	1000/SE.LEN		; Number of entries in a non-first block
SI.1ST	  =:	SI.OTH-1		; Number of entries in first block
SI.NMD	  =:	SI.NBL-1*SI.OTH+SI.1ST	; Maximum total no of index entries

.DSECT	; Layout for SIL index as it would be directly read from disk

SI.NUM:	.BLKW			; Number of modules in SIL
SI.ENT:	.BLKB	SI.1ST*SE.LEN	; Space for first block's SIL Index entries
SI.RSV:	.BLKW	12.		; Reserved
SI.BLS:	.BLKW			; Size of this SIL in blocks.
SI.CHK:	.BLKW			; Checksum of SIL Index
SI.SIL:	.BLKW			; RAD50 "SIL" for identification
SI.MOR:	.BLKB	SI.NMD-SI.1ST*SE.LEN   ; Space for non-first blocks' entries
SI.SIZ:				; Size of SIL index in bytes

.ASSUME SI.SIZ EQ 1000*SI.NBL


.DSECT	; Layout for SIL index in core with all entries made contiguous
	;    (that is, after reading in from disk and squishing out
	;     SI.RSV through SI.CHK)

SI.NUM:	.BLKW				; Number of modules in SIL
SI.ENT:	.BLKB	SI.1ST*SE.LEN		; Space for first block's SIL Index entries
SI.RST:	.BLKB	SI.NBL-1*SI.OTH*SE.LEN	; Space for rest of blocks' entries
SI.CSZ:					; Size of "squished" SIL index in core

.ASSUME SI.RST EQ SI.RSV

.IIF	NDF	L$$IST&ROOT$L,	.ENABL CRF
.IIF	NDF	L$$IST&ROOT$L,	.LIST
