; RNOASM.CMD
;
; MAC COMMAND FILE TO ASSEMBLE RUNOFF (RNO.TSK) MODULES
;
;
;	RUNOFF VERSION M01
;
SYSTEM:COMND ,LST:COMND /CR/-SP=RSX:COMMON,RNO:RNPRE,COMND
SYSTEM:CMTAB ,LST:CMTAB /CR/-SP=RSX:COMMON,RNO:RNPRE,CMTAB
SYSTEM:ERMSG ,LST:ERMSG /CR/-SP=RSX:COMMON,RNO:RNPRE,ERMSG
SYSTEM:FMTCM ,LST:FMTCM /CR/-SP=RSX:COMMON,RNO:RNPRE,FMTCM
SYSTEM:HYPHEN,LST:HYPHEN/CR/-SP=RSX:COMMON,RNO:RNPRE,HYPHEN
SYSTEM:INDEX ,LST:INDEX /CR/-SP=RSX:COMMON,RNO:RNPRE,INDEX
SYSTEM:PINDX ,LST:PINDX /CR/-SP=RSX:COMMON,RNO:RNPRE,PINDX
SYSTEM:RNCMD ,LST:RNCMD /CR/-SP=RSX:COMMON,RNO:RNPRE,RNCMD
SYSTEM:RNFIO ,LST:RNFIO /CR/-SP=RSX:COMMON,RNO:RNPRE,RNFIO
SYSTEM:RNORSX,LST:RNORSX/CR/-SP=RSX:COMMON,RNO:RNPRE,RNORSX
SYSTEM:RUNOFF,LST:RUNOFF/CR/-SP=RSX:COMMON,RNO:RNPRE,RUNOFF
SYSTEM:START ,LST:START /CR/-SP=RSX:COMMON,RNO:RNPRE,START
