; RNOCRF.CMD
;
; CRF COMMAND FILE TO CROSS REFERENCE RUNOFF (RNO.TSK) MODULES
;
LST:COMND .LST/-SP
LST:CMTAB .LST/-SP
LST:ERMSG .LST/-SP
LST:FMTCM .LST/-SP
LST:HYPHEN.LST/-SP
LST:INDEX .LST/-SP
LST:PINDX .LST/-SP
LST:RNCMD .LST/-SP
LST:RNFIO .LST/-SP
LST:RNORSX.LST/-SP
LST:RUNOFF.LST/-SP
LST:START .LST/-SP
