; RNOLIB.CMD
;
; LBR COMMAND FILE FOR ENTERING THE RUNOFF MODULES INTO RNO.OLB
;
SYSTEM:RNO.OLB/CR:85.:0.:12.:OBJ
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:COMND
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:CMTAB
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:ERMSG
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:FMTCM
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:HYPHEN
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:INDEX
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:PINDX
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:RNCMD
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:RNFIO
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:RNORSX
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:RUNOFF
SYSTEM:RNO.OLB/RP/-EP=SYSTEM:START
