$JOB/CCL/NOLIMIT [170,36]
ASSIGN LST: NL
ASSIGN NL: LST
DEASSIGN NL
ASSIGN D: SY
ASSIGN D: DK
ASSIGN <40>
$SWITCH RT11
$R SY:LINK
LIBR.SV/Z,LST:LIBR/W,SY:LIBR=LIBR0/K:28./C
LIBR1/O:1/C
LIBR2/O:1/C
LIBR3/O:1/C
LIBR4/O:1/C
LIBR5/O:1/C
LIBR6/O:1/C
LBREM/O:1
$R SY:SILUS
LIBR.SAV/S,LST:LIBR=LIBR.SV
$R SY:PIP
LIBR.SV,LIBR.OBJ,LIBR.STB/DE/NOLOG
$EOJ
