$JOB/CCL/NOLIMIT [170,36]
ASSIGN LST: NL
ASSIGN NL: LST
DEASSIGN NL
ASSIGN D: DK
ASSIGN D: SY
ASSIGN <40>
$SWITCH RT11
$R SY:PIP
MYPAT.BAK/DE:NOWARN/NOLOG
$R SY:MACRO
MYPAT,LST:MYPAT/C=RSTCND,PAT/N:TTM/L:CND
$R SY:LINK
MYPAT.SV/Z,LST:MYPAT/W,SY:MYPAT=MYPAT/K:8.
$R SY:SILUS
MYPAT.SAV,LST:MYPAT=MYPAT.SV
$R SY:PIP
MYPAT.OBJ,MYPAT.STB,MYPAT.SV/DE/NOLOG
$EOJ
