$JOB/CCL/NOLIMIT [170,36]
ASSIGN LST: NL
ASSIGN NL: LST
DEASSIGN NL
ASSIGN D: DK
ASSIGN D: SY
ASSIGN <40>
$SWITCH RT11
$R SY:PIP
*.BAK/DE:NOWARN/NOLOG
$R SY:MACRO
PAT,LST:PAT/C=RSTCND,PAT/N:TTM/L:CND
$R SY:LINK
PAT.SV/Z,LST:PAT/W,SY:PAT=PAT/K:8.
$R SY:SILUS
PAT.SAV,LST:PAT=PAT.SV
$R SY:PIP
PAT.OBJ,PAT.STB,PAT.SV/DE/NOLOG
$EOJ
