$JOB/CCL/NOLIMIT [170,36]
ASSIGN LST: NL
ASSIGN NL: LST
DEASSIGN NL
ASSIGN D: SY
ASSIGN D: DK
ASSIGN <40>
$SWITCH RT11
$R SY:PIP
*.BAK/DE:NOWARN/NOLOG
$R SY:MACRO
SRCCOM,LST:SRCCOM/C=ULBMAC,SRCCOM
$R SY:LINK
SRCCOM.SV/Z/K:28.,LST:SRCCOM/W,SY:SRCCOM=SRCCOM/K:8.,ULBLIB
$R SY:SILUS
SRCCOM.SAV,LST:SRCCOM=SRCCOM.SV
$R SY:PIP
SRCCOM.SV,SRCCOM.OBJ,SRCCOM.STB/DE/NOLOG
$EOJ
